packages:
  - 'testplanit'
  - 'docs'
  - 'forge-app'
  - 'cli'
  - 'packages/*'
allowBuilds:
  '@forge/cli': true
  '@parcel/watcher': true
  '@prisma/client': true
  '@prisma/engines': true
  '@scarf/scarf': true
  '@swc/core': true
  '@tree-sitter-grammars/tree-sitter-yaml': true
  bcrypt: true
  cloudflared: true
  core-js: true
  core-js-pure: true
  esbuild: true
  iframe-resizer: true
  keytar: true
  msgpackr-extract: true
  msw: true
  prisma: true
  sharp: true
  tree-sitter: true
  tree-sitter-json: true
  unrs-resolver: true
  zenstack: true
