"use client";

import { useClientQueries } from "@zenstackhq/tanstack-query/react";
import { useMemo } from "react";
import { schema } from "~/zenstack/schema";
import { AUTOMATED_TEST_RUN_TYPES } from "~/utils/testResultTypes";

/**
 * In-progress automated run counts keyed by project id, for the project
 * cards on the home and projects pages.
 *
 * Same population as the "Automation Runs in Progress" card on the project
 * runs page — incomplete, non-deleted runs whose type is an automated
 * import format — but aggregated for every project the viewer can read in
 * a single groupBy instead of one query per card. Projects with no running
 * automation are absent from the map, so callers read `counts[id] ?? 0`.
 *
 * NOTE: lives in `testplanit/hooks/` (custom hooks). It MUST NOT move to
 * `testplanit/lib/hooks/` — that directory is regenerated by zenstack generate.
 */
export function useAutomationRunCounts(enabled: boolean = true): {
  counts: Record<number, number>;
  isLoading: boolean;
} {
  const { data, isLoading } = useClientQueries(schema).testRuns.useGroupBy(
    {
      by: ["projectId"],
      where: {
        isCompleted: false,
        isDeleted: false,
        testRunType: { in: AUTOMATED_TEST_RUN_TYPES },
      },
      _count: { _all: true },
    },
    {
      enabled,
      refetchOnWindowFocus: true,
    }
  );

  const counts = useMemo(() => {
    const byProject: Record<number, number> = {};
    for (const group of data ?? []) {
      byProject[group.projectId] = group._count?._all ?? 0;
    }
    return byProject;
  }, [data]);

  return { counts, isLoading };
}
