import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { renderHook, waitFor } from "@testing-library/react";
import React from "react";
import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";

import { useEffectiveRoleOnProject } from "./useEffectiveRoleOnProject";

/**
 * Tests for useEffectiveRoleOnProject — the small custom hook that resolves
 * the viewing user's effective project role (as a numeric roleId) for the
 * role-holder branch of the ReviewActionPanel visibility predicate (D-16).
 *
 * The hook reuses the canonical /api/get-user-permissions resolver
 * (don't duplicate the precedence rules — see Phase 02 Plan 02-06 PLAN
 * read_first guidance). It returns `{ roleId: number | null, isLoading }`.
 *
 * NOTE: The hook lives in `testplanit/hooks/` (custom hooks). NEVER under
 * `lib/hooks/` — that path is regenerated by ZenStack
 * (see [[feedback_no_custom_files_in_lib_hooks]]).
 */

const mockUseSession = vi.fn();
vi.mock("next-auth/react", async (importOriginal) => {
  const original = await importOriginal<typeof import("next-auth/react")>();
  return {
    ...original,
    useSession: () => mockUseSession(),
  };
});

const mockFetch = vi.fn();
vi.stubGlobal("fetch", mockFetch);

function createWrapper() {
  const queryClient = new QueryClient({
    defaultOptions: {
      queries: {
        retry: false,
        gcTime: Infinity,
      },
    },
  });
  const Wrapper = ({ children }: { children: React.ReactNode }) => (
    <QueryClientProvider client={queryClient}>{children}</QueryClientProvider>
  );
  return Wrapper;
}

const MOCK_USER_ID = "user-123";

describe("useEffectiveRoleOnProject", () => {
  beforeEach(() => {
    mockFetch.mockReset();
    mockUseSession.mockReset();
    mockUseSession.mockReturnValue({
      data: { user: { id: MOCK_USER_ID } },
      status: "authenticated",
    });
  });

  afterEach(() => {
    vi.clearAllMocks();
  });

  it("(a) returns { roleId: null, isLoading: false } when projectId is undefined and never fires the fetch", async () => {
    const wrapper = createWrapper();
    const { result } = renderHook(() => useEffectiveRoleOnProject(), {
      wrapper,
    });

    await waitFor(() => expect(result.current.isLoading).toBe(false));

    expect(result.current.roleId).toBeNull();
    expect(mockFetch).not.toHaveBeenCalled();
  });

  it("(b) returns the resolved roleId when the user holds a SPECIFIC_ROLE on the project", async () => {
    mockFetch.mockResolvedValueOnce({
      ok: true,
      json: async () => ({
        hasAccess: true,
        effectiveRole: "QA Engineer",
        effectiveRoleId: 42,
      }),
    } as Response);

    const wrapper = createWrapper();
    const { result } = renderHook(() => useEffectiveRoleOnProject(7), {
      wrapper,
    });

    await waitFor(() => expect(result.current.isLoading).toBe(false));

    expect(result.current.roleId).toBe(42);
    expect(mockFetch).toHaveBeenCalledTimes(1);
    const [url, init] = mockFetch.mock.calls[0];
    expect(url).toBe("/api/get-user-permissions");
    expect(init.method).toBe("POST");
    expect(JSON.parse(init.body)).toEqual({
      userId: MOCK_USER_ID,
      projectId: 7,
    });
  });

  it("(c) returns the resolved roleId when the user inherits GLOBAL_ROLE access (resolver returns the user's global role id)", async () => {
    mockFetch.mockResolvedValueOnce({
      ok: true,
      json: async () => ({
        hasAccess: true,
        effectiveRole: "Test Lead",
        effectiveRoleId: 99,
      }),
    } as Response);

    const wrapper = createWrapper();
    const { result } = renderHook(() => useEffectiveRoleOnProject(11), {
      wrapper,
    });

    await waitFor(() => expect(result.current.isLoading).toBe(false));

    expect(result.current.roleId).toBe(99);
  });

  it("(d) returns roleId null when the user has NO_ACCESS on the project", async () => {
    mockFetch.mockResolvedValueOnce({
      ok: true,
      json: async () => ({
        hasAccess: false,
        effectiveRole: null,
        effectiveRoleId: null,
      }),
    } as Response);

    const wrapper = createWrapper();
    const { result } = renderHook(() => useEffectiveRoleOnProject(13), {
      wrapper,
    });

    await waitFor(() => expect(result.current.isLoading).toBe(false));

    expect(result.current.roleId).toBeNull();
  });

  it("(e) does not fire the fetch when the user is not authenticated yet", async () => {
    mockUseSession.mockReturnValue({ data: null, status: "unauthenticated" });

    const wrapper = createWrapper();
    const { result } = renderHook(() => useEffectiveRoleOnProject(7), {
      wrapper,
    });

    await waitFor(() => expect(result.current.isLoading).toBe(false));

    expect(result.current.roleId).toBeNull();
    expect(mockFetch).not.toHaveBeenCalled();
  });
});
