import { useQuery } from "@tanstack/react-query";
import { useSession } from "next-auth/react";

/**
 * Result shape exposed by useEffectiveRoleOnProject.
 *
 * `roleId` is null when the viewer is unauthenticated, has no project
 * access, or no projectId was supplied. `isLoading` is true only while the
 * underlying fetch is in flight.
 */
export interface UseEffectiveRoleOnProjectResult {
  roleId: number | null;
  isLoading: boolean;
}

/**
 * Resolves the viewing user's effective project role as a numeric id for
 * UI gating predicates that need to compare against, for example,
 * `ReviewRequest.assigneeRoleId`. Reuses the canonical
 * `POST /api/get-user-permissions` resolver so the precedence rules
 * (user-specific permission, group permission, project default) live in
 * exactly one place server-side.
 *
 * Returns `{ roleId: null, isLoading: false }` when:
 *   - no projectId is supplied,
 *   - the viewer is not authenticated,
 *   - the resolver reports no effective role (NO_ACCESS / system admins).
 *
 * Caches for 60 seconds since project role membership is infrequently
 * changed by a tester mid-session.
 *
 * NOTE: This file lives in `testplanit/hooks/` (custom hooks). It MUST NOT
 * move to `testplanit/lib/hooks/` — that directory is regenerated by
 * `pnpm zenstack generate` (see [[feedback_no_custom_files_in_lib_hooks]]).
 */
export function useEffectiveRoleOnProject(
  projectId?: number,
): UseEffectiveRoleOnProjectResult {
  const { data: session } = useSession();
  const userId = session?.user?.id;

  const enabled =
    typeof projectId === "number" && projectId > 0 && !!userId;

  const { data, isLoading } = useQuery<{
    effectiveRoleId: number | null;
  }>({
    queryKey: ["effective-role-on-project", projectId, userId],
    queryFn: async () => {
      const response = await fetch("/api/get-user-permissions", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ userId, projectId }),
      });
      if (!response.ok) {
        throw new Error(
          `Failed to resolve effective role on project: ${response.status}`,
        );
      }
      const result = (await response.json()) as {
        effectiveRoleId?: number | null;
      };
      return { effectiveRoleId: result.effectiveRoleId ?? null };
    },
    enabled,
    staleTime: 60_000,
  });

  if (!enabled) {
    return { roleId: null, isLoading: false };
  }

  return {
    roleId: data?.effectiveRoleId ?? null,
    isLoading,
  };
}
