"use client";

import { useClientQueries } from "@zenstackhq/tanstack-query/react";
import { useQueryClient } from "@tanstack/react-query";
import { useSession } from "next-auth/react";
import { useEffect } from "react";
import { schema } from "~/zenstack/schema";
import { createDeferredEventSource } from "~/hooks/deferredEventSource";
import { useReviewAssigneeRoleIds } from "~/hooks/useReviewAssigneeRoleIds";
import { useReviewFeatureEnabled } from "~/hooks/useReviewFeatureEnabled";

export interface HeaderAlertCounts {
  /** Unread notifications for the current user. */
  notificationCount: number;
  /** PENDING review requests where the viewer is assignee or holds the role. */
  reviewCount: number;
  /** Sum of the two — the number shown on the collapsed-header kebab badge. */
  total: number;
}

/**
 * Live unread-notification + pending-review-inbox counts for the collapsed
 * header kebab badge.
 *
 * NotificationBell and ReviewInboxButton each surface these counts while the
 * header shows its full icon row, but both unmount once the row collapses into
 * the kebab — their menu variants live inside a closed DropdownMenu that Radix
 * does not mount until it is opened. Without this hook the kebab hides every
 * pending item behind a badge-less "⋮" and the user may miss them.
 *
 * Pass `enabled` = "header is compact" so the queries + SSE run only while the
 * kebab owns the counts; the standalone buttons cover the non-compact case, so
 * the two never fetch at once (no duplicate EventSource, no HTTP/1.1 slot
 * waste). A single stream feeds both counts here, mirroring the wake-up wiring
 * in NotificationBell (refetch) and ReviewInboxButton (invalidate cache).
 *
 * NOTE: lives in `testplanit/hooks/` (custom hooks). It MUST NOT move to
 * `testplanit/lib/hooks/` — that directory is regenerated by zenstack generate.
 */
export function useHeaderAlertCounts(enabled: boolean): HeaderAlertCounts {
  const { data: session } = useSession();
  const queryClient = useQueryClient();
  const userId = session?.user?.id;

  // System-level review flag + the roles the viewer can be reached through,
  // mirroring ReviewInboxButton's count gating.
  const { enabled: reviewEnabled } = useReviewFeatureEnabled();
  const roleIds = useReviewAssigneeRoleIds(userId);

  const { data: notificationCount, refetch: refetchNotifications } =
    useClientQueries(schema).notification.useCount(
      {
        where: { userId: userId ?? "", isDeleted: false, isRead: false },
      },
      { enabled: enabled && !!userId }
    );

  const { data: reviewCount } = useClientQueries(schema).reviewRequest.useCount(
    {
      where: {
        status: "PENDING",
        isDeleted: false,
        project: { reviewWorkflowEnabled: true },
        OR: [
          { assigneeUserId: userId ?? "" },
          { assigneeRoleId: { in: roleIds } },
        ],
      },
    },
    { enabled: enabled && !!userId && reviewEnabled === true }
  );

  // One stream feeds both counts: notifications refetch directly, reviews
  // invalidate the whole ReviewRequest cache (see ReviewInboxButton). Runs only
  // while the kebab owns the counts, so it adds no connection when the full
  // icon row (and its own streams) is mounted.
  useEffect(() => {
    if (!enabled || !userId) return;
    if (typeof window === "undefined" || typeof EventSource === "undefined") {
      return;
    }
    const eventSource = createDeferredEventSource("/api/notifications/stream");
    eventSource.onmessage = () => {
      void refetchNotifications();
      void queryClient.invalidateQueries({
        queryKey: ["zenstack", "ReviewRequest"],
      });
    };
    eventSource.onerror = (err) => {
      console.warn("[useHeaderAlertCounts] SSE transport error", err);
    };
    return () => {
      eventSource.close();
    };
  }, [enabled, userId, refetchNotifications, queryClient]);

  const notifications =
    typeof notificationCount === "number" ? notificationCount : 0;
  const reviews = typeof reviewCount === "number" ? reviewCount : 0;

  return {
    notificationCount: notifications,
    reviewCount: reviews,
    total: notifications + reviews,
  };
}
