"use client";

import { useClientQueries } from "@zenstackhq/tanstack-query/react";
import { useMemo } from "react";
import { schema } from "~/zenstack/schema";

export interface IssueFacetOptions {
  /** Distinct values in scope, blanks excluded. */
  values: string[];
  /** At least one issue in scope has no value for this field. */
  hasNone: boolean;
  /** False until the option query has answered — tells "none" from "not yet". */
  settled: boolean;
}

/**
 * Distinct status, priority, and issue type values for the issue list filter
 * dropdowns, scoped by the caller's `scopeWhere` (project relation filter on
 * the project issues page, nothing on the global and admin lists).
 *
 * Values arriving from external trackers vary in casing for what is really
 * one value, so options are de-duplicated case-insensitively and the first
 * spelling seen wins. The matching list filters compare case-insensitively.
 *
 * Blank values are not offered as options; the groupBy's null/empty bucket
 * becomes `hasNone` instead, which the UI renders as an explicit "not set"
 * choice. Issue type in particular is absent far more often than not — it is
 * only written on sync or on create-through-integration.
 *
 * NOTE: lives in `testplanit/hooks/` (custom hooks). It MUST NOT move to
 * `testplanit/lib/hooks/` — that directory is regenerated by zenstack generate.
 */
export function useIssueFilterOptions({
  scopeWhere,
  enabled,
}: {
  scopeWhere?: Record<string, unknown>;
  enabled: boolean;
}): {
  statuses: IssueFacetOptions;
  priorities: IssueFacetOptions;
  issueTypes: IssueFacetOptions;
} {
  const where = useMemo(
    () => ({ isDeleted: false, ...(scopeWhere ?? {}) }),
    [scopeWhere]
  );

  const { data: statusRows, isSuccess: statusSettled } = useClientQueries(
    schema
  ).issue.useGroupBy(
    { by: ["status"], where, orderBy: { status: "asc" } },
    { enabled }
  );

  const { data: priorityRows, isSuccess: prioritySettled } = useClientQueries(
    schema
  ).issue.useGroupBy(
    { by: ["priority"], where, orderBy: { priority: "asc" } },
    { enabled }
  );

  const { data: issueTypeRows, isSuccess: issueTypeSettled } = useClientQueries(
    schema
  ).issue.useGroupBy(
    { by: ["issueTypeName"], where, orderBy: { issueTypeName: "asc" } },
    { enabled }
  );

  const statuses = useMemo(
    () => toFacetOptions(statusRows, (row) => row.status, statusSettled),
    [statusRows, statusSettled]
  );

  const priorities = useMemo(
    () => toFacetOptions(priorityRows, (row) => row.priority, prioritySettled),
    [priorityRows, prioritySettled]
  );

  const issueTypes = useMemo(
    () =>
      toFacetOptions(
        issueTypeRows,
        (row) => row.issueTypeName,
        issueTypeSettled
      ),
    [issueTypeRows, issueTypeSettled]
  );

  return { statuses, priorities, issueTypes };
}

function toFacetOptions<T>(
  rows: T[] | undefined,
  pick: (row: T) => string | null | undefined,
  settled: boolean
): IssueFacetOptions {
  if (!rows) return { values: [], hasNone: false, settled: false };

  const seen = new Map<string, string>();
  let hasNone = false;

  rows.map(pick).forEach((value) => {
    if (!value || value.trim() === "") {
      hasNone = true;
      return;
    }
    const lower = value.toLowerCase();
    if (!seen.has(lower)) seen.set(lower, value);
  });

  return {
    values: Array.from(seen.values()).sort((a, b) =>
      a.toLowerCase().localeCompare(b.toLowerCase())
    ),
    hasNone,
    settled,
  };
}
