"use client";

import { useClientQueries } from "@zenstackhq/tanstack-query/react";
import { useMemo } from "react";
import { schema } from "~/zenstack/schema";

export interface UsePendingReviewCaseIdsResult {
  /**
   * Case ids with a PENDING ReviewRequest. `undefined` means "not resolved
   * yet" — callers MUST hold their query off rather than treat it as the
   * empty set, which would render "In Review" as zero matches.
   */
  caseIds: number[] | undefined;
  isLoading: boolean;
}

/**
 * The project's test cases currently under review — the set behind the
 * repository's "In Review" grouping axis and filter dimension, and the
 * list-wide twin of the per-row PendingReviewBadge.
 *
 * ReviewRequest points at its entity polymorphically (no FK back-relation to
 * RepositoryCases), so "cases in review" is not expressible as a relation
 * filter on the case row. The ids are resolved here instead and compile to an
 * `id: { in: … }` fragment (see filterWhereCompiler's `inReviewCaseIds`).
 * One PENDING request per entity is the app-level invariant, and a project's
 * pending queue is work-in-flight rather than a scan of the repository, so the
 * set stays small enough to travel in the POST body the case list already uses.
 *
 * `enabled` should be the composed review-feature flag
 * (`useReviewFeatureEnabled(projectId).enabled`); when it is false the hook
 * reports the empty set without querying, because the dimension does not exist
 * for that project either.
 *
 * NOTE: This file lives in `testplanit/hooks/` (custom hooks). It MUST NOT
 * move to `testplanit/lib/hooks/` — that directory is regenerated by
 * `pnpm zenstack generate`.
 */
export function usePendingReviewCaseIds(
  projectId: number | undefined,
  enabled: boolean
): UsePendingReviewCaseIdsResult {
  const hasProjectId = typeof projectId === "number" && projectId > 0;
  const queryEnabled = enabled && hasProjectId;

  const { data, isLoading } = useClientQueries(
    schema
  ).reviewRequest.useFindMany(
    {
      where: {
        // Irrelevant while `enabled` is false; a non-zero sentinel keeps the
        // query key stable and makes any regression that fires the query
        // without a real id return nothing rather than match row 0.
        projectId: hasProjectId ? projectId : -1,
        entityType: "CASE",
        status: "PENDING",
        isDeleted: false,
        project: { reviewWorkflowEnabled: true },
      },
      select: { entityId: true },
    } as any,
    { enabled: queryEnabled } as any
  );

  return useMemo(() => {
    if (!queryEnabled) return { caseIds: [], isLoading: false };
    const rows = data as Array<{ entityId: number }> | undefined;
    return {
      caseIds: rows ? [...new Set(rows.map((row) => row.entityId))] : undefined,
      isLoading,
    };
  }, [data, isLoading, queryEnabled]);
}
