"use client";

import { useMemo } from "react";
import { useClientQueries } from "@zenstackhq/tanstack-query/react";
import { schema } from "~/zenstack/schema";

import type { PendingReviewSummary } from "@/components/reviews/PendingReviewBadge";
import { useReviewFeatureEnabled } from "./useReviewFeatureEnabled";

/**
 * PENDING ReviewRequests for a page of visible entities, keyed by entityId —
 * the bulk fetch behind PendingReviewBadge on list rows (one round trip per
 * page render, never per row). Same badge semantics as the runs/sessions list
 * pages: ANY pending review on the entity, not just ones assigned to the
 * viewer.
 *
 * Safe on cross-project surfaces (dashboard, profile assignments): the
 * per-project Review Workflow toggle is applied in the where clause, so rows
 * from projects with the workflow off never produce a badge.
 *
 * NOTE: This file lives in `testplanit/hooks/` (custom hooks). It MUST NOT
 * move to `testplanit/lib/hooks/` — that directory is regenerated by
 * `pnpm zenstack generate`.
 */
export function usePendingReviewsByEntity(
  entityType: "CASE" | "RUN" | "SESSION",
  entityIds: number[]
): Map<number, PendingReviewSummary> {
  const { enabled } = useReviewFeatureEnabled();

  const { data } = useClientQueries(schema).reviewRequest.useFindMany(
    {
      where: {
        entityType,
        entityId: { in: entityIds },
        status: "PENDING",
        isDeleted: false,
        project: { reviewWorkflowEnabled: true },
      },
      select: {
        id: true,
        status: true,
        entityId: true,
        assigneeUserId: true,
        assigneeRoleId: true,
        assigneeUser: { select: { name: true } },
        assigneeRole: { select: { name: true } },
      },
    } as any,
    {
      enabled: enabled === true && entityIds.length > 0,
    } as any
  );

  return useMemo(() => {
    const map = new Map<number, PendingReviewSummary>();
    const rows = data as
      Array<PendingReviewSummary & { entityId: number }> | undefined;
    rows?.forEach((row) => {
      map.set(row.entityId, row);
    });
    return map;
  }, [data]);
}
