"use client";

import { useClientQueries } from "@zenstackhq/tanstack-query/react";
import { schema } from "~/zenstack/schema";

import {
  PENDING_REVIEW_SUMMARY_INCLUDE,
  type PendingReviewSummaryRequest,
} from "~/components/reviews/types";
import { useReviewAssigneeRoleIds } from "./useReviewAssigneeRoleIds";
import { useReviewFeatureEnabled } from "./useReviewFeatureEnabled";

export interface UsePendingReviewRequestsResult {
  /** PENDING requests the viewer is on the hook for, oldest first. */
  requests: PendingReviewSummaryRequest[];
  /** True until the feature flag and the listing have both resolved. */
  isLoading: boolean;
  /** System-level review-feature flag. Undefined while loading. */
  enabled: boolean | undefined;
}

/**
 * PENDING review requests waiting on the current viewer — the same queue the
 * `/reviews` inbox Pending tab shows, exposed as data so other surfaces (the
 * home page's "Your Assignments" card) can render it without duplicating the
 * where-clause.
 *
 * Scope matches `ReviewInboxButton`'s badge count so the header badge and any
 * consuming list never disagree:
 *   - status PENDING, not soft-deleted
 *   - project has the per-project Review Workflow toggle on (stale rows from a
 *     project that toggled the workflow off stay out of the queue)
 *   - the viewer is the direct assignee OR holds the assigned role
 *
 * Sorted oldest-first — the most-overdue request reads at the top, matching
 * the inbox's default Pending sort.
 *
 * `refetchOnWindowFocus` is on (per the inbox's precedent): the app's
 * QueryClient defaults it to false, and a reviewer coming back from another
 * tab should not see a queue that emptied out minutes ago.
 *
 * NOTE: This file lives in `testplanit/hooks/` (custom hooks). It MUST NOT
 * move to `testplanit/lib/hooks/` — that directory is regenerated by
 * `pnpm zenstack generate`.
 */
export function usePendingReviewRequests(
  userId: string | null | undefined
): UsePendingReviewRequestsResult {
  const { enabled, isLoading: featureLoading } = useReviewFeatureEnabled();
  const roleIds = useReviewAssigneeRoleIds(userId);

  const { data, isLoading: rowsLoading } = useClientQueries(
    schema
  ).reviewRequest.useFindMany(
    {
      where: {
        status: "PENDING",
        isDeleted: false,
        project: { reviewWorkflowEnabled: true },
        OR: [
          { assigneeUserId: userId ?? "" },
          { assigneeRoleId: { in: roleIds } },
        ],
      },
      include: PENDING_REVIEW_SUMMARY_INCLUDE,
      orderBy: { createdAt: "asc" },
    },
    {
      enabled: !!userId && enabled === true,
      refetchOnWindowFocus: true,
    } as any
  );

  return {
    requests: (data as PendingReviewSummaryRequest[] | undefined) ?? [],
    // A disabled query never reports isLoading, so the flag fetch has to be
    // folded in explicitly — otherwise consumers read "loaded, nothing here"
    // during the window before the flag resolves.
    isLoading: featureLoading || (enabled === true && rowsLoading),
    enabled,
  };
}
