import { useQuery } from "@tanstack/react-query";
import { useFindUniqueProjects } from "~/lib/hooks";

/**
 * Result shape exposed by useReviewFeatureEnabled.
 *
 * Each flag may be `undefined` while its underlying fetch is in flight.
 * `enabled` becomes a concrete boolean only when both inputs are resolved
 * (or when no projectId was provided, in which case it equals systemEnabled).
 */
export interface UseReviewFeatureEnabledResult {
  /** System-level flag from GET /api/config/review-feature (env-var-backed). */
  systemEnabled: boolean | undefined;
  /** Per-project flag from Projects.reviewWorkflowEnabled. Undefined when no projectId provided. */
  projectEnabled: boolean | undefined;
  /** AND of systemEnabled + projectEnabled (or systemEnabled alone when no projectId). Undefined while loading. */
  enabled: boolean | undefined;
  /** True until both underlying fetches resolve. */
  isLoading: boolean;
}

/**
 * Single source of truth Wave 2/3 review-feature UI consumers ask:
 *   "Is the review feature enabled for this user on this project right now?"
 *
 * Composition (per D-18 / D-19):
 *   - systemEnabled — operator-controlled env var, read server-side via
 *     GET /api/config/review-feature (NOT a NEXT_PUBLIC_ var; see
 *     RESEARCH §Pitfall 2 and the route handler at
 *     `app/api/config/review-feature/route.ts`).
 *   - projectEnabled — `Projects.reviewWorkflowEnabled` read via the
 *     ZenStack-generated `useFindUniqueProjects` hook. Only fetched when a
 *     numeric `projectId` is supplied; otherwise reports `undefined` and
 *     `enabled` collapses to `systemEnabled`.
 *
 * Wave 2 example:
 *   const { enabled } = useReviewFeatureEnabled(projectId);
 *   if (!enabled) return null;
 *   return <RequestReviewButton entityType="CASE" entityId={caseId} />;
 *
 * NOTE: This file lives in `testplanit/hooks/` (custom hooks). It MUST NOT
 * move to `testplanit/lib/hooks/` — that directory is regenerated by
 * `pnpm zenstack generate` (see [[feedback_no_custom_files_in_lib_hooks]]).
 */
export function useReviewFeatureEnabled(
  projectId?: number,
): UseReviewFeatureEnabledResult {
  // Long staleTime: the env var is operator-controlled and changes are rare;
  // refetching every minute would be wasteful and would make the UI flicker
  // for users without changing the answer.
  const {
    data: systemData,
    isLoading: systemLoading,
  } = useQuery<{ enabled: boolean }>({
    queryKey: ["config", "review-feature"],
    queryFn: async () => {
      const response = await fetch("/api/config/review-feature");
      if (!response.ok) {
        throw new Error(
          `Failed to fetch review-feature config: ${response.status}`,
        );
      }
      return (await response.json()) as { enabled: boolean };
    },
    staleTime: 5 * 60 * 1000,
  });

  // WR-02: `0` is forbidden as a real projectId — guarding here keeps the
  // ZenStack query key stable across consumer call sites that pass no
  // projectId, and prevents a future refactor from accidentally enabling
  // the call with the `id: 0` sentinel (which would silently return null
  // and pin `enabled` to undefined forever via the `projectEnabled ===
  // undefined` branch below). Real project ids are positive integers.
  const hasProjectId = typeof projectId === "number" && projectId > 0;

  // Always call the ZenStack hook (Rules of Hooks); the `enabled` option
  // controls whether it actually fires. The `where.id` value here is
  // irrelevant when `enabled: false` — but we still use a non-zero sentinel
  // so any future regression that flips enabled=true with no real id
  // surfaces as a 404-shaped null rather than a "happens to match row id
  // 0" surprise.
  const PROJECT_ID_SENTINEL = -1;
  const { data: projectData, isLoading: projectLoading } =
    useFindUniqueProjects(
      {
        where: { id: hasProjectId ? projectId : PROJECT_ID_SENTINEL },
        select: { reviewWorkflowEnabled: true },
      },
      { enabled: hasProjectId },
    );

  const systemEnabled = systemData?.enabled;
  const projectEnabled = hasProjectId
    ? (projectData?.reviewWorkflowEnabled as boolean | undefined)
    : undefined;

  // isLoading is true until every fetch that will actually run has resolved.
  const isLoading = systemLoading || (hasProjectId && projectLoading);

  let enabled: boolean | undefined;
  if (systemEnabled === undefined) {
    enabled = undefined;
  } else if (!hasProjectId) {
    enabled = systemEnabled;
  } else if (projectEnabled === undefined) {
    enabled = undefined;
  } else {
    enabled = systemEnabled && projectEnabled;
  }

  return {
    systemEnabled,
    projectEnabled,
    enabled,
    isLoading,
  };
}
