"use client";

import { useQuery } from "@tanstack/react-query";
import type { SessionSummaryData } from "~/app/api/sessions/[sessionId]/summary/route";
import type { TestRunSummaryData } from "~/lib/services/testRunSummary-shared";

/**
 * A run's or session's execution window, derived from its results.
 *
 * NOTE: lives in `testplanit/hooks/` (custom hooks). It MUST NOT move to
 * `testplanit/lib/hooks/` — that directory is regenerated by zenstack generate.
 */
export interface ResultWindow {
  /** Earliest result — the start date. Null until something has been run. */
  startDate: Date | null;
  /**
   * Latest result — the end date. Null while the run/session is open: the
   * newest result on something still in progress is not an ending, and
   * showing it as one would make the range shift under the reader.
   */
  endDate: Date | null;
}

function toWindow(
  firstResultAt: string | null | undefined,
  lastResultAt: string | null | undefined,
  isCompleted: boolean
): ResultWindow {
  return {
    startDate: firstResultAt ? new Date(firstResultAt) : null,
    endDate: isCompleted && lastResultAt ? new Date(lastResultAt) : null,
  };
}

interface TestRunResultWindowOptions {
  testRunId: number;
  isCompleted: boolean;
  /** Summary the caller already has (the runs list batch-fetches them). When
   *  set, no request is made. */
  summary?: TestRunSummaryData;
  /** Pass false while a parent's batch summary fetch is in flight, so rows
   *  don't fan out per-run requests the batch is about to obsolete. */
  enabled?: boolean;
}

/**
 * Execution window for a test run.
 *
 * Shares the `["testRunSummary", id]` query key (and URL) with
 * TestRunCasesSummary, which every surface rendering this hook also renders —
 * so the two read one cache entry and one request, not two.
 */
export function useTestRunResultWindow({
  testRunId,
  isCompleted,
  summary,
  enabled = true,
}: TestRunResultWindowOptions): ResultWindow {
  const { data } = useQuery<TestRunSummaryData>({
    queryKey: ["testRunSummary", testRunId],
    queryFn: async () => {
      const response = await fetch(
        `/api/test-runs/${testRunId}/summary?includeCaseDetails=true`
      );
      if (!response.ok) {
        throw new Error("Failed to fetch test run summary");
      }
      return response.json();
    },
    enabled: enabled && !summary && testRunId > 0,
    staleTime: 30000,
  });

  const effective = summary ?? data;
  return toWindow(
    effective?.firstResultAt,
    effective?.lastResultAt,
    isCompleted
  );
}

interface SessionResultWindowOptions {
  sessionId: number;
  isCompleted: boolean;
  enabled?: boolean;
}

/**
 * Execution window for a session. Shares the `["sessionSummary", id]` query
 * key with SessionResultsSummary the same way the run hook above does.
 */
export function useSessionResultWindow({
  sessionId,
  isCompleted,
  enabled = true,
}: SessionResultWindowOptions): ResultWindow {
  const { data } = useQuery<SessionSummaryData>({
    queryKey: ["sessionSummary", sessionId],
    queryFn: async () => {
      const response = await fetch(`/api/sessions/${sessionId}/summary`);
      if (!response.ok) {
        throw new Error("Failed to fetch session summary");
      }
      return response.json();
    },
    enabled: enabled && sessionId > 0,
    staleTime: 30000,
  });

  return toWindow(data?.firstResultAt, data?.lastResultAt, isCompleted);
}
