import { useQuery } from "@tanstack/react-query";
import { useClientQueries } from "@zenstackhq/tanstack-query/react";
import { schema } from "~/zenstack/schema";

/**
 * Result shape exposed by useReviewFeatureEnabled.
 *
 * Each flag may be `undefined` while its underlying fetch is in flight.
 * `enabled` becomes a concrete boolean only when both inputs are resolved
 * (or when no projectId was provided, in which case it equals systemEnabled).
 */
export interface UseReviewFeatureEnabledResult {
  /** System-level flag from GET /api/config/review-feature (AppConfig-backed). */
  systemEnabled: boolean | undefined;
  /** Per-project flag from Projects.reviewWorkflowEnabled. Undefined when no projectId provided. */
  projectEnabled: boolean | undefined;
  /** AND of systemEnabled + projectEnabled (or systemEnabled alone when no projectId). Undefined while loading. */
  enabled: boolean | undefined;
  /** True until both underlying fetches resolve. */
  isLoading: boolean;
}

/**
 * Single source of truth Wave 2/3 review-feature UI consumers ask:
 *   "Is the review feature enabled for this user on this project right now?"
 *
 * Composition (per D-18 / D-19):
 *   - systemEnabled — admin-toggleable AppConfig row keyed
 *     `review_feature_enabled`, exposed server-side via
 *     GET /api/config/review-feature (so the AppConfig value itself does not
 *     ship to the client bundle and the read is auth-scoped centrally).
 *   - projectEnabled — `Projects.reviewWorkflowEnabled` read via the
 *     ZenStack-generated `useClientQueries(schema).projects.useFindUnique` hook. Only fetched when a
 *     numeric `projectId` is supplied; otherwise reports `undefined` and
 *     `enabled` collapses to `systemEnabled`.
 *
 * Wave 2 example:
 *   const { enabled } = useReviewFeatureEnabled(projectId);
 *   if (!enabled) return null;
 *   return <RequestReviewButton entityType="CASE" entityId={caseId} />;
 *
 * NOTE: This file lives in `testplanit/hooks/` (custom hooks). It MUST NOT
 * move to `testplanit/lib/hooks/` — that directory is regenerated by
 * `pnpm zenstack generate` (see [[feedback_no_custom_files_in_lib_hooks]]).
 */
export function useReviewFeatureEnabled(
  projectId?: number
): UseReviewFeatureEnabledResult {
  // Shorter staleTime than the prior env-var implementation: the AppConfig
  // row is admin-toggleable from the Workflows admin page, and an admin
  // flipping it should propagate to other tabs and users within ~30s. The
  // SystemFeatureCard mutation invalidates this query key on success for
  // immediate reflection in the same tab.
  const { data: systemData, isLoading: systemLoading } = useQuery<{
    enabled: boolean;
  }>({
    queryKey: ["config", "review-feature"],
    queryFn: async () => {
      const response = await fetch("/api/config/review-feature");
      if (!response.ok) {
        throw new Error(
          `Failed to fetch review-feature config: ${response.status}`
        );
      }
      return (await response.json()) as { enabled: boolean };
    },
    staleTime: 30 * 1000,
  });

  // WR-02: `0` is forbidden as a real projectId — guarding here keeps the
  // ZenStack query key stable across consumer call sites that pass no
  // projectId, and prevents a future refactor from accidentally enabling
  // the call with the `id: 0` sentinel (which would silently return null
  // and pin `enabled` to undefined forever via the `projectEnabled ===
  // undefined` branch below). Real project ids are positive integers.
  const hasProjectId = typeof projectId === "number" && projectId > 0;

  // Always call the ZenStack hook (Rules of Hooks); the `enabled` option
  // controls whether it actually fires. The `where.id` value here is
  // irrelevant when `enabled: false` — but we still use a non-zero sentinel
  // so any future regression that flips enabled=true with no real id
  // surfaces as a 404-shaped null rather than a "happens to match row id
  // 0" surprise.
  const PROJECT_ID_SENTINEL = -1;
  const { data: projectData, isLoading: projectLoading } =
    useClientQueries(schema).projects.useFindUnique(
      {
        where: { id: hasProjectId ? projectId : PROJECT_ID_SENTINEL },
        select: { reviewWorkflowEnabled: true },
      },
      { enabled: hasProjectId }
    );

  const systemEnabled = systemData?.enabled;
  const projectEnabled = hasProjectId
    ? (projectData?.reviewWorkflowEnabled as boolean | undefined)
    : undefined;

  // isLoading is true until every fetch that will actually run has resolved.
  const isLoading = systemLoading || (hasProjectId && projectLoading);

  let enabled: boolean | undefined;
  if (systemEnabled === undefined) {
    enabled = undefined;
  } else if (!hasProjectId) {
    enabled = systemEnabled;
  } else if (projectEnabled === undefined) {
    enabled = undefined;
  } else {
    enabled = systemEnabled && projectEnabled;
  }

  return {
    systemEnabled,
    projectEnabled,
    enabled,
    isLoading,
  };
}
