"use client";

import { useClientQueries } from "@zenstackhq/tanstack-query/react";
import { useMemo } from "react";
import { schema } from "~/zenstack/schema";

/**
 * Role IDs a user can be reached through as a review assignee.
 *
 * A ReviewRequest is either assigned to a user directly (`assigneeUserId`) or
 * to a role (`assigneeRoleId`). Resolving the role branch means flattening
 * every role the viewer holds:
 *
 *   - their global `User.roleId`, and
 *   - the `roleId` of every SPECIFIC_ROLE `UserProjectPermission` row.
 *
 * Deduped via Set; null/undefined entries dropped. Returns `[]` while the
 * lookup is in flight or when no user id is supplied, which narrows the
 * consuming query to the direct-assignee branch until the roles land.
 *
 * NOTE: This file lives in `testplanit/hooks/` (custom hooks). It MUST NOT
 * move to `testplanit/lib/hooks/` — that directory is regenerated by
 * `pnpm zenstack generate`.
 */
export function useReviewAssigneeRoleIds(
  userId: string | null | undefined
): number[] {
  const { data: userWithRoles } = useClientQueries(schema).user.useFindUnique(
    {
      where: { id: userId ?? "" },
      select: {
        roleId: true,
        projectPermissions: {
          select: {
            roleId: true,
            accessType: true,
          },
        },
      },
    },
    { enabled: !!userId }
  );

  return useMemo(() => {
    if (!userWithRoles) return [];
    const ids = new Set<number>();
    const globalRoleId = (userWithRoles as { roleId?: number | null }).roleId;
    if (typeof globalRoleId === "number") ids.add(globalRoleId);
    const projectPerms =
      (
        userWithRoles as {
          projectPermissions?: Array<{
            roleId: number | null;
            accessType: string;
          }>;
        }
      ).projectPermissions ?? [];
    for (const perm of projectPerms) {
      if (
        perm.accessType === "SPECIFIC_ROLE" &&
        typeof perm.roleId === "number"
      ) {
        ids.add(perm.roleId);
      }
    }
    return Array.from(ids);
  }, [userWithRoles]);
}
