import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { renderHook, waitFor } from "@testing-library/react";
import React from "react";
import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";

import { useReviewFeatureEnabled } from "./useReviewFeatureEnabled";

/**
 * Tests for useReviewFeatureEnabled — the single source of truth that Wave 2/3
 * UI consumers ask "is the review feature enabled for this user on this
 * project right now?".
 *
 * Composition (per D-18 / D-19):
 *   - systemEnabled = GET /api/config/review-feature → { enabled }
 *   - projectEnabled = useFindUniqueProjects(...).reviewWorkflowEnabled when
 *     projectId is provided
 *   - enabled = AND of both (or systemEnabled alone when no projectId)
 *
 * NOTE: The hook lives in `testplanit/hooks/` (custom hooks). NEVER under
 * `lib/hooks/` — that path is regenerated by ZenStack
 * (see [[feedback_no_custom_files_in_lib_hooks]]).
 */

// Mock the ZenStack-generated hook for project read.
const mockUseFindUniqueProjects = vi.fn();
vi.mock("@zenstackhq/tanstack-query/react", () => ({
  useClientQueries: () => ({
    projects: {
      useFindUnique: (...args: unknown[]) => mockUseFindUniqueProjects(...args),
    },
  }),
}));

// Stub global fetch so the GET /api/config/review-feature call is controllable.
const mockFetch = vi.fn();
vi.stubGlobal("fetch", mockFetch);

function createWrapper() {
  const queryClient = new QueryClient({
    defaultOptions: {
      queries: {
        retry: false,
        gcTime: Infinity,
      },
    },
  });
  const Wrapper = ({ children }: { children: React.ReactNode }) => (
    <QueryClientProvider client={queryClient}>{children}</QueryClientProvider>
  );
  return Wrapper;
}

function mockSystemEnabled(enabled: boolean) {
  mockFetch.mockResolvedValueOnce({
    ok: true,
    json: async () => ({ enabled }),
  } as Response);
}

function mockProjectQuery(
  result:
    | { data: { reviewWorkflowEnabled: boolean }; isLoading: boolean }
    | { data: undefined; isLoading: boolean }
) {
  mockUseFindUniqueProjects.mockReturnValue(result);
}

describe("useReviewFeatureEnabled", () => {
  beforeEach(() => {
    mockFetch.mockReset();
    mockUseFindUniqueProjects.mockReset();
    // Default project query: not called (no projectId)
    mockUseFindUniqueProjects.mockReturnValue({
      data: undefined,
      isLoading: false,
    });
  });

  afterEach(() => {
    vi.clearAllMocks();
  });

  describe("without projectId", () => {
    it("(a) returns systemEnabled true → enabled true when no projectId is provided", async () => {
      mockSystemEnabled(true);

      const wrapper = createWrapper();
      const { result } = renderHook(() => useReviewFeatureEnabled(), {
        wrapper,
      });

      await waitFor(() => expect(result.current.isLoading).toBe(false));

      expect(result.current.systemEnabled).toBe(true);
      expect(result.current.projectEnabled).toBeUndefined();
      expect(result.current.enabled).toBe(true);
    });

    it("(b) returns systemEnabled false → enabled false when no projectId is provided", async () => {
      mockSystemEnabled(false);

      const wrapper = createWrapper();
      const { result } = renderHook(() => useReviewFeatureEnabled(), {
        wrapper,
      });

      await waitFor(() => expect(result.current.isLoading).toBe(false));

      expect(result.current.systemEnabled).toBe(false);
      expect(result.current.projectEnabled).toBeUndefined();
      expect(result.current.enabled).toBe(false);
    });
  });

  describe("with projectId", () => {
    it("(c) returns enabled true when system enabled AND project enabled", async () => {
      mockSystemEnabled(true);
      mockProjectQuery({
        data: { reviewWorkflowEnabled: true },
        isLoading: false,
      });

      const wrapper = createWrapper();
      const { result } = renderHook(() => useReviewFeatureEnabled(42), {
        wrapper,
      });

      await waitFor(() => expect(result.current.isLoading).toBe(false));

      expect(result.current.systemEnabled).toBe(true);
      expect(result.current.projectEnabled).toBe(true);
      expect(result.current.enabled).toBe(true);
    });

    it("(d) returns enabled false when system enabled but project disabled", async () => {
      mockSystemEnabled(true);
      mockProjectQuery({
        data: { reviewWorkflowEnabled: false },
        isLoading: false,
      });

      const wrapper = createWrapper();
      const { result } = renderHook(() => useReviewFeatureEnabled(42), {
        wrapper,
      });

      await waitFor(() => expect(result.current.isLoading).toBe(false));

      expect(result.current.systemEnabled).toBe(true);
      expect(result.current.projectEnabled).toBe(false);
      expect(result.current.enabled).toBe(false);
    });

    it("(e) returns enabled false when system disabled even if project enabled", async () => {
      mockSystemEnabled(false);
      mockProjectQuery({
        data: { reviewWorkflowEnabled: true },
        isLoading: false,
      });

      const wrapper = createWrapper();
      const { result } = renderHook(() => useReviewFeatureEnabled(42), {
        wrapper,
      });

      await waitFor(() => expect(result.current.isLoading).toBe(false));

      expect(result.current.systemEnabled).toBe(false);
      expect(result.current.projectEnabled).toBe(true);
      expect(result.current.enabled).toBe(false);
    });

    it("calls useFindUniqueProjects with the project id and a select for reviewWorkflowEnabled", async () => {
      mockSystemEnabled(true);
      mockProjectQuery({
        data: { reviewWorkflowEnabled: true },
        isLoading: false,
      });

      const wrapper = createWrapper();
      renderHook(() => useReviewFeatureEnabled(7), { wrapper });

      // The ZenStack hook should be called immediately (the enabled flag
      // controls whether it actually fires, but we still call it on every render).
      expect(mockUseFindUniqueProjects).toHaveBeenCalled();
      const [args, opts] = mockUseFindUniqueProjects.mock.calls[0];
      expect(args).toEqual({
        where: { id: 7 },
        select: { reviewWorkflowEnabled: true },
      });
      expect(opts).toEqual(expect.objectContaining({ enabled: true }));
    });

    it("passes { enabled: false } to useFindUniqueProjects when projectId is undefined", async () => {
      mockSystemEnabled(true);

      const wrapper = createWrapper();
      renderHook(() => useReviewFeatureEnabled(), { wrapper });

      expect(mockUseFindUniqueProjects).toHaveBeenCalled();
      const opts = mockUseFindUniqueProjects.mock.calls[0][1];
      expect(opts).toEqual(expect.objectContaining({ enabled: false }));
    });
  });

  describe("loading state", () => {
    it("(f) reports isLoading true while the system fetch is in flight", async () => {
      // Never-resolving fetch promise to keep the query pending.
      // Box the resolver so TypeScript doesn't narrow `let` to `never` inside
      // the executor closure.
      const resolverBox: { resolve?: (value: Response) => void } = {};
      mockFetch.mockReturnValueOnce(
        new Promise<Response>((resolve) => {
          resolverBox.resolve = resolve;
        })
      );

      const wrapper = createWrapper();
      const { result } = renderHook(() => useReviewFeatureEnabled(), {
        wrapper,
      });

      // Initial render: query is firing, hook is loading.
      await waitFor(() => expect(result.current.isLoading).toBe(true));
      expect(result.current.systemEnabled).toBeUndefined();
      expect(result.current.enabled).toBeUndefined();

      // Clean up so the test runner can teardown.
      resolverBox.resolve?.({
        ok: true,
        json: async () => ({ enabled: true }),
      } as Response);
    });

    it("reports isLoading true while the project query is loading", async () => {
      mockSystemEnabled(true);
      mockProjectQuery({ data: undefined, isLoading: true });

      const wrapper = createWrapper();
      const { result } = renderHook(() => useReviewFeatureEnabled(42), {
        wrapper,
      });

      // The system fetch resolves; the project query stays loading.
      await waitFor(() => expect(result.current.systemEnabled).toBe(true));
      expect(result.current.isLoading).toBe(true);
      expect(result.current.projectEnabled).toBeUndefined();
      expect(result.current.enabled).toBeUndefined();
    });
  });

  describe("hook location invariant", () => {
    it("is exported from testplanit/hooks/ (NOT lib/hooks/) — failure here would mean the file moved into ZenStack's regen path", () => {
      // The import at the top of this file is `./useReviewFeatureEnabled`,
      // and this file lives at `testplanit/hooks/useReviewFeatureEnabled.test.tsx`.
      // Vitest module resolution would fail before this test ran if the file
      // moved to `lib/hooks/`. This assertion is the explicit guard.
      expect(typeof useReviewFeatureEnabled).toBe("function");
    });
  });
});
