"use client";

import { useQuery } from "@tanstack/react-query";
import { useCallback } from "react";
import { ACTIVE_EXECUTION_STATUSES } from "~/lib/execution/types";

/**
 * Dispatch history for a run, from the executions route (the ExecutionTarget
 * row is admin-only through the RPC, so the route joins the target name for
 * everyone who can read the run).
 *
 * While an execution is in flight the query polls every few seconds as a
 * fallback for the live stream, so the chip moves from Pending to Dispatched
 * even when no SSE connection is open.
 *
 * Lives in `testplanit/hooks/` (custom hooks) — never `lib/hooks/`, which is
 * regenerated by zenstack generate.
 */

export interface TestRunExecutionRow {
  id: number;
  status: string;
  provider: string;
  ref: string | null;
  externalRunId: string | null;
  externalUrl: string | null;
  externalStatus: string | null;
  error: string | null;
  selectionCount: number;
  requestedCaseIds: unknown;
  dispatchedAt: string | null;
  resultsReceivedAt: string | null;
  completedAt: string | null;
  createdAt: string;
  target: {
    id: number;
    name: string;
    provider: string;
    timeoutMinutes?: number;
  } | null;
  requestedBy: { id: string; name: string | null; email: string | null } | null;
}

export const testRunExecutionsQueryKey = (runId: number) => [
  "testRunExecutions",
  runId,
];

const ACTIVE_POLL_INTERVAL_MS = 5_000;

function isActiveExecution(row: TestRunExecutionRow | undefined): boolean {
  return Boolean(
    row && ACTIVE_EXECUTION_STATUSES.includes(row.status as never)
  );
}

export function useTestRunExecutions(
  runId: number | null,
  options: { enabled?: boolean } = {}
) {
  const query = useQuery({
    queryKey: testRunExecutionsQueryKey(runId ?? 0),
    queryFn: async (): Promise<TestRunExecutionRow[]> => {
      const res = await fetch(`/api/test-runs/${runId}/executions?limit=25`);
      if (!res.ok) throw new Error(`HTTP ${res.status}`);
      const data = (await res.json()) as { executions: TestRunExecutionRow[] };
      return data.executions;
    },
    enabled: (options.enabled ?? true) && runId != null && runId > 0,
    staleTime: 10_000,
    refetchOnWindowFocus: true,
    refetchInterval: (q) =>
      isActiveExecution(q.state.data?.[0]) ? ACTIVE_POLL_INTERVAL_MS : false,
  });

  const executions = query.data ?? [];
  const latest = executions[0] ?? null;
  const active = latest && isActiveExecution(latest) ? latest : null;

  const refetch = useCallback(() => void query.refetch(), [query]);

  return {
    executions,
    latest,
    active,
    isLoading: query.isLoading,
    refetch,
  };
}
