/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */

import type { Prisma, CaseSharedDataSetAssignment } from "@prisma/client";
import type { UseMutationOptions, UseQueryOptions, UseInfiniteQueryOptions, InfiniteData } from '@tanstack/react-query';
import { getHooksContext } from '@zenstackhq/tanstack-query/runtime-v5/react';
import { useModelQuery, useInfiniteModelQuery, useModelMutation } from '@zenstackhq/tanstack-query/runtime-v5/react';
import type { PickEnumerable, CheckSelect, QueryError, ExtraQueryOptions, ExtraMutationOptions } from '@zenstackhq/tanstack-query/runtime-v5';
import type { PolicyCrudKind } from '@zenstackhq/runtime'
import metadata from './__model_meta';
type DefaultError = QueryError;
import { useSuspenseModelQuery, useSuspenseInfiniteModelQuery } from '@zenstackhq/tanstack-query/runtime-v5/react';
import type { UseSuspenseQueryOptions, UseSuspenseInfiniteQueryOptions } from '@tanstack/react-query';

export function useCreateCaseSharedDataSetAssignment(options?: Omit<(UseMutationOptions<(CaseSharedDataSetAssignment | undefined), DefaultError, Prisma.CaseSharedDataSetAssignmentCreateArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.CaseSharedDataSetAssignmentCreateArgs, DefaultError, CaseSharedDataSetAssignment, true>('CaseSharedDataSetAssignment', 'POST', `${endpoint}/caseSharedDataSetAssignment/create`, metadata, options, fetch, true)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.CaseSharedDataSetAssignmentCreateArgs>(
            args: Prisma.SelectSubset<T, Prisma.CaseSharedDataSetAssignmentCreateArgs>,
            options?: Omit<(UseMutationOptions<(CheckSelect<T, CaseSharedDataSetAssignment, Prisma.CaseSharedDataSetAssignmentGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.CaseSharedDataSetAssignmentCreateArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as (CheckSelect<T, CaseSharedDataSetAssignment, Prisma.CaseSharedDataSetAssignmentGetPayload<T>> | undefined);
        },
    };
    return mutation;
}

export function useCreateManyCaseSharedDataSetAssignment(options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.CaseSharedDataSetAssignmentCreateManyArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.CaseSharedDataSetAssignmentCreateManyArgs, DefaultError, Prisma.BatchPayload, false>('CaseSharedDataSetAssignment', 'POST', `${endpoint}/caseSharedDataSetAssignment/createMany`, metadata, options, fetch, false)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.CaseSharedDataSetAssignmentCreateManyArgs>(
            args: Prisma.SelectSubset<T, Prisma.CaseSharedDataSetAssignmentCreateManyArgs>,
            options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.SelectSubset<T, Prisma.CaseSharedDataSetAssignmentCreateManyArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as Prisma.BatchPayload;
        },
    };
    return mutation;
}

export function useFindManyCaseSharedDataSetAssignment<TArgs extends Prisma.CaseSharedDataSetAssignmentFindManyArgs, TQueryFnData = Array<Prisma.CaseSharedDataSetAssignmentGetPayload<TArgs> & { $optimistic?: boolean }>, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.CaseSharedDataSetAssignmentFindManyArgs>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('CaseSharedDataSetAssignment', `${endpoint}/caseSharedDataSetAssignment/findMany`, args, options, fetch);
}

export function useInfiniteFindManyCaseSharedDataSetAssignment<TArgs extends Prisma.CaseSharedDataSetAssignmentFindManyArgs, TQueryFnData = Array<Prisma.CaseSharedDataSetAssignmentGetPayload<TArgs>>, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.CaseSharedDataSetAssignmentFindManyArgs>, options?: Omit<UseInfiniteQueryOptions<TQueryFnData, TError, InfiniteData<TData>>, 'queryKey' | 'initialPageParam'>) {
    options = options ?? { getNextPageParam: () => null };
    const { endpoint, fetch } = getHooksContext();
    return useInfiniteModelQuery<TQueryFnData, TData, TError>('CaseSharedDataSetAssignment', `${endpoint}/caseSharedDataSetAssignment/findMany`, args, options, fetch);
}

export function useSuspenseFindManyCaseSharedDataSetAssignment<TArgs extends Prisma.CaseSharedDataSetAssignmentFindManyArgs, TQueryFnData = Array<Prisma.CaseSharedDataSetAssignmentGetPayload<TArgs> & { $optimistic?: boolean }>, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.CaseSharedDataSetAssignmentFindManyArgs>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('CaseSharedDataSetAssignment', `${endpoint}/caseSharedDataSetAssignment/findMany`, args, options, fetch);
}

export function useSuspenseInfiniteFindManyCaseSharedDataSetAssignment<TArgs extends Prisma.CaseSharedDataSetAssignmentFindManyArgs, TQueryFnData = Array<Prisma.CaseSharedDataSetAssignmentGetPayload<TArgs>>, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.CaseSharedDataSetAssignmentFindManyArgs>, options?: Omit<UseSuspenseInfiniteQueryOptions<TQueryFnData, TError, InfiniteData<TData>>, 'queryKey' | 'initialPageParam'>) {
    options = options ?? { getNextPageParam: () => null };
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseInfiniteModelQuery<TQueryFnData, TData, TError>('CaseSharedDataSetAssignment', `${endpoint}/caseSharedDataSetAssignment/findMany`, args, options, fetch);
}

export function useFindUniqueCaseSharedDataSetAssignment<TArgs extends Prisma.CaseSharedDataSetAssignmentFindUniqueArgs, TQueryFnData = Prisma.CaseSharedDataSetAssignmentGetPayload<TArgs> & { $optimistic?: boolean }, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.CaseSharedDataSetAssignmentFindUniqueArgs>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('CaseSharedDataSetAssignment', `${endpoint}/caseSharedDataSetAssignment/findUnique`, args, options, fetch);
}

export function useSuspenseFindUniqueCaseSharedDataSetAssignment<TArgs extends Prisma.CaseSharedDataSetAssignmentFindUniqueArgs, TQueryFnData = Prisma.CaseSharedDataSetAssignmentGetPayload<TArgs> & { $optimistic?: boolean }, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.CaseSharedDataSetAssignmentFindUniqueArgs>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('CaseSharedDataSetAssignment', `${endpoint}/caseSharedDataSetAssignment/findUnique`, args, options, fetch);
}

export function useFindFirstCaseSharedDataSetAssignment<TArgs extends Prisma.CaseSharedDataSetAssignmentFindFirstArgs, TQueryFnData = Prisma.CaseSharedDataSetAssignmentGetPayload<TArgs> & { $optimistic?: boolean }, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.CaseSharedDataSetAssignmentFindFirstArgs>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('CaseSharedDataSetAssignment', `${endpoint}/caseSharedDataSetAssignment/findFirst`, args, options, fetch);
}

export function useSuspenseFindFirstCaseSharedDataSetAssignment<TArgs extends Prisma.CaseSharedDataSetAssignmentFindFirstArgs, TQueryFnData = Prisma.CaseSharedDataSetAssignmentGetPayload<TArgs> & { $optimistic?: boolean }, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.CaseSharedDataSetAssignmentFindFirstArgs>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('CaseSharedDataSetAssignment', `${endpoint}/caseSharedDataSetAssignment/findFirst`, args, options, fetch);
}

export function useUpdateCaseSharedDataSetAssignment(options?: Omit<(UseMutationOptions<(CaseSharedDataSetAssignment | undefined), DefaultError, Prisma.CaseSharedDataSetAssignmentUpdateArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.CaseSharedDataSetAssignmentUpdateArgs, DefaultError, CaseSharedDataSetAssignment, true>('CaseSharedDataSetAssignment', 'PUT', `${endpoint}/caseSharedDataSetAssignment/update`, metadata, options, fetch, true)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.CaseSharedDataSetAssignmentUpdateArgs>(
            args: Prisma.SelectSubset<T, Prisma.CaseSharedDataSetAssignmentUpdateArgs>,
            options?: Omit<(UseMutationOptions<(CheckSelect<T, CaseSharedDataSetAssignment, Prisma.CaseSharedDataSetAssignmentGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.CaseSharedDataSetAssignmentUpdateArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as (CheckSelect<T, CaseSharedDataSetAssignment, Prisma.CaseSharedDataSetAssignmentGetPayload<T>> | undefined);
        },
    };
    return mutation;
}

export function useUpdateManyCaseSharedDataSetAssignment(options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.CaseSharedDataSetAssignmentUpdateManyArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.CaseSharedDataSetAssignmentUpdateManyArgs, DefaultError, Prisma.BatchPayload, false>('CaseSharedDataSetAssignment', 'PUT', `${endpoint}/caseSharedDataSetAssignment/updateMany`, metadata, options, fetch, false)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.CaseSharedDataSetAssignmentUpdateManyArgs>(
            args: Prisma.SelectSubset<T, Prisma.CaseSharedDataSetAssignmentUpdateManyArgs>,
            options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.SelectSubset<T, Prisma.CaseSharedDataSetAssignmentUpdateManyArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as Prisma.BatchPayload;
        },
    };
    return mutation;
}

export function useUpsertCaseSharedDataSetAssignment(options?: Omit<(UseMutationOptions<(CaseSharedDataSetAssignment | undefined), DefaultError, Prisma.CaseSharedDataSetAssignmentUpsertArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.CaseSharedDataSetAssignmentUpsertArgs, DefaultError, CaseSharedDataSetAssignment, true>('CaseSharedDataSetAssignment', 'POST', `${endpoint}/caseSharedDataSetAssignment/upsert`, metadata, options, fetch, true)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.CaseSharedDataSetAssignmentUpsertArgs>(
            args: Prisma.SelectSubset<T, Prisma.CaseSharedDataSetAssignmentUpsertArgs>,
            options?: Omit<(UseMutationOptions<(CheckSelect<T, CaseSharedDataSetAssignment, Prisma.CaseSharedDataSetAssignmentGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.CaseSharedDataSetAssignmentUpsertArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as (CheckSelect<T, CaseSharedDataSetAssignment, Prisma.CaseSharedDataSetAssignmentGetPayload<T>> | undefined);
        },
    };
    return mutation;
}

export function useDeleteCaseSharedDataSetAssignment(options?: Omit<(UseMutationOptions<(CaseSharedDataSetAssignment | undefined), DefaultError, Prisma.CaseSharedDataSetAssignmentDeleteArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.CaseSharedDataSetAssignmentDeleteArgs, DefaultError, CaseSharedDataSetAssignment, true>('CaseSharedDataSetAssignment', 'DELETE', `${endpoint}/caseSharedDataSetAssignment/delete`, metadata, options, fetch, true)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.CaseSharedDataSetAssignmentDeleteArgs>(
            args: Prisma.SelectSubset<T, Prisma.CaseSharedDataSetAssignmentDeleteArgs>,
            options?: Omit<(UseMutationOptions<(CheckSelect<T, CaseSharedDataSetAssignment, Prisma.CaseSharedDataSetAssignmentGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.CaseSharedDataSetAssignmentDeleteArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as (CheckSelect<T, CaseSharedDataSetAssignment, Prisma.CaseSharedDataSetAssignmentGetPayload<T>> | undefined);
        },
    };
    return mutation;
}

export function useDeleteManyCaseSharedDataSetAssignment(options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.CaseSharedDataSetAssignmentDeleteManyArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.CaseSharedDataSetAssignmentDeleteManyArgs, DefaultError, Prisma.BatchPayload, false>('CaseSharedDataSetAssignment', 'DELETE', `${endpoint}/caseSharedDataSetAssignment/deleteMany`, metadata, options, fetch, false)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.CaseSharedDataSetAssignmentDeleteManyArgs>(
            args: Prisma.SelectSubset<T, Prisma.CaseSharedDataSetAssignmentDeleteManyArgs>,
            options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.SelectSubset<T, Prisma.CaseSharedDataSetAssignmentDeleteManyArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as Prisma.BatchPayload;
        },
    };
    return mutation;
}

export function useAggregateCaseSharedDataSetAssignment<TArgs extends Prisma.CaseSharedDataSetAssignmentAggregateArgs, TQueryFnData = Prisma.GetCaseSharedDataSetAssignmentAggregateType<TArgs>, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.CaseSharedDataSetAssignmentAggregateArgs>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('CaseSharedDataSetAssignment', `${endpoint}/caseSharedDataSetAssignment/aggregate`, args, options, fetch);
}

export function useSuspenseAggregateCaseSharedDataSetAssignment<TArgs extends Prisma.CaseSharedDataSetAssignmentAggregateArgs, TQueryFnData = Prisma.GetCaseSharedDataSetAssignmentAggregateType<TArgs>, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.CaseSharedDataSetAssignmentAggregateArgs>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('CaseSharedDataSetAssignment', `${endpoint}/caseSharedDataSetAssignment/aggregate`, args, options, fetch);
}

export function useGroupByCaseSharedDataSetAssignment<TArgs extends Prisma.CaseSharedDataSetAssignmentGroupByArgs, HasSelectOrTake extends Prisma.Or<Prisma.Extends<'skip', Prisma.Keys<TArgs>>, Prisma.Extends<'take', Prisma.Keys<TArgs>>>, OrderByArg extends Prisma.True extends HasSelectOrTake ? { orderBy: Prisma.CaseSharedDataSetAssignmentGroupByArgs['orderBy'] } : { orderBy?: Prisma.CaseSharedDataSetAssignmentGroupByArgs['orderBy'] }, OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<TArgs['orderBy']>>>, ByFields extends Prisma.MaybeTupleToUnion<TArgs['by']>, ByValid extends Prisma.Has<ByFields, OrderFields>, HavingFields extends Prisma.GetHavingFields<TArgs['having']>, HavingValid extends Prisma.Has<ByFields, HavingFields>, ByEmpty extends TArgs['by'] extends never[] ? Prisma.True : Prisma.False, InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
        ? never
        : P extends string
        ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
        : [
            Error,
            'Field ',
            P,
            ` in "having" needs to be provided in "by"`,
        ]
    }[HavingFields]
    : 'take' extends Prisma.Keys<TArgs>
    ? 'orderBy' extends Prisma.Keys<TArgs>
    ? ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields]
    : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<TArgs>
    ? 'orderBy' extends Prisma.Keys<TArgs>
    ? ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields]
    : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields], TQueryFnData = {} extends InputErrors ?
    Array<PickEnumerable<Prisma.CaseSharedDataSetAssignmentGroupByOutputType, TArgs['by']> &
    {
        [P in ((keyof TArgs) & (keyof Prisma.CaseSharedDataSetAssignmentGroupByOutputType))]: P extends '_count'
        ? TArgs[P] extends boolean
        ? number
        : Prisma.GetScalarType<TArgs[P], Prisma.CaseSharedDataSetAssignmentGroupByOutputType[P]>
        : Prisma.GetScalarType<TArgs[P], Prisma.CaseSharedDataSetAssignmentGroupByOutputType[P]>
    }
    > : InputErrors, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.SubsetIntersection<TArgs, Prisma.CaseSharedDataSetAssignmentGroupByArgs, OrderByArg> & InputErrors>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('CaseSharedDataSetAssignment', `${endpoint}/caseSharedDataSetAssignment/groupBy`, args, options, fetch);
}

export function useSuspenseGroupByCaseSharedDataSetAssignment<TArgs extends Prisma.CaseSharedDataSetAssignmentGroupByArgs, HasSelectOrTake extends Prisma.Or<Prisma.Extends<'skip', Prisma.Keys<TArgs>>, Prisma.Extends<'take', Prisma.Keys<TArgs>>>, OrderByArg extends Prisma.True extends HasSelectOrTake ? { orderBy: Prisma.CaseSharedDataSetAssignmentGroupByArgs['orderBy'] } : { orderBy?: Prisma.CaseSharedDataSetAssignmentGroupByArgs['orderBy'] }, OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<TArgs['orderBy']>>>, ByFields extends Prisma.MaybeTupleToUnion<TArgs['by']>, ByValid extends Prisma.Has<ByFields, OrderFields>, HavingFields extends Prisma.GetHavingFields<TArgs['having']>, HavingValid extends Prisma.Has<ByFields, HavingFields>, ByEmpty extends TArgs['by'] extends never[] ? Prisma.True : Prisma.False, InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
        ? never
        : P extends string
        ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
        : [
            Error,
            'Field ',
            P,
            ` in "having" needs to be provided in "by"`,
        ]
    }[HavingFields]
    : 'take' extends Prisma.Keys<TArgs>
    ? 'orderBy' extends Prisma.Keys<TArgs>
    ? ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields]
    : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<TArgs>
    ? 'orderBy' extends Prisma.Keys<TArgs>
    ? ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields]
    : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields], TQueryFnData = {} extends InputErrors ?
    Array<PickEnumerable<Prisma.CaseSharedDataSetAssignmentGroupByOutputType, TArgs['by']> &
    {
        [P in ((keyof TArgs) & (keyof Prisma.CaseSharedDataSetAssignmentGroupByOutputType))]: P extends '_count'
        ? TArgs[P] extends boolean
        ? number
        : Prisma.GetScalarType<TArgs[P], Prisma.CaseSharedDataSetAssignmentGroupByOutputType[P]>
        : Prisma.GetScalarType<TArgs[P], Prisma.CaseSharedDataSetAssignmentGroupByOutputType[P]>
    }
    > : InputErrors, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.SubsetIntersection<TArgs, Prisma.CaseSharedDataSetAssignmentGroupByArgs, OrderByArg> & InputErrors>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('CaseSharedDataSetAssignment', `${endpoint}/caseSharedDataSetAssignment/groupBy`, args, options, fetch);
}

export function useCountCaseSharedDataSetAssignment<TArgs extends Prisma.CaseSharedDataSetAssignmentCountArgs, TQueryFnData = TArgs extends { select: any; } ? TArgs['select'] extends true ? number : Prisma.GetScalarType<TArgs['select'], Prisma.CaseSharedDataSetAssignmentCountAggregateOutputType> : number, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.CaseSharedDataSetAssignmentCountArgs>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('CaseSharedDataSetAssignment', `${endpoint}/caseSharedDataSetAssignment/count`, args, options, fetch);
}

export function useSuspenseCountCaseSharedDataSetAssignment<TArgs extends Prisma.CaseSharedDataSetAssignmentCountArgs, TQueryFnData = TArgs extends { select: any; } ? TArgs['select'] extends true ? number : Prisma.GetScalarType<TArgs['select'], Prisma.CaseSharedDataSetAssignmentCountAggregateOutputType> : number, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.CaseSharedDataSetAssignmentCountArgs>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('CaseSharedDataSetAssignment', `${endpoint}/caseSharedDataSetAssignment/count`, args, options, fetch);
}

export function useCheckCaseSharedDataSetAssignment<TError = DefaultError>(args: { operation: PolicyCrudKind; where?: { id?: number; caseId?: number; sharedDataSetId?: number; pinnedVersionId?: number; createdById?: string }; }, options?: (Omit<UseQueryOptions<boolean, TError, boolean>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<boolean, boolean, TError>('CaseSharedDataSetAssignment', `${endpoint}/caseSharedDataSetAssignment/check`, args, options, fetch);
}
