/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */

import type { Prisma, DataSetRow } from "@prisma/client";
import type { UseMutationOptions, UseQueryOptions, UseInfiniteQueryOptions, InfiniteData } from '@tanstack/react-query';
import { getHooksContext } from '@zenstackhq/tanstack-query/runtime-v5/react';
import { useModelQuery, useInfiniteModelQuery, useModelMutation } from '@zenstackhq/tanstack-query/runtime-v5/react';
import type { PickEnumerable, CheckSelect, QueryError, ExtraQueryOptions, ExtraMutationOptions } from '@zenstackhq/tanstack-query/runtime-v5';
import type { PolicyCrudKind } from '@zenstackhq/runtime'
import metadata from './__model_meta';
type DefaultError = QueryError;
import { useSuspenseModelQuery, useSuspenseInfiniteModelQuery } from '@zenstackhq/tanstack-query/runtime-v5/react';
import type { UseSuspenseQueryOptions, UseSuspenseInfiniteQueryOptions } from '@tanstack/react-query';

export function useCreateDataSetRow(options?: Omit<(UseMutationOptions<(DataSetRow | undefined), DefaultError, Prisma.DataSetRowCreateArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.DataSetRowCreateArgs, DefaultError, DataSetRow, true>('DataSetRow', 'POST', `${endpoint}/dataSetRow/create`, metadata, options, fetch, true)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.DataSetRowCreateArgs>(
            args: Prisma.SelectSubset<T, Prisma.DataSetRowCreateArgs>,
            options?: Omit<(UseMutationOptions<(CheckSelect<T, DataSetRow, Prisma.DataSetRowGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.DataSetRowCreateArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as (CheckSelect<T, DataSetRow, Prisma.DataSetRowGetPayload<T>> | undefined);
        },
    };
    return mutation;
}

export function useCreateManyDataSetRow(options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.DataSetRowCreateManyArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.DataSetRowCreateManyArgs, DefaultError, Prisma.BatchPayload, false>('DataSetRow', 'POST', `${endpoint}/dataSetRow/createMany`, metadata, options, fetch, false)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.DataSetRowCreateManyArgs>(
            args: Prisma.SelectSubset<T, Prisma.DataSetRowCreateManyArgs>,
            options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.SelectSubset<T, Prisma.DataSetRowCreateManyArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as Prisma.BatchPayload;
        },
    };
    return mutation;
}

export function useFindManyDataSetRow<TArgs extends Prisma.DataSetRowFindManyArgs, TQueryFnData = Array<Prisma.DataSetRowGetPayload<TArgs> & { $optimistic?: boolean }>, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.DataSetRowFindManyArgs>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('DataSetRow', `${endpoint}/dataSetRow/findMany`, args, options, fetch);
}

export function useInfiniteFindManyDataSetRow<TArgs extends Prisma.DataSetRowFindManyArgs, TQueryFnData = Array<Prisma.DataSetRowGetPayload<TArgs>>, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.DataSetRowFindManyArgs>, options?: Omit<UseInfiniteQueryOptions<TQueryFnData, TError, InfiniteData<TData>>, 'queryKey' | 'initialPageParam'>) {
    options = options ?? { getNextPageParam: () => null };
    const { endpoint, fetch } = getHooksContext();
    return useInfiniteModelQuery<TQueryFnData, TData, TError>('DataSetRow', `${endpoint}/dataSetRow/findMany`, args, options, fetch);
}

export function useSuspenseFindManyDataSetRow<TArgs extends Prisma.DataSetRowFindManyArgs, TQueryFnData = Array<Prisma.DataSetRowGetPayload<TArgs> & { $optimistic?: boolean }>, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.DataSetRowFindManyArgs>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('DataSetRow', `${endpoint}/dataSetRow/findMany`, args, options, fetch);
}

export function useSuspenseInfiniteFindManyDataSetRow<TArgs extends Prisma.DataSetRowFindManyArgs, TQueryFnData = Array<Prisma.DataSetRowGetPayload<TArgs>>, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.DataSetRowFindManyArgs>, options?: Omit<UseSuspenseInfiniteQueryOptions<TQueryFnData, TError, InfiniteData<TData>>, 'queryKey' | 'initialPageParam'>) {
    options = options ?? { getNextPageParam: () => null };
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseInfiniteModelQuery<TQueryFnData, TData, TError>('DataSetRow', `${endpoint}/dataSetRow/findMany`, args, options, fetch);
}

export function useFindUniqueDataSetRow<TArgs extends Prisma.DataSetRowFindUniqueArgs, TQueryFnData = Prisma.DataSetRowGetPayload<TArgs> & { $optimistic?: boolean }, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.DataSetRowFindUniqueArgs>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('DataSetRow', `${endpoint}/dataSetRow/findUnique`, args, options, fetch);
}

export function useSuspenseFindUniqueDataSetRow<TArgs extends Prisma.DataSetRowFindUniqueArgs, TQueryFnData = Prisma.DataSetRowGetPayload<TArgs> & { $optimistic?: boolean }, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.DataSetRowFindUniqueArgs>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('DataSetRow', `${endpoint}/dataSetRow/findUnique`, args, options, fetch);
}

export function useFindFirstDataSetRow<TArgs extends Prisma.DataSetRowFindFirstArgs, TQueryFnData = Prisma.DataSetRowGetPayload<TArgs> & { $optimistic?: boolean }, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.DataSetRowFindFirstArgs>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('DataSetRow', `${endpoint}/dataSetRow/findFirst`, args, options, fetch);
}

export function useSuspenseFindFirstDataSetRow<TArgs extends Prisma.DataSetRowFindFirstArgs, TQueryFnData = Prisma.DataSetRowGetPayload<TArgs> & { $optimistic?: boolean }, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.DataSetRowFindFirstArgs>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('DataSetRow', `${endpoint}/dataSetRow/findFirst`, args, options, fetch);
}

export function useUpdateDataSetRow(options?: Omit<(UseMutationOptions<(DataSetRow | undefined), DefaultError, Prisma.DataSetRowUpdateArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.DataSetRowUpdateArgs, DefaultError, DataSetRow, true>('DataSetRow', 'PUT', `${endpoint}/dataSetRow/update`, metadata, options, fetch, true)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.DataSetRowUpdateArgs>(
            args: Prisma.SelectSubset<T, Prisma.DataSetRowUpdateArgs>,
            options?: Omit<(UseMutationOptions<(CheckSelect<T, DataSetRow, Prisma.DataSetRowGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.DataSetRowUpdateArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as (CheckSelect<T, DataSetRow, Prisma.DataSetRowGetPayload<T>> | undefined);
        },
    };
    return mutation;
}

export function useUpdateManyDataSetRow(options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.DataSetRowUpdateManyArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.DataSetRowUpdateManyArgs, DefaultError, Prisma.BatchPayload, false>('DataSetRow', 'PUT', `${endpoint}/dataSetRow/updateMany`, metadata, options, fetch, false)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.DataSetRowUpdateManyArgs>(
            args: Prisma.SelectSubset<T, Prisma.DataSetRowUpdateManyArgs>,
            options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.SelectSubset<T, Prisma.DataSetRowUpdateManyArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as Prisma.BatchPayload;
        },
    };
    return mutation;
}

export function useUpsertDataSetRow(options?: Omit<(UseMutationOptions<(DataSetRow | undefined), DefaultError, Prisma.DataSetRowUpsertArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.DataSetRowUpsertArgs, DefaultError, DataSetRow, true>('DataSetRow', 'POST', `${endpoint}/dataSetRow/upsert`, metadata, options, fetch, true)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.DataSetRowUpsertArgs>(
            args: Prisma.SelectSubset<T, Prisma.DataSetRowUpsertArgs>,
            options?: Omit<(UseMutationOptions<(CheckSelect<T, DataSetRow, Prisma.DataSetRowGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.DataSetRowUpsertArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as (CheckSelect<T, DataSetRow, Prisma.DataSetRowGetPayload<T>> | undefined);
        },
    };
    return mutation;
}

export function useDeleteDataSetRow(options?: Omit<(UseMutationOptions<(DataSetRow | undefined), DefaultError, Prisma.DataSetRowDeleteArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.DataSetRowDeleteArgs, DefaultError, DataSetRow, true>('DataSetRow', 'DELETE', `${endpoint}/dataSetRow/delete`, metadata, options, fetch, true)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.DataSetRowDeleteArgs>(
            args: Prisma.SelectSubset<T, Prisma.DataSetRowDeleteArgs>,
            options?: Omit<(UseMutationOptions<(CheckSelect<T, DataSetRow, Prisma.DataSetRowGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.DataSetRowDeleteArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as (CheckSelect<T, DataSetRow, Prisma.DataSetRowGetPayload<T>> | undefined);
        },
    };
    return mutation;
}

export function useDeleteManyDataSetRow(options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.DataSetRowDeleteManyArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.DataSetRowDeleteManyArgs, DefaultError, Prisma.BatchPayload, false>('DataSetRow', 'DELETE', `${endpoint}/dataSetRow/deleteMany`, metadata, options, fetch, false)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.DataSetRowDeleteManyArgs>(
            args: Prisma.SelectSubset<T, Prisma.DataSetRowDeleteManyArgs>,
            options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.SelectSubset<T, Prisma.DataSetRowDeleteManyArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as Prisma.BatchPayload;
        },
    };
    return mutation;
}

export function useAggregateDataSetRow<TArgs extends Prisma.DataSetRowAggregateArgs, TQueryFnData = Prisma.GetDataSetRowAggregateType<TArgs>, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.DataSetRowAggregateArgs>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('DataSetRow', `${endpoint}/dataSetRow/aggregate`, args, options, fetch);
}

export function useSuspenseAggregateDataSetRow<TArgs extends Prisma.DataSetRowAggregateArgs, TQueryFnData = Prisma.GetDataSetRowAggregateType<TArgs>, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.DataSetRowAggregateArgs>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('DataSetRow', `${endpoint}/dataSetRow/aggregate`, args, options, fetch);
}

export function useGroupByDataSetRow<TArgs extends Prisma.DataSetRowGroupByArgs, HasSelectOrTake extends Prisma.Or<Prisma.Extends<'skip', Prisma.Keys<TArgs>>, Prisma.Extends<'take', Prisma.Keys<TArgs>>>, OrderByArg extends Prisma.True extends HasSelectOrTake ? { orderBy: Prisma.DataSetRowGroupByArgs['orderBy'] } : { orderBy?: Prisma.DataSetRowGroupByArgs['orderBy'] }, OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<TArgs['orderBy']>>>, ByFields extends Prisma.MaybeTupleToUnion<TArgs['by']>, ByValid extends Prisma.Has<ByFields, OrderFields>, HavingFields extends Prisma.GetHavingFields<TArgs['having']>, HavingValid extends Prisma.Has<ByFields, HavingFields>, ByEmpty extends TArgs['by'] extends never[] ? Prisma.True : Prisma.False, InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
        ? never
        : P extends string
        ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
        : [
            Error,
            'Field ',
            P,
            ` in "having" needs to be provided in "by"`,
        ]
    }[HavingFields]
    : 'take' extends Prisma.Keys<TArgs>
    ? 'orderBy' extends Prisma.Keys<TArgs>
    ? ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields]
    : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<TArgs>
    ? 'orderBy' extends Prisma.Keys<TArgs>
    ? ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields]
    : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields], TQueryFnData = {} extends InputErrors ?
    Array<PickEnumerable<Prisma.DataSetRowGroupByOutputType, TArgs['by']> &
    {
        [P in ((keyof TArgs) & (keyof Prisma.DataSetRowGroupByOutputType))]: P extends '_count'
        ? TArgs[P] extends boolean
        ? number
        : Prisma.GetScalarType<TArgs[P], Prisma.DataSetRowGroupByOutputType[P]>
        : Prisma.GetScalarType<TArgs[P], Prisma.DataSetRowGroupByOutputType[P]>
    }
    > : InputErrors, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.SubsetIntersection<TArgs, Prisma.DataSetRowGroupByArgs, OrderByArg> & InputErrors>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('DataSetRow', `${endpoint}/dataSetRow/groupBy`, args, options, fetch);
}

export function useSuspenseGroupByDataSetRow<TArgs extends Prisma.DataSetRowGroupByArgs, HasSelectOrTake extends Prisma.Or<Prisma.Extends<'skip', Prisma.Keys<TArgs>>, Prisma.Extends<'take', Prisma.Keys<TArgs>>>, OrderByArg extends Prisma.True extends HasSelectOrTake ? { orderBy: Prisma.DataSetRowGroupByArgs['orderBy'] } : { orderBy?: Prisma.DataSetRowGroupByArgs['orderBy'] }, OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<TArgs['orderBy']>>>, ByFields extends Prisma.MaybeTupleToUnion<TArgs['by']>, ByValid extends Prisma.Has<ByFields, OrderFields>, HavingFields extends Prisma.GetHavingFields<TArgs['having']>, HavingValid extends Prisma.Has<ByFields, HavingFields>, ByEmpty extends TArgs['by'] extends never[] ? Prisma.True : Prisma.False, InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
        ? never
        : P extends string
        ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
        : [
            Error,
            'Field ',
            P,
            ` in "having" needs to be provided in "by"`,
        ]
    }[HavingFields]
    : 'take' extends Prisma.Keys<TArgs>
    ? 'orderBy' extends Prisma.Keys<TArgs>
    ? ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields]
    : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<TArgs>
    ? 'orderBy' extends Prisma.Keys<TArgs>
    ? ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields]
    : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields], TQueryFnData = {} extends InputErrors ?
    Array<PickEnumerable<Prisma.DataSetRowGroupByOutputType, TArgs['by']> &
    {
        [P in ((keyof TArgs) & (keyof Prisma.DataSetRowGroupByOutputType))]: P extends '_count'
        ? TArgs[P] extends boolean
        ? number
        : Prisma.GetScalarType<TArgs[P], Prisma.DataSetRowGroupByOutputType[P]>
        : Prisma.GetScalarType<TArgs[P], Prisma.DataSetRowGroupByOutputType[P]>
    }
    > : InputErrors, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.SubsetIntersection<TArgs, Prisma.DataSetRowGroupByArgs, OrderByArg> & InputErrors>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('DataSetRow', `${endpoint}/dataSetRow/groupBy`, args, options, fetch);
}

export function useCountDataSetRow<TArgs extends Prisma.DataSetRowCountArgs, TQueryFnData = TArgs extends { select: any; } ? TArgs['select'] extends true ? number : Prisma.GetScalarType<TArgs['select'], Prisma.DataSetRowCountAggregateOutputType> : number, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.DataSetRowCountArgs>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('DataSetRow', `${endpoint}/dataSetRow/count`, args, options, fetch);
}

export function useSuspenseCountDataSetRow<TArgs extends Prisma.DataSetRowCountArgs, TQueryFnData = TArgs extends { select: any; } ? TArgs['select'] extends true ? number : Prisma.GetScalarType<TArgs['select'], Prisma.DataSetRowCountAggregateOutputType> : number, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.DataSetRowCountArgs>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('DataSetRow', `${endpoint}/dataSetRow/count`, args, options, fetch);
}

export function useCheckDataSetRow<TError = DefaultError>(args: { operation: PolicyCrudKind; where?: { id?: number; dataSetId?: number; rowIndex?: number; label?: string; isDeleted?: boolean }; }, options?: (Omit<UseQueryOptions<boolean, TError, boolean>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<boolean, boolean, TError>('DataSetRow', `${endpoint}/dataSetRow/check`, args, options, fetch);
}
