/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */

import type { Prisma, IntegrationProject } from "@prisma/client";
import type { UseMutationOptions, UseQueryOptions, UseInfiniteQueryOptions, InfiniteData } from '@tanstack/react-query';
import { getHooksContext } from '@zenstackhq/tanstack-query/runtime-v5/react';
import { useModelQuery, useInfiniteModelQuery, useModelMutation } from '@zenstackhq/tanstack-query/runtime-v5/react';
import type { PickEnumerable, CheckSelect, QueryError, ExtraQueryOptions, ExtraMutationOptions } from '@zenstackhq/tanstack-query/runtime-v5';
import type { PolicyCrudKind } from '@zenstackhq/runtime'
import metadata from './__model_meta';
type DefaultError = QueryError;
import { useSuspenseModelQuery, useSuspenseInfiniteModelQuery } from '@zenstackhq/tanstack-query/runtime-v5/react';
import type { UseSuspenseQueryOptions, UseSuspenseInfiniteQueryOptions } from '@tanstack/react-query';

export function useCreateIntegrationProject(options?: Omit<(UseMutationOptions<(IntegrationProject | undefined), DefaultError, Prisma.IntegrationProjectCreateArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.IntegrationProjectCreateArgs, DefaultError, IntegrationProject, true>('IntegrationProject', 'POST', `${endpoint}/integrationProject/create`, metadata, options, fetch, true)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.IntegrationProjectCreateArgs>(
            args: Prisma.SelectSubset<T, Prisma.IntegrationProjectCreateArgs>,
            options?: Omit<(UseMutationOptions<(CheckSelect<T, IntegrationProject, Prisma.IntegrationProjectGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.IntegrationProjectCreateArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as (CheckSelect<T, IntegrationProject, Prisma.IntegrationProjectGetPayload<T>> | undefined);
        },
    };
    return mutation;
}

export function useCreateManyIntegrationProject(options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.IntegrationProjectCreateManyArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.IntegrationProjectCreateManyArgs, DefaultError, Prisma.BatchPayload, false>('IntegrationProject', 'POST', `${endpoint}/integrationProject/createMany`, metadata, options, fetch, false)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.IntegrationProjectCreateManyArgs>(
            args: Prisma.SelectSubset<T, Prisma.IntegrationProjectCreateManyArgs>,
            options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.SelectSubset<T, Prisma.IntegrationProjectCreateManyArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as Prisma.BatchPayload;
        },
    };
    return mutation;
}

export function useFindManyIntegrationProject<TArgs extends Prisma.IntegrationProjectFindManyArgs, TQueryFnData = Array<Prisma.IntegrationProjectGetPayload<TArgs> & { $optimistic?: boolean }>, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.IntegrationProjectFindManyArgs>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('IntegrationProject', `${endpoint}/integrationProject/findMany`, args, options, fetch);
}

export function useInfiniteFindManyIntegrationProject<TArgs extends Prisma.IntegrationProjectFindManyArgs, TQueryFnData = Array<Prisma.IntegrationProjectGetPayload<TArgs>>, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.IntegrationProjectFindManyArgs>, options?: Omit<UseInfiniteQueryOptions<TQueryFnData, TError, InfiniteData<TData>>, 'queryKey' | 'initialPageParam'>) {
    options = options ?? { getNextPageParam: () => null };
    const { endpoint, fetch } = getHooksContext();
    return useInfiniteModelQuery<TQueryFnData, TData, TError>('IntegrationProject', `${endpoint}/integrationProject/findMany`, args, options, fetch);
}

export function useSuspenseFindManyIntegrationProject<TArgs extends Prisma.IntegrationProjectFindManyArgs, TQueryFnData = Array<Prisma.IntegrationProjectGetPayload<TArgs> & { $optimistic?: boolean }>, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.IntegrationProjectFindManyArgs>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('IntegrationProject', `${endpoint}/integrationProject/findMany`, args, options, fetch);
}

export function useSuspenseInfiniteFindManyIntegrationProject<TArgs extends Prisma.IntegrationProjectFindManyArgs, TQueryFnData = Array<Prisma.IntegrationProjectGetPayload<TArgs>>, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.IntegrationProjectFindManyArgs>, options?: Omit<UseSuspenseInfiniteQueryOptions<TQueryFnData, TError, InfiniteData<TData>>, 'queryKey' | 'initialPageParam'>) {
    options = options ?? { getNextPageParam: () => null };
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseInfiniteModelQuery<TQueryFnData, TData, TError>('IntegrationProject', `${endpoint}/integrationProject/findMany`, args, options, fetch);
}

export function useFindUniqueIntegrationProject<TArgs extends Prisma.IntegrationProjectFindUniqueArgs, TQueryFnData = Prisma.IntegrationProjectGetPayload<TArgs> & { $optimistic?: boolean }, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.IntegrationProjectFindUniqueArgs>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('IntegrationProject', `${endpoint}/integrationProject/findUnique`, args, options, fetch);
}

export function useSuspenseFindUniqueIntegrationProject<TArgs extends Prisma.IntegrationProjectFindUniqueArgs, TQueryFnData = Prisma.IntegrationProjectGetPayload<TArgs> & { $optimistic?: boolean }, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.IntegrationProjectFindUniqueArgs>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('IntegrationProject', `${endpoint}/integrationProject/findUnique`, args, options, fetch);
}

export function useFindFirstIntegrationProject<TArgs extends Prisma.IntegrationProjectFindFirstArgs, TQueryFnData = Prisma.IntegrationProjectGetPayload<TArgs> & { $optimistic?: boolean }, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.IntegrationProjectFindFirstArgs>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('IntegrationProject', `${endpoint}/integrationProject/findFirst`, args, options, fetch);
}

export function useSuspenseFindFirstIntegrationProject<TArgs extends Prisma.IntegrationProjectFindFirstArgs, TQueryFnData = Prisma.IntegrationProjectGetPayload<TArgs> & { $optimistic?: boolean }, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.IntegrationProjectFindFirstArgs>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('IntegrationProject', `${endpoint}/integrationProject/findFirst`, args, options, fetch);
}

export function useUpdateIntegrationProject(options?: Omit<(UseMutationOptions<(IntegrationProject | undefined), DefaultError, Prisma.IntegrationProjectUpdateArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.IntegrationProjectUpdateArgs, DefaultError, IntegrationProject, true>('IntegrationProject', 'PUT', `${endpoint}/integrationProject/update`, metadata, options, fetch, true)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.IntegrationProjectUpdateArgs>(
            args: Prisma.SelectSubset<T, Prisma.IntegrationProjectUpdateArgs>,
            options?: Omit<(UseMutationOptions<(CheckSelect<T, IntegrationProject, Prisma.IntegrationProjectGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.IntegrationProjectUpdateArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as (CheckSelect<T, IntegrationProject, Prisma.IntegrationProjectGetPayload<T>> | undefined);
        },
    };
    return mutation;
}

export function useUpdateManyIntegrationProject(options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.IntegrationProjectUpdateManyArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.IntegrationProjectUpdateManyArgs, DefaultError, Prisma.BatchPayload, false>('IntegrationProject', 'PUT', `${endpoint}/integrationProject/updateMany`, metadata, options, fetch, false)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.IntegrationProjectUpdateManyArgs>(
            args: Prisma.SelectSubset<T, Prisma.IntegrationProjectUpdateManyArgs>,
            options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.SelectSubset<T, Prisma.IntegrationProjectUpdateManyArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as Prisma.BatchPayload;
        },
    };
    return mutation;
}

export function useUpsertIntegrationProject(options?: Omit<(UseMutationOptions<(IntegrationProject | undefined), DefaultError, Prisma.IntegrationProjectUpsertArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.IntegrationProjectUpsertArgs, DefaultError, IntegrationProject, true>('IntegrationProject', 'POST', `${endpoint}/integrationProject/upsert`, metadata, options, fetch, true)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.IntegrationProjectUpsertArgs>(
            args: Prisma.SelectSubset<T, Prisma.IntegrationProjectUpsertArgs>,
            options?: Omit<(UseMutationOptions<(CheckSelect<T, IntegrationProject, Prisma.IntegrationProjectGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.IntegrationProjectUpsertArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as (CheckSelect<T, IntegrationProject, Prisma.IntegrationProjectGetPayload<T>> | undefined);
        },
    };
    return mutation;
}

export function useDeleteIntegrationProject(options?: Omit<(UseMutationOptions<(IntegrationProject | undefined), DefaultError, Prisma.IntegrationProjectDeleteArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.IntegrationProjectDeleteArgs, DefaultError, IntegrationProject, true>('IntegrationProject', 'DELETE', `${endpoint}/integrationProject/delete`, metadata, options, fetch, true)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.IntegrationProjectDeleteArgs>(
            args: Prisma.SelectSubset<T, Prisma.IntegrationProjectDeleteArgs>,
            options?: Omit<(UseMutationOptions<(CheckSelect<T, IntegrationProject, Prisma.IntegrationProjectGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.IntegrationProjectDeleteArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as (CheckSelect<T, IntegrationProject, Prisma.IntegrationProjectGetPayload<T>> | undefined);
        },
    };
    return mutation;
}

export function useDeleteManyIntegrationProject(options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.IntegrationProjectDeleteManyArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.IntegrationProjectDeleteManyArgs, DefaultError, Prisma.BatchPayload, false>('IntegrationProject', 'DELETE', `${endpoint}/integrationProject/deleteMany`, metadata, options, fetch, false)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.IntegrationProjectDeleteManyArgs>(
            args: Prisma.SelectSubset<T, Prisma.IntegrationProjectDeleteManyArgs>,
            options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.SelectSubset<T, Prisma.IntegrationProjectDeleteManyArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as Prisma.BatchPayload;
        },
    };
    return mutation;
}

export function useAggregateIntegrationProject<TArgs extends Prisma.IntegrationProjectAggregateArgs, TQueryFnData = Prisma.GetIntegrationProjectAggregateType<TArgs>, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.IntegrationProjectAggregateArgs>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('IntegrationProject', `${endpoint}/integrationProject/aggregate`, args, options, fetch);
}

export function useSuspenseAggregateIntegrationProject<TArgs extends Prisma.IntegrationProjectAggregateArgs, TQueryFnData = Prisma.GetIntegrationProjectAggregateType<TArgs>, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.IntegrationProjectAggregateArgs>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('IntegrationProject', `${endpoint}/integrationProject/aggregate`, args, options, fetch);
}

export function useGroupByIntegrationProject<TArgs extends Prisma.IntegrationProjectGroupByArgs, HasSelectOrTake extends Prisma.Or<Prisma.Extends<'skip', Prisma.Keys<TArgs>>, Prisma.Extends<'take', Prisma.Keys<TArgs>>>, OrderByArg extends Prisma.True extends HasSelectOrTake ? { orderBy: Prisma.IntegrationProjectGroupByArgs['orderBy'] } : { orderBy?: Prisma.IntegrationProjectGroupByArgs['orderBy'] }, OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<TArgs['orderBy']>>>, ByFields extends Prisma.MaybeTupleToUnion<TArgs['by']>, ByValid extends Prisma.Has<ByFields, OrderFields>, HavingFields extends Prisma.GetHavingFields<TArgs['having']>, HavingValid extends Prisma.Has<ByFields, HavingFields>, ByEmpty extends TArgs['by'] extends never[] ? Prisma.True : Prisma.False, InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
        ? never
        : P extends string
        ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
        : [
            Error,
            'Field ',
            P,
            ` in "having" needs to be provided in "by"`,
        ]
    }[HavingFields]
    : 'take' extends Prisma.Keys<TArgs>
    ? 'orderBy' extends Prisma.Keys<TArgs>
    ? ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields]
    : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<TArgs>
    ? 'orderBy' extends Prisma.Keys<TArgs>
    ? ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields]
    : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields], TQueryFnData = {} extends InputErrors ?
    Array<PickEnumerable<Prisma.IntegrationProjectGroupByOutputType, TArgs['by']> &
    {
        [P in ((keyof TArgs) & (keyof Prisma.IntegrationProjectGroupByOutputType))]: P extends '_count'
        ? TArgs[P] extends boolean
        ? number
        : Prisma.GetScalarType<TArgs[P], Prisma.IntegrationProjectGroupByOutputType[P]>
        : Prisma.GetScalarType<TArgs[P], Prisma.IntegrationProjectGroupByOutputType[P]>
    }
    > : InputErrors, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.SubsetIntersection<TArgs, Prisma.IntegrationProjectGroupByArgs, OrderByArg> & InputErrors>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('IntegrationProject', `${endpoint}/integrationProject/groupBy`, args, options, fetch);
}

export function useSuspenseGroupByIntegrationProject<TArgs extends Prisma.IntegrationProjectGroupByArgs, HasSelectOrTake extends Prisma.Or<Prisma.Extends<'skip', Prisma.Keys<TArgs>>, Prisma.Extends<'take', Prisma.Keys<TArgs>>>, OrderByArg extends Prisma.True extends HasSelectOrTake ? { orderBy: Prisma.IntegrationProjectGroupByArgs['orderBy'] } : { orderBy?: Prisma.IntegrationProjectGroupByArgs['orderBy'] }, OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<TArgs['orderBy']>>>, ByFields extends Prisma.MaybeTupleToUnion<TArgs['by']>, ByValid extends Prisma.Has<ByFields, OrderFields>, HavingFields extends Prisma.GetHavingFields<TArgs['having']>, HavingValid extends Prisma.Has<ByFields, HavingFields>, ByEmpty extends TArgs['by'] extends never[] ? Prisma.True : Prisma.False, InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
        ? never
        : P extends string
        ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
        : [
            Error,
            'Field ',
            P,
            ` in "having" needs to be provided in "by"`,
        ]
    }[HavingFields]
    : 'take' extends Prisma.Keys<TArgs>
    ? 'orderBy' extends Prisma.Keys<TArgs>
    ? ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields]
    : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<TArgs>
    ? 'orderBy' extends Prisma.Keys<TArgs>
    ? ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields]
    : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields], TQueryFnData = {} extends InputErrors ?
    Array<PickEnumerable<Prisma.IntegrationProjectGroupByOutputType, TArgs['by']> &
    {
        [P in ((keyof TArgs) & (keyof Prisma.IntegrationProjectGroupByOutputType))]: P extends '_count'
        ? TArgs[P] extends boolean
        ? number
        : Prisma.GetScalarType<TArgs[P], Prisma.IntegrationProjectGroupByOutputType[P]>
        : Prisma.GetScalarType<TArgs[P], Prisma.IntegrationProjectGroupByOutputType[P]>
    }
    > : InputErrors, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.SubsetIntersection<TArgs, Prisma.IntegrationProjectGroupByArgs, OrderByArg> & InputErrors>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('IntegrationProject', `${endpoint}/integrationProject/groupBy`, args, options, fetch);
}

export function useCountIntegrationProject<TArgs extends Prisma.IntegrationProjectCountArgs, TQueryFnData = TArgs extends { select: any; } ? TArgs['select'] extends true ? number : Prisma.GetScalarType<TArgs['select'], Prisma.IntegrationProjectCountAggregateOutputType> : number, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.IntegrationProjectCountArgs>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('IntegrationProject', `${endpoint}/integrationProject/count`, args, options, fetch);
}

export function useSuspenseCountIntegrationProject<TArgs extends Prisma.IntegrationProjectCountArgs, TQueryFnData = TArgs extends { select: any; } ? TArgs['select'] extends true ? number : Prisma.GetScalarType<TArgs['select'], Prisma.IntegrationProjectCountAggregateOutputType> : number, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.IntegrationProjectCountArgs>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('IntegrationProject', `${endpoint}/integrationProject/count`, args, options, fetch);
}

export function useCheckIntegrationProject<TError = DefaultError>(args: { operation: PolicyCrudKind; where?: { id?: string; projectIntegrationId?: string; externalProjectId?: string; externalProjectKey?: string; externalProjectName?: string; isActive?: boolean; isDefault?: boolean; defaultIssueType?: string; defaultIssueTypeName?: string; syncStatus?: string; syncError?: string }; }, options?: (Omit<UseQueryOptions<boolean, TError, boolean>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<boolean, boolean, TError>('IntegrationProject', `${endpoint}/integrationProject/check`, args, options, fetch);
}
