/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */

import type { Prisma, LlmReportSnapshot } from "@prisma/client";
import type { UseMutationOptions, UseQueryOptions, UseInfiniteQueryOptions, InfiniteData } from '@tanstack/react-query';
import { getHooksContext } from '@zenstackhq/tanstack-query/runtime-v5/react';
import { useModelQuery, useInfiniteModelQuery, useModelMutation } from '@zenstackhq/tanstack-query/runtime-v5/react';
import type { PickEnumerable, CheckSelect, QueryError, ExtraQueryOptions, ExtraMutationOptions } from '@zenstackhq/tanstack-query/runtime-v5';
import type { PolicyCrudKind } from '@zenstackhq/runtime'
import metadata from './__model_meta';
type DefaultError = QueryError;
import { useSuspenseModelQuery, useSuspenseInfiniteModelQuery } from '@zenstackhq/tanstack-query/runtime-v5/react';
import type { UseSuspenseQueryOptions, UseSuspenseInfiniteQueryOptions } from '@tanstack/react-query';

export function useCreateLlmReportSnapshot(options?: Omit<(UseMutationOptions<(LlmReportSnapshot | undefined), DefaultError, Prisma.LlmReportSnapshotCreateArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.LlmReportSnapshotCreateArgs, DefaultError, LlmReportSnapshot, true>('LlmReportSnapshot', 'POST', `${endpoint}/llmReportSnapshot/create`, metadata, options, fetch, true)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.LlmReportSnapshotCreateArgs>(
            args: Prisma.SelectSubset<T, Prisma.LlmReportSnapshotCreateArgs>,
            options?: Omit<(UseMutationOptions<(CheckSelect<T, LlmReportSnapshot, Prisma.LlmReportSnapshotGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.LlmReportSnapshotCreateArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as (CheckSelect<T, LlmReportSnapshot, Prisma.LlmReportSnapshotGetPayload<T>> | undefined);
        },
    };
    return mutation;
}

export function useCreateManyLlmReportSnapshot(options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.LlmReportSnapshotCreateManyArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.LlmReportSnapshotCreateManyArgs, DefaultError, Prisma.BatchPayload, false>('LlmReportSnapshot', 'POST', `${endpoint}/llmReportSnapshot/createMany`, metadata, options, fetch, false)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.LlmReportSnapshotCreateManyArgs>(
            args: Prisma.SelectSubset<T, Prisma.LlmReportSnapshotCreateManyArgs>,
            options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.SelectSubset<T, Prisma.LlmReportSnapshotCreateManyArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as Prisma.BatchPayload;
        },
    };
    return mutation;
}

export function useFindManyLlmReportSnapshot<TArgs extends Prisma.LlmReportSnapshotFindManyArgs, TQueryFnData = Array<Prisma.LlmReportSnapshotGetPayload<TArgs> & { $optimistic?: boolean }>, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.LlmReportSnapshotFindManyArgs>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('LlmReportSnapshot', `${endpoint}/llmReportSnapshot/findMany`, args, options, fetch);
}

export function useInfiniteFindManyLlmReportSnapshot<TArgs extends Prisma.LlmReportSnapshotFindManyArgs, TQueryFnData = Array<Prisma.LlmReportSnapshotGetPayload<TArgs>>, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.LlmReportSnapshotFindManyArgs>, options?: Omit<UseInfiniteQueryOptions<TQueryFnData, TError, InfiniteData<TData>>, 'queryKey' | 'initialPageParam'>) {
    options = options ?? { getNextPageParam: () => null };
    const { endpoint, fetch } = getHooksContext();
    return useInfiniteModelQuery<TQueryFnData, TData, TError>('LlmReportSnapshot', `${endpoint}/llmReportSnapshot/findMany`, args, options, fetch);
}

export function useSuspenseFindManyLlmReportSnapshot<TArgs extends Prisma.LlmReportSnapshotFindManyArgs, TQueryFnData = Array<Prisma.LlmReportSnapshotGetPayload<TArgs> & { $optimistic?: boolean }>, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.LlmReportSnapshotFindManyArgs>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('LlmReportSnapshot', `${endpoint}/llmReportSnapshot/findMany`, args, options, fetch);
}

export function useSuspenseInfiniteFindManyLlmReportSnapshot<TArgs extends Prisma.LlmReportSnapshotFindManyArgs, TQueryFnData = Array<Prisma.LlmReportSnapshotGetPayload<TArgs>>, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.LlmReportSnapshotFindManyArgs>, options?: Omit<UseSuspenseInfiniteQueryOptions<TQueryFnData, TError, InfiniteData<TData>>, 'queryKey' | 'initialPageParam'>) {
    options = options ?? { getNextPageParam: () => null };
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseInfiniteModelQuery<TQueryFnData, TData, TError>('LlmReportSnapshot', `${endpoint}/llmReportSnapshot/findMany`, args, options, fetch);
}

export function useFindUniqueLlmReportSnapshot<TArgs extends Prisma.LlmReportSnapshotFindUniqueArgs, TQueryFnData = Prisma.LlmReportSnapshotGetPayload<TArgs> & { $optimistic?: boolean }, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.LlmReportSnapshotFindUniqueArgs>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('LlmReportSnapshot', `${endpoint}/llmReportSnapshot/findUnique`, args, options, fetch);
}

export function useSuspenseFindUniqueLlmReportSnapshot<TArgs extends Prisma.LlmReportSnapshotFindUniqueArgs, TQueryFnData = Prisma.LlmReportSnapshotGetPayload<TArgs> & { $optimistic?: boolean }, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.LlmReportSnapshotFindUniqueArgs>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('LlmReportSnapshot', `${endpoint}/llmReportSnapshot/findUnique`, args, options, fetch);
}

export function useFindFirstLlmReportSnapshot<TArgs extends Prisma.LlmReportSnapshotFindFirstArgs, TQueryFnData = Prisma.LlmReportSnapshotGetPayload<TArgs> & { $optimistic?: boolean }, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.LlmReportSnapshotFindFirstArgs>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('LlmReportSnapshot', `${endpoint}/llmReportSnapshot/findFirst`, args, options, fetch);
}

export function useSuspenseFindFirstLlmReportSnapshot<TArgs extends Prisma.LlmReportSnapshotFindFirstArgs, TQueryFnData = Prisma.LlmReportSnapshotGetPayload<TArgs> & { $optimistic?: boolean }, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.LlmReportSnapshotFindFirstArgs>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('LlmReportSnapshot', `${endpoint}/llmReportSnapshot/findFirst`, args, options, fetch);
}

export function useUpdateLlmReportSnapshot(options?: Omit<(UseMutationOptions<(LlmReportSnapshot | undefined), DefaultError, Prisma.LlmReportSnapshotUpdateArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.LlmReportSnapshotUpdateArgs, DefaultError, LlmReportSnapshot, true>('LlmReportSnapshot', 'PUT', `${endpoint}/llmReportSnapshot/update`, metadata, options, fetch, true)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.LlmReportSnapshotUpdateArgs>(
            args: Prisma.SelectSubset<T, Prisma.LlmReportSnapshotUpdateArgs>,
            options?: Omit<(UseMutationOptions<(CheckSelect<T, LlmReportSnapshot, Prisma.LlmReportSnapshotGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.LlmReportSnapshotUpdateArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as (CheckSelect<T, LlmReportSnapshot, Prisma.LlmReportSnapshotGetPayload<T>> | undefined);
        },
    };
    return mutation;
}

export function useUpdateManyLlmReportSnapshot(options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.LlmReportSnapshotUpdateManyArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.LlmReportSnapshotUpdateManyArgs, DefaultError, Prisma.BatchPayload, false>('LlmReportSnapshot', 'PUT', `${endpoint}/llmReportSnapshot/updateMany`, metadata, options, fetch, false)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.LlmReportSnapshotUpdateManyArgs>(
            args: Prisma.SelectSubset<T, Prisma.LlmReportSnapshotUpdateManyArgs>,
            options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.SelectSubset<T, Prisma.LlmReportSnapshotUpdateManyArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as Prisma.BatchPayload;
        },
    };
    return mutation;
}

export function useUpsertLlmReportSnapshot(options?: Omit<(UseMutationOptions<(LlmReportSnapshot | undefined), DefaultError, Prisma.LlmReportSnapshotUpsertArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.LlmReportSnapshotUpsertArgs, DefaultError, LlmReportSnapshot, true>('LlmReportSnapshot', 'POST', `${endpoint}/llmReportSnapshot/upsert`, metadata, options, fetch, true)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.LlmReportSnapshotUpsertArgs>(
            args: Prisma.SelectSubset<T, Prisma.LlmReportSnapshotUpsertArgs>,
            options?: Omit<(UseMutationOptions<(CheckSelect<T, LlmReportSnapshot, Prisma.LlmReportSnapshotGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.LlmReportSnapshotUpsertArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as (CheckSelect<T, LlmReportSnapshot, Prisma.LlmReportSnapshotGetPayload<T>> | undefined);
        },
    };
    return mutation;
}

export function useDeleteLlmReportSnapshot(options?: Omit<(UseMutationOptions<(LlmReportSnapshot | undefined), DefaultError, Prisma.LlmReportSnapshotDeleteArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.LlmReportSnapshotDeleteArgs, DefaultError, LlmReportSnapshot, true>('LlmReportSnapshot', 'DELETE', `${endpoint}/llmReportSnapshot/delete`, metadata, options, fetch, true)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.LlmReportSnapshotDeleteArgs>(
            args: Prisma.SelectSubset<T, Prisma.LlmReportSnapshotDeleteArgs>,
            options?: Omit<(UseMutationOptions<(CheckSelect<T, LlmReportSnapshot, Prisma.LlmReportSnapshotGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.LlmReportSnapshotDeleteArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as (CheckSelect<T, LlmReportSnapshot, Prisma.LlmReportSnapshotGetPayload<T>> | undefined);
        },
    };
    return mutation;
}

export function useDeleteManyLlmReportSnapshot(options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.LlmReportSnapshotDeleteManyArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.LlmReportSnapshotDeleteManyArgs, DefaultError, Prisma.BatchPayload, false>('LlmReportSnapshot', 'DELETE', `${endpoint}/llmReportSnapshot/deleteMany`, metadata, options, fetch, false)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.LlmReportSnapshotDeleteManyArgs>(
            args: Prisma.SelectSubset<T, Prisma.LlmReportSnapshotDeleteManyArgs>,
            options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.SelectSubset<T, Prisma.LlmReportSnapshotDeleteManyArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as Prisma.BatchPayload;
        },
    };
    return mutation;
}

export function useAggregateLlmReportSnapshot<TArgs extends Prisma.LlmReportSnapshotAggregateArgs, TQueryFnData = Prisma.GetLlmReportSnapshotAggregateType<TArgs>, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.LlmReportSnapshotAggregateArgs>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('LlmReportSnapshot', `${endpoint}/llmReportSnapshot/aggregate`, args, options, fetch);
}

export function useSuspenseAggregateLlmReportSnapshot<TArgs extends Prisma.LlmReportSnapshotAggregateArgs, TQueryFnData = Prisma.GetLlmReportSnapshotAggregateType<TArgs>, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.LlmReportSnapshotAggregateArgs>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('LlmReportSnapshot', `${endpoint}/llmReportSnapshot/aggregate`, args, options, fetch);
}

export function useGroupByLlmReportSnapshot<TArgs extends Prisma.LlmReportSnapshotGroupByArgs, HasSelectOrTake extends Prisma.Or<Prisma.Extends<'skip', Prisma.Keys<TArgs>>, Prisma.Extends<'take', Prisma.Keys<TArgs>>>, OrderByArg extends Prisma.True extends HasSelectOrTake ? { orderBy: Prisma.LlmReportSnapshotGroupByArgs['orderBy'] } : { orderBy?: Prisma.LlmReportSnapshotGroupByArgs['orderBy'] }, OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<TArgs['orderBy']>>>, ByFields extends Prisma.MaybeTupleToUnion<TArgs['by']>, ByValid extends Prisma.Has<ByFields, OrderFields>, HavingFields extends Prisma.GetHavingFields<TArgs['having']>, HavingValid extends Prisma.Has<ByFields, HavingFields>, ByEmpty extends TArgs['by'] extends never[] ? Prisma.True : Prisma.False, InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
        ? never
        : P extends string
        ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
        : [
            Error,
            'Field ',
            P,
            ` in "having" needs to be provided in "by"`,
        ]
    }[HavingFields]
    : 'take' extends Prisma.Keys<TArgs>
    ? 'orderBy' extends Prisma.Keys<TArgs>
    ? ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields]
    : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<TArgs>
    ? 'orderBy' extends Prisma.Keys<TArgs>
    ? ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields]
    : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields], TQueryFnData = {} extends InputErrors ?
    Array<PickEnumerable<Prisma.LlmReportSnapshotGroupByOutputType, TArgs['by']> &
    {
        [P in ((keyof TArgs) & (keyof Prisma.LlmReportSnapshotGroupByOutputType))]: P extends '_count'
        ? TArgs[P] extends boolean
        ? number
        : Prisma.GetScalarType<TArgs[P], Prisma.LlmReportSnapshotGroupByOutputType[P]>
        : Prisma.GetScalarType<TArgs[P], Prisma.LlmReportSnapshotGroupByOutputType[P]>
    }
    > : InputErrors, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.SubsetIntersection<TArgs, Prisma.LlmReportSnapshotGroupByArgs, OrderByArg> & InputErrors>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('LlmReportSnapshot', `${endpoint}/llmReportSnapshot/groupBy`, args, options, fetch);
}

export function useSuspenseGroupByLlmReportSnapshot<TArgs extends Prisma.LlmReportSnapshotGroupByArgs, HasSelectOrTake extends Prisma.Or<Prisma.Extends<'skip', Prisma.Keys<TArgs>>, Prisma.Extends<'take', Prisma.Keys<TArgs>>>, OrderByArg extends Prisma.True extends HasSelectOrTake ? { orderBy: Prisma.LlmReportSnapshotGroupByArgs['orderBy'] } : { orderBy?: Prisma.LlmReportSnapshotGroupByArgs['orderBy'] }, OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<TArgs['orderBy']>>>, ByFields extends Prisma.MaybeTupleToUnion<TArgs['by']>, ByValid extends Prisma.Has<ByFields, OrderFields>, HavingFields extends Prisma.GetHavingFields<TArgs['having']>, HavingValid extends Prisma.Has<ByFields, HavingFields>, ByEmpty extends TArgs['by'] extends never[] ? Prisma.True : Prisma.False, InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
        ? never
        : P extends string
        ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
        : [
            Error,
            'Field ',
            P,
            ` in "having" needs to be provided in "by"`,
        ]
    }[HavingFields]
    : 'take' extends Prisma.Keys<TArgs>
    ? 'orderBy' extends Prisma.Keys<TArgs>
    ? ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields]
    : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<TArgs>
    ? 'orderBy' extends Prisma.Keys<TArgs>
    ? ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields]
    : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields], TQueryFnData = {} extends InputErrors ?
    Array<PickEnumerable<Prisma.LlmReportSnapshotGroupByOutputType, TArgs['by']> &
    {
        [P in ((keyof TArgs) & (keyof Prisma.LlmReportSnapshotGroupByOutputType))]: P extends '_count'
        ? TArgs[P] extends boolean
        ? number
        : Prisma.GetScalarType<TArgs[P], Prisma.LlmReportSnapshotGroupByOutputType[P]>
        : Prisma.GetScalarType<TArgs[P], Prisma.LlmReportSnapshotGroupByOutputType[P]>
    }
    > : InputErrors, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.SubsetIntersection<TArgs, Prisma.LlmReportSnapshotGroupByArgs, OrderByArg> & InputErrors>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('LlmReportSnapshot', `${endpoint}/llmReportSnapshot/groupBy`, args, options, fetch);
}

export function useCountLlmReportSnapshot<TArgs extends Prisma.LlmReportSnapshotCountArgs, TQueryFnData = TArgs extends { select: any; } ? TArgs['select'] extends true ? number : Prisma.GetScalarType<TArgs['select'], Prisma.LlmReportSnapshotCountAggregateOutputType> : number, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.LlmReportSnapshotCountArgs>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('LlmReportSnapshot', `${endpoint}/llmReportSnapshot/count`, args, options, fetch);
}

export function useSuspenseCountLlmReportSnapshot<TArgs extends Prisma.LlmReportSnapshotCountArgs, TQueryFnData = TArgs extends { select: any; } ? TArgs['select'] extends true ? number : Prisma.GetScalarType<TArgs['select'], Prisma.LlmReportSnapshotCountAggregateOutputType> : number, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.LlmReportSnapshotCountArgs>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('LlmReportSnapshot', `${endpoint}/llmReportSnapshot/count`, args, options, fetch);
}

export function useCheckLlmReportSnapshot<TError = DefaultError>(args: { operation: PolicyCrudKind; where?: { id?: number; projectId?: number; reportType?: string; status?: string; llmIntegrationId?: number; generatedById?: string; errorMessage?: string; isDeleted?: boolean }; }, options?: (Omit<UseQueryOptions<boolean, TError, boolean>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<boolean, boolean, TError>('LlmReportSnapshot', `${endpoint}/llmReportSnapshot/check`, args, options, fetch);
}
