/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */

import type { Prisma, PasswordHistory } from "@prisma/client";
import type { UseMutationOptions, UseQueryOptions, UseInfiniteQueryOptions, InfiniteData } from '@tanstack/react-query';
import { getHooksContext } from '@zenstackhq/tanstack-query/runtime-v5/react';
import { useModelQuery, useInfiniteModelQuery, useModelMutation } from '@zenstackhq/tanstack-query/runtime-v5/react';
import type { PickEnumerable, CheckSelect, QueryError, ExtraQueryOptions, ExtraMutationOptions } from '@zenstackhq/tanstack-query/runtime-v5';
import type { PolicyCrudKind } from '@zenstackhq/runtime'
import metadata from './__model_meta';
type DefaultError = QueryError;
import { useSuspenseModelQuery, useSuspenseInfiniteModelQuery } from '@zenstackhq/tanstack-query/runtime-v5/react';
import type { UseSuspenseQueryOptions, UseSuspenseInfiniteQueryOptions } from '@tanstack/react-query';

export function useCreatePasswordHistory(options?: Omit<(UseMutationOptions<(PasswordHistory | undefined), DefaultError, Prisma.PasswordHistoryCreateArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.PasswordHistoryCreateArgs, DefaultError, PasswordHistory, true>('PasswordHistory', 'POST', `${endpoint}/passwordHistory/create`, metadata, options, fetch, true)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.PasswordHistoryCreateArgs>(
            args: Prisma.SelectSubset<T, Prisma.PasswordHistoryCreateArgs>,
            options?: Omit<(UseMutationOptions<(CheckSelect<T, PasswordHistory, Prisma.PasswordHistoryGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.PasswordHistoryCreateArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as (CheckSelect<T, PasswordHistory, Prisma.PasswordHistoryGetPayload<T>> | undefined);
        },
    };
    return mutation;
}

export function useCreateManyPasswordHistory(options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.PasswordHistoryCreateManyArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.PasswordHistoryCreateManyArgs, DefaultError, Prisma.BatchPayload, false>('PasswordHistory', 'POST', `${endpoint}/passwordHistory/createMany`, metadata, options, fetch, false)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.PasswordHistoryCreateManyArgs>(
            args: Prisma.SelectSubset<T, Prisma.PasswordHistoryCreateManyArgs>,
            options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.SelectSubset<T, Prisma.PasswordHistoryCreateManyArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as Prisma.BatchPayload;
        },
    };
    return mutation;
}

export function useFindManyPasswordHistory<TArgs extends Prisma.PasswordHistoryFindManyArgs, TQueryFnData = Array<Prisma.PasswordHistoryGetPayload<TArgs> & { $optimistic?: boolean }>, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.PasswordHistoryFindManyArgs>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('PasswordHistory', `${endpoint}/passwordHistory/findMany`, args, options, fetch);
}

export function useInfiniteFindManyPasswordHistory<TArgs extends Prisma.PasswordHistoryFindManyArgs, TQueryFnData = Array<Prisma.PasswordHistoryGetPayload<TArgs>>, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.PasswordHistoryFindManyArgs>, options?: Omit<UseInfiniteQueryOptions<TQueryFnData, TError, InfiniteData<TData>>, 'queryKey' | 'initialPageParam'>) {
    options = options ?? { getNextPageParam: () => null };
    const { endpoint, fetch } = getHooksContext();
    return useInfiniteModelQuery<TQueryFnData, TData, TError>('PasswordHistory', `${endpoint}/passwordHistory/findMany`, args, options, fetch);
}

export function useSuspenseFindManyPasswordHistory<TArgs extends Prisma.PasswordHistoryFindManyArgs, TQueryFnData = Array<Prisma.PasswordHistoryGetPayload<TArgs> & { $optimistic?: boolean }>, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.PasswordHistoryFindManyArgs>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('PasswordHistory', `${endpoint}/passwordHistory/findMany`, args, options, fetch);
}

export function useSuspenseInfiniteFindManyPasswordHistory<TArgs extends Prisma.PasswordHistoryFindManyArgs, TQueryFnData = Array<Prisma.PasswordHistoryGetPayload<TArgs>>, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.PasswordHistoryFindManyArgs>, options?: Omit<UseSuspenseInfiniteQueryOptions<TQueryFnData, TError, InfiniteData<TData>>, 'queryKey' | 'initialPageParam'>) {
    options = options ?? { getNextPageParam: () => null };
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseInfiniteModelQuery<TQueryFnData, TData, TError>('PasswordHistory', `${endpoint}/passwordHistory/findMany`, args, options, fetch);
}

export function useFindUniquePasswordHistory<TArgs extends Prisma.PasswordHistoryFindUniqueArgs, TQueryFnData = Prisma.PasswordHistoryGetPayload<TArgs> & { $optimistic?: boolean }, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.PasswordHistoryFindUniqueArgs>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('PasswordHistory', `${endpoint}/passwordHistory/findUnique`, args, options, fetch);
}

export function useSuspenseFindUniquePasswordHistory<TArgs extends Prisma.PasswordHistoryFindUniqueArgs, TQueryFnData = Prisma.PasswordHistoryGetPayload<TArgs> & { $optimistic?: boolean }, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.PasswordHistoryFindUniqueArgs>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('PasswordHistory', `${endpoint}/passwordHistory/findUnique`, args, options, fetch);
}

export function useFindFirstPasswordHistory<TArgs extends Prisma.PasswordHistoryFindFirstArgs, TQueryFnData = Prisma.PasswordHistoryGetPayload<TArgs> & { $optimistic?: boolean }, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.PasswordHistoryFindFirstArgs>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('PasswordHistory', `${endpoint}/passwordHistory/findFirst`, args, options, fetch);
}

export function useSuspenseFindFirstPasswordHistory<TArgs extends Prisma.PasswordHistoryFindFirstArgs, TQueryFnData = Prisma.PasswordHistoryGetPayload<TArgs> & { $optimistic?: boolean }, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.PasswordHistoryFindFirstArgs>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('PasswordHistory', `${endpoint}/passwordHistory/findFirst`, args, options, fetch);
}

export function useUpdatePasswordHistory(options?: Omit<(UseMutationOptions<(PasswordHistory | undefined), DefaultError, Prisma.PasswordHistoryUpdateArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.PasswordHistoryUpdateArgs, DefaultError, PasswordHistory, true>('PasswordHistory', 'PUT', `${endpoint}/passwordHistory/update`, metadata, options, fetch, true)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.PasswordHistoryUpdateArgs>(
            args: Prisma.SelectSubset<T, Prisma.PasswordHistoryUpdateArgs>,
            options?: Omit<(UseMutationOptions<(CheckSelect<T, PasswordHistory, Prisma.PasswordHistoryGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.PasswordHistoryUpdateArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as (CheckSelect<T, PasswordHistory, Prisma.PasswordHistoryGetPayload<T>> | undefined);
        },
    };
    return mutation;
}

export function useUpdateManyPasswordHistory(options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.PasswordHistoryUpdateManyArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.PasswordHistoryUpdateManyArgs, DefaultError, Prisma.BatchPayload, false>('PasswordHistory', 'PUT', `${endpoint}/passwordHistory/updateMany`, metadata, options, fetch, false)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.PasswordHistoryUpdateManyArgs>(
            args: Prisma.SelectSubset<T, Prisma.PasswordHistoryUpdateManyArgs>,
            options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.SelectSubset<T, Prisma.PasswordHistoryUpdateManyArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as Prisma.BatchPayload;
        },
    };
    return mutation;
}

export function useUpsertPasswordHistory(options?: Omit<(UseMutationOptions<(PasswordHistory | undefined), DefaultError, Prisma.PasswordHistoryUpsertArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.PasswordHistoryUpsertArgs, DefaultError, PasswordHistory, true>('PasswordHistory', 'POST', `${endpoint}/passwordHistory/upsert`, metadata, options, fetch, true)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.PasswordHistoryUpsertArgs>(
            args: Prisma.SelectSubset<T, Prisma.PasswordHistoryUpsertArgs>,
            options?: Omit<(UseMutationOptions<(CheckSelect<T, PasswordHistory, Prisma.PasswordHistoryGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.PasswordHistoryUpsertArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as (CheckSelect<T, PasswordHistory, Prisma.PasswordHistoryGetPayload<T>> | undefined);
        },
    };
    return mutation;
}

export function useDeletePasswordHistory(options?: Omit<(UseMutationOptions<(PasswordHistory | undefined), DefaultError, Prisma.PasswordHistoryDeleteArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.PasswordHistoryDeleteArgs, DefaultError, PasswordHistory, true>('PasswordHistory', 'DELETE', `${endpoint}/passwordHistory/delete`, metadata, options, fetch, true)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.PasswordHistoryDeleteArgs>(
            args: Prisma.SelectSubset<T, Prisma.PasswordHistoryDeleteArgs>,
            options?: Omit<(UseMutationOptions<(CheckSelect<T, PasswordHistory, Prisma.PasswordHistoryGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.PasswordHistoryDeleteArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as (CheckSelect<T, PasswordHistory, Prisma.PasswordHistoryGetPayload<T>> | undefined);
        },
    };
    return mutation;
}

export function useDeleteManyPasswordHistory(options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.PasswordHistoryDeleteManyArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.PasswordHistoryDeleteManyArgs, DefaultError, Prisma.BatchPayload, false>('PasswordHistory', 'DELETE', `${endpoint}/passwordHistory/deleteMany`, metadata, options, fetch, false)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.PasswordHistoryDeleteManyArgs>(
            args: Prisma.SelectSubset<T, Prisma.PasswordHistoryDeleteManyArgs>,
            options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.SelectSubset<T, Prisma.PasswordHistoryDeleteManyArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as Prisma.BatchPayload;
        },
    };
    return mutation;
}

export function useAggregatePasswordHistory<TArgs extends Prisma.PasswordHistoryAggregateArgs, TQueryFnData = Prisma.GetPasswordHistoryAggregateType<TArgs>, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.PasswordHistoryAggregateArgs>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('PasswordHistory', `${endpoint}/passwordHistory/aggregate`, args, options, fetch);
}

export function useSuspenseAggregatePasswordHistory<TArgs extends Prisma.PasswordHistoryAggregateArgs, TQueryFnData = Prisma.GetPasswordHistoryAggregateType<TArgs>, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.PasswordHistoryAggregateArgs>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('PasswordHistory', `${endpoint}/passwordHistory/aggregate`, args, options, fetch);
}

export function useGroupByPasswordHistory<TArgs extends Prisma.PasswordHistoryGroupByArgs, HasSelectOrTake extends Prisma.Or<Prisma.Extends<'skip', Prisma.Keys<TArgs>>, Prisma.Extends<'take', Prisma.Keys<TArgs>>>, OrderByArg extends Prisma.True extends HasSelectOrTake ? { orderBy: Prisma.PasswordHistoryGroupByArgs['orderBy'] } : { orderBy?: Prisma.PasswordHistoryGroupByArgs['orderBy'] }, OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<TArgs['orderBy']>>>, ByFields extends Prisma.MaybeTupleToUnion<TArgs['by']>, ByValid extends Prisma.Has<ByFields, OrderFields>, HavingFields extends Prisma.GetHavingFields<TArgs['having']>, HavingValid extends Prisma.Has<ByFields, HavingFields>, ByEmpty extends TArgs['by'] extends never[] ? Prisma.True : Prisma.False, InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
        ? never
        : P extends string
        ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
        : [
            Error,
            'Field ',
            P,
            ` in "having" needs to be provided in "by"`,
        ]
    }[HavingFields]
    : 'take' extends Prisma.Keys<TArgs>
    ? 'orderBy' extends Prisma.Keys<TArgs>
    ? ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields]
    : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<TArgs>
    ? 'orderBy' extends Prisma.Keys<TArgs>
    ? ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields]
    : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields], TQueryFnData = {} extends InputErrors ?
    Array<PickEnumerable<Prisma.PasswordHistoryGroupByOutputType, TArgs['by']> &
    {
        [P in ((keyof TArgs) & (keyof Prisma.PasswordHistoryGroupByOutputType))]: P extends '_count'
        ? TArgs[P] extends boolean
        ? number
        : Prisma.GetScalarType<TArgs[P], Prisma.PasswordHistoryGroupByOutputType[P]>
        : Prisma.GetScalarType<TArgs[P], Prisma.PasswordHistoryGroupByOutputType[P]>
    }
    > : InputErrors, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.SubsetIntersection<TArgs, Prisma.PasswordHistoryGroupByArgs, OrderByArg> & InputErrors>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('PasswordHistory', `${endpoint}/passwordHistory/groupBy`, args, options, fetch);
}

export function useSuspenseGroupByPasswordHistory<TArgs extends Prisma.PasswordHistoryGroupByArgs, HasSelectOrTake extends Prisma.Or<Prisma.Extends<'skip', Prisma.Keys<TArgs>>, Prisma.Extends<'take', Prisma.Keys<TArgs>>>, OrderByArg extends Prisma.True extends HasSelectOrTake ? { orderBy: Prisma.PasswordHistoryGroupByArgs['orderBy'] } : { orderBy?: Prisma.PasswordHistoryGroupByArgs['orderBy'] }, OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<TArgs['orderBy']>>>, ByFields extends Prisma.MaybeTupleToUnion<TArgs['by']>, ByValid extends Prisma.Has<ByFields, OrderFields>, HavingFields extends Prisma.GetHavingFields<TArgs['having']>, HavingValid extends Prisma.Has<ByFields, HavingFields>, ByEmpty extends TArgs['by'] extends never[] ? Prisma.True : Prisma.False, InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
        ? never
        : P extends string
        ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
        : [
            Error,
            'Field ',
            P,
            ` in "having" needs to be provided in "by"`,
        ]
    }[HavingFields]
    : 'take' extends Prisma.Keys<TArgs>
    ? 'orderBy' extends Prisma.Keys<TArgs>
    ? ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields]
    : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<TArgs>
    ? 'orderBy' extends Prisma.Keys<TArgs>
    ? ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields]
    : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields], TQueryFnData = {} extends InputErrors ?
    Array<PickEnumerable<Prisma.PasswordHistoryGroupByOutputType, TArgs['by']> &
    {
        [P in ((keyof TArgs) & (keyof Prisma.PasswordHistoryGroupByOutputType))]: P extends '_count'
        ? TArgs[P] extends boolean
        ? number
        : Prisma.GetScalarType<TArgs[P], Prisma.PasswordHistoryGroupByOutputType[P]>
        : Prisma.GetScalarType<TArgs[P], Prisma.PasswordHistoryGroupByOutputType[P]>
    }
    > : InputErrors, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.SubsetIntersection<TArgs, Prisma.PasswordHistoryGroupByArgs, OrderByArg> & InputErrors>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('PasswordHistory', `${endpoint}/passwordHistory/groupBy`, args, options, fetch);
}

export function useCountPasswordHistory<TArgs extends Prisma.PasswordHistoryCountArgs, TQueryFnData = TArgs extends { select: any; } ? TArgs['select'] extends true ? number : Prisma.GetScalarType<TArgs['select'], Prisma.PasswordHistoryCountAggregateOutputType> : number, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.PasswordHistoryCountArgs>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('PasswordHistory', `${endpoint}/passwordHistory/count`, args, options, fetch);
}

export function useSuspenseCountPasswordHistory<TArgs extends Prisma.PasswordHistoryCountArgs, TQueryFnData = TArgs extends { select: any; } ? TArgs['select'] extends true ? number : Prisma.GetScalarType<TArgs['select'], Prisma.PasswordHistoryCountAggregateOutputType> : number, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.PasswordHistoryCountArgs>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('PasswordHistory', `${endpoint}/passwordHistory/count`, args, options, fetch);
}

export function useCheckPasswordHistory<TError = DefaultError>(args: { operation: PolicyCrudKind; where?: { id?: string; userId?: string; hash?: string }; }, options?: (Omit<UseQueryOptions<boolean, TError, boolean>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<boolean, boolean, TError>('PasswordHistory', `${endpoint}/passwordHistory/check`, args, options, fetch);
}
