/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */

import type { Prisma, PendingAuth } from "@prisma/client";
import type { UseMutationOptions, UseQueryOptions, UseInfiniteQueryOptions, InfiniteData } from '@tanstack/react-query';
import { getHooksContext } from '@zenstackhq/tanstack-query/runtime-v5/react';
import { useModelQuery, useInfiniteModelQuery, useModelMutation } from '@zenstackhq/tanstack-query/runtime-v5/react';
import type { PickEnumerable, CheckSelect, QueryError, ExtraQueryOptions, ExtraMutationOptions } from '@zenstackhq/tanstack-query/runtime-v5';
import type { PolicyCrudKind } from '@zenstackhq/runtime'
import metadata from './__model_meta';
type DefaultError = QueryError;
import { useSuspenseModelQuery, useSuspenseInfiniteModelQuery } from '@zenstackhq/tanstack-query/runtime-v5/react';
import type { UseSuspenseQueryOptions, UseSuspenseInfiniteQueryOptions } from '@tanstack/react-query';

export function useCreatePendingAuth(options?: Omit<(UseMutationOptions<(PendingAuth | undefined), DefaultError, Prisma.PendingAuthCreateArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.PendingAuthCreateArgs, DefaultError, PendingAuth, true>('PendingAuth', 'POST', `${endpoint}/pendingAuth/create`, metadata, options, fetch, true)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.PendingAuthCreateArgs>(
            args: Prisma.SelectSubset<T, Prisma.PendingAuthCreateArgs>,
            options?: Omit<(UseMutationOptions<(CheckSelect<T, PendingAuth, Prisma.PendingAuthGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.PendingAuthCreateArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as (CheckSelect<T, PendingAuth, Prisma.PendingAuthGetPayload<T>> | undefined);
        },
    };
    return mutation;
}

export function useCreateManyPendingAuth(options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.PendingAuthCreateManyArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.PendingAuthCreateManyArgs, DefaultError, Prisma.BatchPayload, false>('PendingAuth', 'POST', `${endpoint}/pendingAuth/createMany`, metadata, options, fetch, false)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.PendingAuthCreateManyArgs>(
            args: Prisma.SelectSubset<T, Prisma.PendingAuthCreateManyArgs>,
            options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.SelectSubset<T, Prisma.PendingAuthCreateManyArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as Prisma.BatchPayload;
        },
    };
    return mutation;
}

export function useFindManyPendingAuth<TArgs extends Prisma.PendingAuthFindManyArgs, TQueryFnData = Array<Prisma.PendingAuthGetPayload<TArgs> & { $optimistic?: boolean }>, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.PendingAuthFindManyArgs>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('PendingAuth', `${endpoint}/pendingAuth/findMany`, args, options, fetch);
}

export function useInfiniteFindManyPendingAuth<TArgs extends Prisma.PendingAuthFindManyArgs, TQueryFnData = Array<Prisma.PendingAuthGetPayload<TArgs>>, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.PendingAuthFindManyArgs>, options?: Omit<UseInfiniteQueryOptions<TQueryFnData, TError, InfiniteData<TData>>, 'queryKey' | 'initialPageParam'>) {
    options = options ?? { getNextPageParam: () => null };
    const { endpoint, fetch } = getHooksContext();
    return useInfiniteModelQuery<TQueryFnData, TData, TError>('PendingAuth', `${endpoint}/pendingAuth/findMany`, args, options, fetch);
}

export function useSuspenseFindManyPendingAuth<TArgs extends Prisma.PendingAuthFindManyArgs, TQueryFnData = Array<Prisma.PendingAuthGetPayload<TArgs> & { $optimistic?: boolean }>, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.PendingAuthFindManyArgs>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('PendingAuth', `${endpoint}/pendingAuth/findMany`, args, options, fetch);
}

export function useSuspenseInfiniteFindManyPendingAuth<TArgs extends Prisma.PendingAuthFindManyArgs, TQueryFnData = Array<Prisma.PendingAuthGetPayload<TArgs>>, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.PendingAuthFindManyArgs>, options?: Omit<UseSuspenseInfiniteQueryOptions<TQueryFnData, TError, InfiniteData<TData>>, 'queryKey' | 'initialPageParam'>) {
    options = options ?? { getNextPageParam: () => null };
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseInfiniteModelQuery<TQueryFnData, TData, TError>('PendingAuth', `${endpoint}/pendingAuth/findMany`, args, options, fetch);
}

export function useFindUniquePendingAuth<TArgs extends Prisma.PendingAuthFindUniqueArgs, TQueryFnData = Prisma.PendingAuthGetPayload<TArgs> & { $optimistic?: boolean }, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.PendingAuthFindUniqueArgs>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('PendingAuth', `${endpoint}/pendingAuth/findUnique`, args, options, fetch);
}

export function useSuspenseFindUniquePendingAuth<TArgs extends Prisma.PendingAuthFindUniqueArgs, TQueryFnData = Prisma.PendingAuthGetPayload<TArgs> & { $optimistic?: boolean }, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.PendingAuthFindUniqueArgs>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('PendingAuth', `${endpoint}/pendingAuth/findUnique`, args, options, fetch);
}

export function useFindFirstPendingAuth<TArgs extends Prisma.PendingAuthFindFirstArgs, TQueryFnData = Prisma.PendingAuthGetPayload<TArgs> & { $optimistic?: boolean }, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.PendingAuthFindFirstArgs>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('PendingAuth', `${endpoint}/pendingAuth/findFirst`, args, options, fetch);
}

export function useSuspenseFindFirstPendingAuth<TArgs extends Prisma.PendingAuthFindFirstArgs, TQueryFnData = Prisma.PendingAuthGetPayload<TArgs> & { $optimistic?: boolean }, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.PendingAuthFindFirstArgs>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('PendingAuth', `${endpoint}/pendingAuth/findFirst`, args, options, fetch);
}

export function useUpdatePendingAuth(options?: Omit<(UseMutationOptions<(PendingAuth | undefined), DefaultError, Prisma.PendingAuthUpdateArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.PendingAuthUpdateArgs, DefaultError, PendingAuth, true>('PendingAuth', 'PUT', `${endpoint}/pendingAuth/update`, metadata, options, fetch, true)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.PendingAuthUpdateArgs>(
            args: Prisma.SelectSubset<T, Prisma.PendingAuthUpdateArgs>,
            options?: Omit<(UseMutationOptions<(CheckSelect<T, PendingAuth, Prisma.PendingAuthGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.PendingAuthUpdateArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as (CheckSelect<T, PendingAuth, Prisma.PendingAuthGetPayload<T>> | undefined);
        },
    };
    return mutation;
}

export function useUpdateManyPendingAuth(options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.PendingAuthUpdateManyArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.PendingAuthUpdateManyArgs, DefaultError, Prisma.BatchPayload, false>('PendingAuth', 'PUT', `${endpoint}/pendingAuth/updateMany`, metadata, options, fetch, false)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.PendingAuthUpdateManyArgs>(
            args: Prisma.SelectSubset<T, Prisma.PendingAuthUpdateManyArgs>,
            options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.SelectSubset<T, Prisma.PendingAuthUpdateManyArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as Prisma.BatchPayload;
        },
    };
    return mutation;
}

export function useUpsertPendingAuth(options?: Omit<(UseMutationOptions<(PendingAuth | undefined), DefaultError, Prisma.PendingAuthUpsertArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.PendingAuthUpsertArgs, DefaultError, PendingAuth, true>('PendingAuth', 'POST', `${endpoint}/pendingAuth/upsert`, metadata, options, fetch, true)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.PendingAuthUpsertArgs>(
            args: Prisma.SelectSubset<T, Prisma.PendingAuthUpsertArgs>,
            options?: Omit<(UseMutationOptions<(CheckSelect<T, PendingAuth, Prisma.PendingAuthGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.PendingAuthUpsertArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as (CheckSelect<T, PendingAuth, Prisma.PendingAuthGetPayload<T>> | undefined);
        },
    };
    return mutation;
}

export function useDeletePendingAuth(options?: Omit<(UseMutationOptions<(PendingAuth | undefined), DefaultError, Prisma.PendingAuthDeleteArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.PendingAuthDeleteArgs, DefaultError, PendingAuth, true>('PendingAuth', 'DELETE', `${endpoint}/pendingAuth/delete`, metadata, options, fetch, true)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.PendingAuthDeleteArgs>(
            args: Prisma.SelectSubset<T, Prisma.PendingAuthDeleteArgs>,
            options?: Omit<(UseMutationOptions<(CheckSelect<T, PendingAuth, Prisma.PendingAuthGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.PendingAuthDeleteArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as (CheckSelect<T, PendingAuth, Prisma.PendingAuthGetPayload<T>> | undefined);
        },
    };
    return mutation;
}

export function useDeleteManyPendingAuth(options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.PendingAuthDeleteManyArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.PendingAuthDeleteManyArgs, DefaultError, Prisma.BatchPayload, false>('PendingAuth', 'DELETE', `${endpoint}/pendingAuth/deleteMany`, metadata, options, fetch, false)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.PendingAuthDeleteManyArgs>(
            args: Prisma.SelectSubset<T, Prisma.PendingAuthDeleteManyArgs>,
            options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.SelectSubset<T, Prisma.PendingAuthDeleteManyArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as Prisma.BatchPayload;
        },
    };
    return mutation;
}

export function useAggregatePendingAuth<TArgs extends Prisma.PendingAuthAggregateArgs, TQueryFnData = Prisma.GetPendingAuthAggregateType<TArgs>, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.PendingAuthAggregateArgs>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('PendingAuth', `${endpoint}/pendingAuth/aggregate`, args, options, fetch);
}

export function useSuspenseAggregatePendingAuth<TArgs extends Prisma.PendingAuthAggregateArgs, TQueryFnData = Prisma.GetPendingAuthAggregateType<TArgs>, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.PendingAuthAggregateArgs>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('PendingAuth', `${endpoint}/pendingAuth/aggregate`, args, options, fetch);
}

export function useGroupByPendingAuth<TArgs extends Prisma.PendingAuthGroupByArgs, HasSelectOrTake extends Prisma.Or<Prisma.Extends<'skip', Prisma.Keys<TArgs>>, Prisma.Extends<'take', Prisma.Keys<TArgs>>>, OrderByArg extends Prisma.True extends HasSelectOrTake ? { orderBy: Prisma.PendingAuthGroupByArgs['orderBy'] } : { orderBy?: Prisma.PendingAuthGroupByArgs['orderBy'] }, OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<TArgs['orderBy']>>>, ByFields extends Prisma.MaybeTupleToUnion<TArgs['by']>, ByValid extends Prisma.Has<ByFields, OrderFields>, HavingFields extends Prisma.GetHavingFields<TArgs['having']>, HavingValid extends Prisma.Has<ByFields, HavingFields>, ByEmpty extends TArgs['by'] extends never[] ? Prisma.True : Prisma.False, InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
        ? never
        : P extends string
        ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
        : [
            Error,
            'Field ',
            P,
            ` in "having" needs to be provided in "by"`,
        ]
    }[HavingFields]
    : 'take' extends Prisma.Keys<TArgs>
    ? 'orderBy' extends Prisma.Keys<TArgs>
    ? ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields]
    : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<TArgs>
    ? 'orderBy' extends Prisma.Keys<TArgs>
    ? ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields]
    : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields], TQueryFnData = {} extends InputErrors ?
    Array<PickEnumerable<Prisma.PendingAuthGroupByOutputType, TArgs['by']> &
    {
        [P in ((keyof TArgs) & (keyof Prisma.PendingAuthGroupByOutputType))]: P extends '_count'
        ? TArgs[P] extends boolean
        ? number
        : Prisma.GetScalarType<TArgs[P], Prisma.PendingAuthGroupByOutputType[P]>
        : Prisma.GetScalarType<TArgs[P], Prisma.PendingAuthGroupByOutputType[P]>
    }
    > : InputErrors, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.SubsetIntersection<TArgs, Prisma.PendingAuthGroupByArgs, OrderByArg> & InputErrors>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('PendingAuth', `${endpoint}/pendingAuth/groupBy`, args, options, fetch);
}

export function useSuspenseGroupByPendingAuth<TArgs extends Prisma.PendingAuthGroupByArgs, HasSelectOrTake extends Prisma.Or<Prisma.Extends<'skip', Prisma.Keys<TArgs>>, Prisma.Extends<'take', Prisma.Keys<TArgs>>>, OrderByArg extends Prisma.True extends HasSelectOrTake ? { orderBy: Prisma.PendingAuthGroupByArgs['orderBy'] } : { orderBy?: Prisma.PendingAuthGroupByArgs['orderBy'] }, OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<TArgs['orderBy']>>>, ByFields extends Prisma.MaybeTupleToUnion<TArgs['by']>, ByValid extends Prisma.Has<ByFields, OrderFields>, HavingFields extends Prisma.GetHavingFields<TArgs['having']>, HavingValid extends Prisma.Has<ByFields, HavingFields>, ByEmpty extends TArgs['by'] extends never[] ? Prisma.True : Prisma.False, InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
        ? never
        : P extends string
        ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
        : [
            Error,
            'Field ',
            P,
            ` in "having" needs to be provided in "by"`,
        ]
    }[HavingFields]
    : 'take' extends Prisma.Keys<TArgs>
    ? 'orderBy' extends Prisma.Keys<TArgs>
    ? ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields]
    : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<TArgs>
    ? 'orderBy' extends Prisma.Keys<TArgs>
    ? ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields]
    : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields], TQueryFnData = {} extends InputErrors ?
    Array<PickEnumerable<Prisma.PendingAuthGroupByOutputType, TArgs['by']> &
    {
        [P in ((keyof TArgs) & (keyof Prisma.PendingAuthGroupByOutputType))]: P extends '_count'
        ? TArgs[P] extends boolean
        ? number
        : Prisma.GetScalarType<TArgs[P], Prisma.PendingAuthGroupByOutputType[P]>
        : Prisma.GetScalarType<TArgs[P], Prisma.PendingAuthGroupByOutputType[P]>
    }
    > : InputErrors, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.SubsetIntersection<TArgs, Prisma.PendingAuthGroupByArgs, OrderByArg> & InputErrors>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('PendingAuth', `${endpoint}/pendingAuth/groupBy`, args, options, fetch);
}

export function useCountPendingAuth<TArgs extends Prisma.PendingAuthCountArgs, TQueryFnData = TArgs extends { select: any; } ? TArgs['select'] extends true ? number : Prisma.GetScalarType<TArgs['select'], Prisma.PendingAuthCountAggregateOutputType> : number, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.PendingAuthCountArgs>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('PendingAuth', `${endpoint}/pendingAuth/count`, args, options, fetch);
}

export function useSuspenseCountPendingAuth<TArgs extends Prisma.PendingAuthCountArgs, TQueryFnData = TArgs extends { select: any; } ? TArgs['select'] extends true ? number : Prisma.GetScalarType<TArgs['select'], Prisma.PendingAuthCountAggregateOutputType> : number, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.PendingAuthCountArgs>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('PendingAuth', `${endpoint}/pendingAuth/count`, args, options, fetch);
}
import type { PendingAuthStatus } from '@prisma/client';

export function useCheckPendingAuth<TError = DefaultError>(args: { operation: PolicyCrudKind; where?: { id?: string; email?: string; verifierHash?: string; linkTokenHash?: string; codeHash?: string; status?: PendingAuthStatus; attempts?: number; callbackUrl?: string; requestIp?: string; requestUserAgent?: string }; }, options?: (Omit<UseQueryOptions<boolean, TError, boolean>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<boolean, boolean, TError>('PendingAuth', `${endpoint}/pendingAuth/check`, args, options, fetch);
}
