/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */

import type { Prisma, ReviewRequest } from "@prisma/client";
import type { UseMutationOptions, UseQueryOptions, UseInfiniteQueryOptions, InfiniteData } from '@tanstack/react-query';
import { getHooksContext } from '@zenstackhq/tanstack-query/runtime-v5/react';
import { useModelQuery, useInfiniteModelQuery, useModelMutation } from '@zenstackhq/tanstack-query/runtime-v5/react';
import type { PickEnumerable, CheckSelect, QueryError, ExtraQueryOptions, ExtraMutationOptions } from '@zenstackhq/tanstack-query/runtime-v5';
import type { PolicyCrudKind } from '@zenstackhq/runtime'
import metadata from './__model_meta';
type DefaultError = QueryError;
import { useSuspenseModelQuery, useSuspenseInfiniteModelQuery } from '@zenstackhq/tanstack-query/runtime-v5/react';
import type { UseSuspenseQueryOptions, UseSuspenseInfiniteQueryOptions } from '@tanstack/react-query';

export function useCreateReviewRequest(options?: Omit<(UseMutationOptions<(ReviewRequest | undefined), DefaultError, Prisma.ReviewRequestCreateArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.ReviewRequestCreateArgs, DefaultError, ReviewRequest, true>('ReviewRequest', 'POST', `${endpoint}/reviewRequest/create`, metadata, options, fetch, true)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.ReviewRequestCreateArgs>(
            args: Prisma.SelectSubset<T, Prisma.ReviewRequestCreateArgs>,
            options?: Omit<(UseMutationOptions<(CheckSelect<T, ReviewRequest, Prisma.ReviewRequestGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.ReviewRequestCreateArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as (CheckSelect<T, ReviewRequest, Prisma.ReviewRequestGetPayload<T>> | undefined);
        },
    };
    return mutation;
}

export function useCreateManyReviewRequest(options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.ReviewRequestCreateManyArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.ReviewRequestCreateManyArgs, DefaultError, Prisma.BatchPayload, false>('ReviewRequest', 'POST', `${endpoint}/reviewRequest/createMany`, metadata, options, fetch, false)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.ReviewRequestCreateManyArgs>(
            args: Prisma.SelectSubset<T, Prisma.ReviewRequestCreateManyArgs>,
            options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.SelectSubset<T, Prisma.ReviewRequestCreateManyArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as Prisma.BatchPayload;
        },
    };
    return mutation;
}

export function useFindManyReviewRequest<TArgs extends Prisma.ReviewRequestFindManyArgs, TQueryFnData = Array<Prisma.ReviewRequestGetPayload<TArgs> & { $optimistic?: boolean }>, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.ReviewRequestFindManyArgs>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('ReviewRequest', `${endpoint}/reviewRequest/findMany`, args, options, fetch);
}

export function useInfiniteFindManyReviewRequest<TArgs extends Prisma.ReviewRequestFindManyArgs, TQueryFnData = Array<Prisma.ReviewRequestGetPayload<TArgs>>, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.ReviewRequestFindManyArgs>, options?: Omit<UseInfiniteQueryOptions<TQueryFnData, TError, InfiniteData<TData>>, 'queryKey' | 'initialPageParam'>) {
    options = options ?? { getNextPageParam: () => null };
    const { endpoint, fetch } = getHooksContext();
    return useInfiniteModelQuery<TQueryFnData, TData, TError>('ReviewRequest', `${endpoint}/reviewRequest/findMany`, args, options, fetch);
}

export function useSuspenseFindManyReviewRequest<TArgs extends Prisma.ReviewRequestFindManyArgs, TQueryFnData = Array<Prisma.ReviewRequestGetPayload<TArgs> & { $optimistic?: boolean }>, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.ReviewRequestFindManyArgs>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('ReviewRequest', `${endpoint}/reviewRequest/findMany`, args, options, fetch);
}

export function useSuspenseInfiniteFindManyReviewRequest<TArgs extends Prisma.ReviewRequestFindManyArgs, TQueryFnData = Array<Prisma.ReviewRequestGetPayload<TArgs>>, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.ReviewRequestFindManyArgs>, options?: Omit<UseSuspenseInfiniteQueryOptions<TQueryFnData, TError, InfiniteData<TData>>, 'queryKey' | 'initialPageParam'>) {
    options = options ?? { getNextPageParam: () => null };
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseInfiniteModelQuery<TQueryFnData, TData, TError>('ReviewRequest', `${endpoint}/reviewRequest/findMany`, args, options, fetch);
}

export function useFindUniqueReviewRequest<TArgs extends Prisma.ReviewRequestFindUniqueArgs, TQueryFnData = Prisma.ReviewRequestGetPayload<TArgs> & { $optimistic?: boolean }, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.ReviewRequestFindUniqueArgs>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('ReviewRequest', `${endpoint}/reviewRequest/findUnique`, args, options, fetch);
}

export function useSuspenseFindUniqueReviewRequest<TArgs extends Prisma.ReviewRequestFindUniqueArgs, TQueryFnData = Prisma.ReviewRequestGetPayload<TArgs> & { $optimistic?: boolean }, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.ReviewRequestFindUniqueArgs>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('ReviewRequest', `${endpoint}/reviewRequest/findUnique`, args, options, fetch);
}

export function useFindFirstReviewRequest<TArgs extends Prisma.ReviewRequestFindFirstArgs, TQueryFnData = Prisma.ReviewRequestGetPayload<TArgs> & { $optimistic?: boolean }, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.ReviewRequestFindFirstArgs>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('ReviewRequest', `${endpoint}/reviewRequest/findFirst`, args, options, fetch);
}

export function useSuspenseFindFirstReviewRequest<TArgs extends Prisma.ReviewRequestFindFirstArgs, TQueryFnData = Prisma.ReviewRequestGetPayload<TArgs> & { $optimistic?: boolean }, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.ReviewRequestFindFirstArgs>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('ReviewRequest', `${endpoint}/reviewRequest/findFirst`, args, options, fetch);
}

export function useUpdateReviewRequest(options?: Omit<(UseMutationOptions<(ReviewRequest | undefined), DefaultError, Prisma.ReviewRequestUpdateArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.ReviewRequestUpdateArgs, DefaultError, ReviewRequest, true>('ReviewRequest', 'PUT', `${endpoint}/reviewRequest/update`, metadata, options, fetch, true)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.ReviewRequestUpdateArgs>(
            args: Prisma.SelectSubset<T, Prisma.ReviewRequestUpdateArgs>,
            options?: Omit<(UseMutationOptions<(CheckSelect<T, ReviewRequest, Prisma.ReviewRequestGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.ReviewRequestUpdateArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as (CheckSelect<T, ReviewRequest, Prisma.ReviewRequestGetPayload<T>> | undefined);
        },
    };
    return mutation;
}

export function useUpdateManyReviewRequest(options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.ReviewRequestUpdateManyArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.ReviewRequestUpdateManyArgs, DefaultError, Prisma.BatchPayload, false>('ReviewRequest', 'PUT', `${endpoint}/reviewRequest/updateMany`, metadata, options, fetch, false)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.ReviewRequestUpdateManyArgs>(
            args: Prisma.SelectSubset<T, Prisma.ReviewRequestUpdateManyArgs>,
            options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.SelectSubset<T, Prisma.ReviewRequestUpdateManyArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as Prisma.BatchPayload;
        },
    };
    return mutation;
}

export function useUpsertReviewRequest(options?: Omit<(UseMutationOptions<(ReviewRequest | undefined), DefaultError, Prisma.ReviewRequestUpsertArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.ReviewRequestUpsertArgs, DefaultError, ReviewRequest, true>('ReviewRequest', 'POST', `${endpoint}/reviewRequest/upsert`, metadata, options, fetch, true)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.ReviewRequestUpsertArgs>(
            args: Prisma.SelectSubset<T, Prisma.ReviewRequestUpsertArgs>,
            options?: Omit<(UseMutationOptions<(CheckSelect<T, ReviewRequest, Prisma.ReviewRequestGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.ReviewRequestUpsertArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as (CheckSelect<T, ReviewRequest, Prisma.ReviewRequestGetPayload<T>> | undefined);
        },
    };
    return mutation;
}

export function useDeleteReviewRequest(options?: Omit<(UseMutationOptions<(ReviewRequest | undefined), DefaultError, Prisma.ReviewRequestDeleteArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.ReviewRequestDeleteArgs, DefaultError, ReviewRequest, true>('ReviewRequest', 'DELETE', `${endpoint}/reviewRequest/delete`, metadata, options, fetch, true)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.ReviewRequestDeleteArgs>(
            args: Prisma.SelectSubset<T, Prisma.ReviewRequestDeleteArgs>,
            options?: Omit<(UseMutationOptions<(CheckSelect<T, ReviewRequest, Prisma.ReviewRequestGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.ReviewRequestDeleteArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as (CheckSelect<T, ReviewRequest, Prisma.ReviewRequestGetPayload<T>> | undefined);
        },
    };
    return mutation;
}

export function useDeleteManyReviewRequest(options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.ReviewRequestDeleteManyArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.ReviewRequestDeleteManyArgs, DefaultError, Prisma.BatchPayload, false>('ReviewRequest', 'DELETE', `${endpoint}/reviewRequest/deleteMany`, metadata, options, fetch, false)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.ReviewRequestDeleteManyArgs>(
            args: Prisma.SelectSubset<T, Prisma.ReviewRequestDeleteManyArgs>,
            options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.SelectSubset<T, Prisma.ReviewRequestDeleteManyArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as Prisma.BatchPayload;
        },
    };
    return mutation;
}

export function useAggregateReviewRequest<TArgs extends Prisma.ReviewRequestAggregateArgs, TQueryFnData = Prisma.GetReviewRequestAggregateType<TArgs>, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.ReviewRequestAggregateArgs>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('ReviewRequest', `${endpoint}/reviewRequest/aggregate`, args, options, fetch);
}

export function useSuspenseAggregateReviewRequest<TArgs extends Prisma.ReviewRequestAggregateArgs, TQueryFnData = Prisma.GetReviewRequestAggregateType<TArgs>, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.ReviewRequestAggregateArgs>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('ReviewRequest', `${endpoint}/reviewRequest/aggregate`, args, options, fetch);
}

export function useGroupByReviewRequest<TArgs extends Prisma.ReviewRequestGroupByArgs, HasSelectOrTake extends Prisma.Or<Prisma.Extends<'skip', Prisma.Keys<TArgs>>, Prisma.Extends<'take', Prisma.Keys<TArgs>>>, OrderByArg extends Prisma.True extends HasSelectOrTake ? { orderBy: Prisma.ReviewRequestGroupByArgs['orderBy'] } : { orderBy?: Prisma.ReviewRequestGroupByArgs['orderBy'] }, OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<TArgs['orderBy']>>>, ByFields extends Prisma.MaybeTupleToUnion<TArgs['by']>, ByValid extends Prisma.Has<ByFields, OrderFields>, HavingFields extends Prisma.GetHavingFields<TArgs['having']>, HavingValid extends Prisma.Has<ByFields, HavingFields>, ByEmpty extends TArgs['by'] extends never[] ? Prisma.True : Prisma.False, InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
        ? never
        : P extends string
        ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
        : [
            Error,
            'Field ',
            P,
            ` in "having" needs to be provided in "by"`,
        ]
    }[HavingFields]
    : 'take' extends Prisma.Keys<TArgs>
    ? 'orderBy' extends Prisma.Keys<TArgs>
    ? ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields]
    : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<TArgs>
    ? 'orderBy' extends Prisma.Keys<TArgs>
    ? ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields]
    : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields], TQueryFnData = {} extends InputErrors ?
    Array<PickEnumerable<Prisma.ReviewRequestGroupByOutputType, TArgs['by']> &
    {
        [P in ((keyof TArgs) & (keyof Prisma.ReviewRequestGroupByOutputType))]: P extends '_count'
        ? TArgs[P] extends boolean
        ? number
        : Prisma.GetScalarType<TArgs[P], Prisma.ReviewRequestGroupByOutputType[P]>
        : Prisma.GetScalarType<TArgs[P], Prisma.ReviewRequestGroupByOutputType[P]>
    }
    > : InputErrors, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.SubsetIntersection<TArgs, Prisma.ReviewRequestGroupByArgs, OrderByArg> & InputErrors>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('ReviewRequest', `${endpoint}/reviewRequest/groupBy`, args, options, fetch);
}

export function useSuspenseGroupByReviewRequest<TArgs extends Prisma.ReviewRequestGroupByArgs, HasSelectOrTake extends Prisma.Or<Prisma.Extends<'skip', Prisma.Keys<TArgs>>, Prisma.Extends<'take', Prisma.Keys<TArgs>>>, OrderByArg extends Prisma.True extends HasSelectOrTake ? { orderBy: Prisma.ReviewRequestGroupByArgs['orderBy'] } : { orderBy?: Prisma.ReviewRequestGroupByArgs['orderBy'] }, OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<TArgs['orderBy']>>>, ByFields extends Prisma.MaybeTupleToUnion<TArgs['by']>, ByValid extends Prisma.Has<ByFields, OrderFields>, HavingFields extends Prisma.GetHavingFields<TArgs['having']>, HavingValid extends Prisma.Has<ByFields, HavingFields>, ByEmpty extends TArgs['by'] extends never[] ? Prisma.True : Prisma.False, InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
        ? never
        : P extends string
        ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
        : [
            Error,
            'Field ',
            P,
            ` in "having" needs to be provided in "by"`,
        ]
    }[HavingFields]
    : 'take' extends Prisma.Keys<TArgs>
    ? 'orderBy' extends Prisma.Keys<TArgs>
    ? ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields]
    : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<TArgs>
    ? 'orderBy' extends Prisma.Keys<TArgs>
    ? ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields]
    : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields], TQueryFnData = {} extends InputErrors ?
    Array<PickEnumerable<Prisma.ReviewRequestGroupByOutputType, TArgs['by']> &
    {
        [P in ((keyof TArgs) & (keyof Prisma.ReviewRequestGroupByOutputType))]: P extends '_count'
        ? TArgs[P] extends boolean
        ? number
        : Prisma.GetScalarType<TArgs[P], Prisma.ReviewRequestGroupByOutputType[P]>
        : Prisma.GetScalarType<TArgs[P], Prisma.ReviewRequestGroupByOutputType[P]>
    }
    > : InputErrors, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.SubsetIntersection<TArgs, Prisma.ReviewRequestGroupByArgs, OrderByArg> & InputErrors>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('ReviewRequest', `${endpoint}/reviewRequest/groupBy`, args, options, fetch);
}

export function useCountReviewRequest<TArgs extends Prisma.ReviewRequestCountArgs, TQueryFnData = TArgs extends { select: any; } ? TArgs['select'] extends true ? number : Prisma.GetScalarType<TArgs['select'], Prisma.ReviewRequestCountAggregateOutputType> : number, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.ReviewRequestCountArgs>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('ReviewRequest', `${endpoint}/reviewRequest/count`, args, options, fetch);
}

export function useSuspenseCountReviewRequest<TArgs extends Prisma.ReviewRequestCountArgs, TQueryFnData = TArgs extends { select: any; } ? TArgs['select'] extends true ? number : Prisma.GetScalarType<TArgs['select'], Prisma.ReviewRequestCountAggregateOutputType> : number, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.ReviewRequestCountArgs>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('ReviewRequest', `${endpoint}/reviewRequest/count`, args, options, fetch);
}
import type { ReviewEntityType, ReviewStatus } from '@prisma/client';

export function useCheckReviewRequest<TError = DefaultError>(args: { operation: PolicyCrudKind; where?: { id?: string; projectId?: number; entityType?: ReviewEntityType; entityId?: number; requestedByUserId?: string; assigneeUserId?: string; assigneeRoleId?: number; fromStateId?: number; toStateId?: number; status?: ReviewStatus; decisionComment?: string; decidedByUserId?: string; isDeleted?: boolean }; }, options?: (Omit<UseQueryOptions<boolean, TError, boolean>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<boolean, boolean, TError>('ReviewRequest', `${endpoint}/reviewRequest/check`, args, options, fetch);
}
