/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */

import type { Prisma, ScimToken } from "@prisma/client";
import type { UseMutationOptions, UseQueryOptions, UseInfiniteQueryOptions, InfiniteData } from '@tanstack/react-query';
import { getHooksContext } from '@zenstackhq/tanstack-query/runtime-v5/react';
import { useModelQuery, useInfiniteModelQuery, useModelMutation } from '@zenstackhq/tanstack-query/runtime-v5/react';
import type { PickEnumerable, CheckSelect, QueryError, ExtraQueryOptions, ExtraMutationOptions } from '@zenstackhq/tanstack-query/runtime-v5';
import type { PolicyCrudKind } from '@zenstackhq/runtime'
import metadata from './__model_meta';
type DefaultError = QueryError;
import { useSuspenseModelQuery, useSuspenseInfiniteModelQuery } from '@zenstackhq/tanstack-query/runtime-v5/react';
import type { UseSuspenseQueryOptions, UseSuspenseInfiniteQueryOptions } from '@tanstack/react-query';

export function useCreateScimToken(options?: Omit<(UseMutationOptions<(ScimToken | undefined), DefaultError, Prisma.ScimTokenCreateArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.ScimTokenCreateArgs, DefaultError, ScimToken, true>('ScimToken', 'POST', `${endpoint}/scimToken/create`, metadata, options, fetch, true)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.ScimTokenCreateArgs>(
            args: Prisma.SelectSubset<T, Prisma.ScimTokenCreateArgs>,
            options?: Omit<(UseMutationOptions<(CheckSelect<T, ScimToken, Prisma.ScimTokenGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.ScimTokenCreateArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as (CheckSelect<T, ScimToken, Prisma.ScimTokenGetPayload<T>> | undefined);
        },
    };
    return mutation;
}

export function useCreateManyScimToken(options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.ScimTokenCreateManyArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.ScimTokenCreateManyArgs, DefaultError, Prisma.BatchPayload, false>('ScimToken', 'POST', `${endpoint}/scimToken/createMany`, metadata, options, fetch, false)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.ScimTokenCreateManyArgs>(
            args: Prisma.SelectSubset<T, Prisma.ScimTokenCreateManyArgs>,
            options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.SelectSubset<T, Prisma.ScimTokenCreateManyArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as Prisma.BatchPayload;
        },
    };
    return mutation;
}

export function useFindManyScimToken<TArgs extends Prisma.ScimTokenFindManyArgs, TQueryFnData = Array<Prisma.ScimTokenGetPayload<TArgs> & { $optimistic?: boolean }>, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.ScimTokenFindManyArgs>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('ScimToken', `${endpoint}/scimToken/findMany`, args, options, fetch);
}

export function useInfiniteFindManyScimToken<TArgs extends Prisma.ScimTokenFindManyArgs, TQueryFnData = Array<Prisma.ScimTokenGetPayload<TArgs>>, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.ScimTokenFindManyArgs>, options?: Omit<UseInfiniteQueryOptions<TQueryFnData, TError, InfiniteData<TData>>, 'queryKey' | 'initialPageParam'>) {
    options = options ?? { getNextPageParam: () => null };
    const { endpoint, fetch } = getHooksContext();
    return useInfiniteModelQuery<TQueryFnData, TData, TError>('ScimToken', `${endpoint}/scimToken/findMany`, args, options, fetch);
}

export function useSuspenseFindManyScimToken<TArgs extends Prisma.ScimTokenFindManyArgs, TQueryFnData = Array<Prisma.ScimTokenGetPayload<TArgs> & { $optimistic?: boolean }>, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.ScimTokenFindManyArgs>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('ScimToken', `${endpoint}/scimToken/findMany`, args, options, fetch);
}

export function useSuspenseInfiniteFindManyScimToken<TArgs extends Prisma.ScimTokenFindManyArgs, TQueryFnData = Array<Prisma.ScimTokenGetPayload<TArgs>>, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.ScimTokenFindManyArgs>, options?: Omit<UseSuspenseInfiniteQueryOptions<TQueryFnData, TError, InfiniteData<TData>>, 'queryKey' | 'initialPageParam'>) {
    options = options ?? { getNextPageParam: () => null };
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseInfiniteModelQuery<TQueryFnData, TData, TError>('ScimToken', `${endpoint}/scimToken/findMany`, args, options, fetch);
}

export function useFindUniqueScimToken<TArgs extends Prisma.ScimTokenFindUniqueArgs, TQueryFnData = Prisma.ScimTokenGetPayload<TArgs> & { $optimistic?: boolean }, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.ScimTokenFindUniqueArgs>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('ScimToken', `${endpoint}/scimToken/findUnique`, args, options, fetch);
}

export function useSuspenseFindUniqueScimToken<TArgs extends Prisma.ScimTokenFindUniqueArgs, TQueryFnData = Prisma.ScimTokenGetPayload<TArgs> & { $optimistic?: boolean }, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.ScimTokenFindUniqueArgs>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('ScimToken', `${endpoint}/scimToken/findUnique`, args, options, fetch);
}

export function useFindFirstScimToken<TArgs extends Prisma.ScimTokenFindFirstArgs, TQueryFnData = Prisma.ScimTokenGetPayload<TArgs> & { $optimistic?: boolean }, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.ScimTokenFindFirstArgs>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('ScimToken', `${endpoint}/scimToken/findFirst`, args, options, fetch);
}

export function useSuspenseFindFirstScimToken<TArgs extends Prisma.ScimTokenFindFirstArgs, TQueryFnData = Prisma.ScimTokenGetPayload<TArgs> & { $optimistic?: boolean }, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.ScimTokenFindFirstArgs>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('ScimToken', `${endpoint}/scimToken/findFirst`, args, options, fetch);
}

export function useUpdateScimToken(options?: Omit<(UseMutationOptions<(ScimToken | undefined), DefaultError, Prisma.ScimTokenUpdateArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.ScimTokenUpdateArgs, DefaultError, ScimToken, true>('ScimToken', 'PUT', `${endpoint}/scimToken/update`, metadata, options, fetch, true)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.ScimTokenUpdateArgs>(
            args: Prisma.SelectSubset<T, Prisma.ScimTokenUpdateArgs>,
            options?: Omit<(UseMutationOptions<(CheckSelect<T, ScimToken, Prisma.ScimTokenGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.ScimTokenUpdateArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as (CheckSelect<T, ScimToken, Prisma.ScimTokenGetPayload<T>> | undefined);
        },
    };
    return mutation;
}

export function useUpdateManyScimToken(options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.ScimTokenUpdateManyArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.ScimTokenUpdateManyArgs, DefaultError, Prisma.BatchPayload, false>('ScimToken', 'PUT', `${endpoint}/scimToken/updateMany`, metadata, options, fetch, false)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.ScimTokenUpdateManyArgs>(
            args: Prisma.SelectSubset<T, Prisma.ScimTokenUpdateManyArgs>,
            options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.SelectSubset<T, Prisma.ScimTokenUpdateManyArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as Prisma.BatchPayload;
        },
    };
    return mutation;
}

export function useUpsertScimToken(options?: Omit<(UseMutationOptions<(ScimToken | undefined), DefaultError, Prisma.ScimTokenUpsertArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.ScimTokenUpsertArgs, DefaultError, ScimToken, true>('ScimToken', 'POST', `${endpoint}/scimToken/upsert`, metadata, options, fetch, true)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.ScimTokenUpsertArgs>(
            args: Prisma.SelectSubset<T, Prisma.ScimTokenUpsertArgs>,
            options?: Omit<(UseMutationOptions<(CheckSelect<T, ScimToken, Prisma.ScimTokenGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.ScimTokenUpsertArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as (CheckSelect<T, ScimToken, Prisma.ScimTokenGetPayload<T>> | undefined);
        },
    };
    return mutation;
}

export function useDeleteScimToken(options?: Omit<(UseMutationOptions<(ScimToken | undefined), DefaultError, Prisma.ScimTokenDeleteArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.ScimTokenDeleteArgs, DefaultError, ScimToken, true>('ScimToken', 'DELETE', `${endpoint}/scimToken/delete`, metadata, options, fetch, true)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.ScimTokenDeleteArgs>(
            args: Prisma.SelectSubset<T, Prisma.ScimTokenDeleteArgs>,
            options?: Omit<(UseMutationOptions<(CheckSelect<T, ScimToken, Prisma.ScimTokenGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.ScimTokenDeleteArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as (CheckSelect<T, ScimToken, Prisma.ScimTokenGetPayload<T>> | undefined);
        },
    };
    return mutation;
}

export function useDeleteManyScimToken(options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.ScimTokenDeleteManyArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.ScimTokenDeleteManyArgs, DefaultError, Prisma.BatchPayload, false>('ScimToken', 'DELETE', `${endpoint}/scimToken/deleteMany`, metadata, options, fetch, false)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.ScimTokenDeleteManyArgs>(
            args: Prisma.SelectSubset<T, Prisma.ScimTokenDeleteManyArgs>,
            options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.SelectSubset<T, Prisma.ScimTokenDeleteManyArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as Prisma.BatchPayload;
        },
    };
    return mutation;
}

export function useAggregateScimToken<TArgs extends Prisma.ScimTokenAggregateArgs, TQueryFnData = Prisma.GetScimTokenAggregateType<TArgs>, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.ScimTokenAggregateArgs>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('ScimToken', `${endpoint}/scimToken/aggregate`, args, options, fetch);
}

export function useSuspenseAggregateScimToken<TArgs extends Prisma.ScimTokenAggregateArgs, TQueryFnData = Prisma.GetScimTokenAggregateType<TArgs>, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.ScimTokenAggregateArgs>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('ScimToken', `${endpoint}/scimToken/aggregate`, args, options, fetch);
}

export function useGroupByScimToken<TArgs extends Prisma.ScimTokenGroupByArgs, HasSelectOrTake extends Prisma.Or<Prisma.Extends<'skip', Prisma.Keys<TArgs>>, Prisma.Extends<'take', Prisma.Keys<TArgs>>>, OrderByArg extends Prisma.True extends HasSelectOrTake ? { orderBy: Prisma.ScimTokenGroupByArgs['orderBy'] } : { orderBy?: Prisma.ScimTokenGroupByArgs['orderBy'] }, OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<TArgs['orderBy']>>>, ByFields extends Prisma.MaybeTupleToUnion<TArgs['by']>, ByValid extends Prisma.Has<ByFields, OrderFields>, HavingFields extends Prisma.GetHavingFields<TArgs['having']>, HavingValid extends Prisma.Has<ByFields, HavingFields>, ByEmpty extends TArgs['by'] extends never[] ? Prisma.True : Prisma.False, InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
        ? never
        : P extends string
        ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
        : [
            Error,
            'Field ',
            P,
            ` in "having" needs to be provided in "by"`,
        ]
    }[HavingFields]
    : 'take' extends Prisma.Keys<TArgs>
    ? 'orderBy' extends Prisma.Keys<TArgs>
    ? ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields]
    : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<TArgs>
    ? 'orderBy' extends Prisma.Keys<TArgs>
    ? ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields]
    : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields], TQueryFnData = {} extends InputErrors ?
    Array<PickEnumerable<Prisma.ScimTokenGroupByOutputType, TArgs['by']> &
    {
        [P in ((keyof TArgs) & (keyof Prisma.ScimTokenGroupByOutputType))]: P extends '_count'
        ? TArgs[P] extends boolean
        ? number
        : Prisma.GetScalarType<TArgs[P], Prisma.ScimTokenGroupByOutputType[P]>
        : Prisma.GetScalarType<TArgs[P], Prisma.ScimTokenGroupByOutputType[P]>
    }
    > : InputErrors, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.SubsetIntersection<TArgs, Prisma.ScimTokenGroupByArgs, OrderByArg> & InputErrors>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('ScimToken', `${endpoint}/scimToken/groupBy`, args, options, fetch);
}

export function useSuspenseGroupByScimToken<TArgs extends Prisma.ScimTokenGroupByArgs, HasSelectOrTake extends Prisma.Or<Prisma.Extends<'skip', Prisma.Keys<TArgs>>, Prisma.Extends<'take', Prisma.Keys<TArgs>>>, OrderByArg extends Prisma.True extends HasSelectOrTake ? { orderBy: Prisma.ScimTokenGroupByArgs['orderBy'] } : { orderBy?: Prisma.ScimTokenGroupByArgs['orderBy'] }, OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<TArgs['orderBy']>>>, ByFields extends Prisma.MaybeTupleToUnion<TArgs['by']>, ByValid extends Prisma.Has<ByFields, OrderFields>, HavingFields extends Prisma.GetHavingFields<TArgs['having']>, HavingValid extends Prisma.Has<ByFields, HavingFields>, ByEmpty extends TArgs['by'] extends never[] ? Prisma.True : Prisma.False, InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
        ? never
        : P extends string
        ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
        : [
            Error,
            'Field ',
            P,
            ` in "having" needs to be provided in "by"`,
        ]
    }[HavingFields]
    : 'take' extends Prisma.Keys<TArgs>
    ? 'orderBy' extends Prisma.Keys<TArgs>
    ? ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields]
    : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<TArgs>
    ? 'orderBy' extends Prisma.Keys<TArgs>
    ? ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields]
    : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields], TQueryFnData = {} extends InputErrors ?
    Array<PickEnumerable<Prisma.ScimTokenGroupByOutputType, TArgs['by']> &
    {
        [P in ((keyof TArgs) & (keyof Prisma.ScimTokenGroupByOutputType))]: P extends '_count'
        ? TArgs[P] extends boolean
        ? number
        : Prisma.GetScalarType<TArgs[P], Prisma.ScimTokenGroupByOutputType[P]>
        : Prisma.GetScalarType<TArgs[P], Prisma.ScimTokenGroupByOutputType[P]>
    }
    > : InputErrors, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.SubsetIntersection<TArgs, Prisma.ScimTokenGroupByArgs, OrderByArg> & InputErrors>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('ScimToken', `${endpoint}/scimToken/groupBy`, args, options, fetch);
}

export function useCountScimToken<TArgs extends Prisma.ScimTokenCountArgs, TQueryFnData = TArgs extends { select: any; } ? TArgs['select'] extends true ? number : Prisma.GetScalarType<TArgs['select'], Prisma.ScimTokenCountAggregateOutputType> : number, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.ScimTokenCountArgs>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('ScimToken', `${endpoint}/scimToken/count`, args, options, fetch);
}

export function useSuspenseCountScimToken<TArgs extends Prisma.ScimTokenCountArgs, TQueryFnData = TArgs extends { select: any; } ? TArgs['select'] extends true ? number : Prisma.GetScalarType<TArgs['select'], Prisma.ScimTokenCountAggregateOutputType> : number, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.ScimTokenCountArgs>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('ScimToken', `${endpoint}/scimToken/count`, args, options, fetch);
}
import type { IdpName } from '@prisma/client';

export function useCheckScimToken<TError = DefaultError>(args: { operation: PolicyCrudKind; where?: { id?: string; name?: string; idpName?: IdpName; token?: string; tokenPrefix?: string; secret?: string; systemUserId?: string; createdById?: string; revokedById?: string; lastUsedIp?: string; isActive?: boolean }; }, options?: (Omit<UseQueryOptions<boolean, TError, boolean>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<boolean, boolean, TError>('ScimToken', `${endpoint}/scimToken/check`, args, options, fetch);
}
