/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */

import type { Prisma, StepSequenceMatch } from "@prisma/client";
import type { UseMutationOptions, UseQueryOptions, UseInfiniteQueryOptions, InfiniteData } from '@tanstack/react-query';
import { getHooksContext } from '@zenstackhq/tanstack-query/runtime-v5/react';
import { useModelQuery, useInfiniteModelQuery, useModelMutation } from '@zenstackhq/tanstack-query/runtime-v5/react';
import type { PickEnumerable, CheckSelect, QueryError, ExtraQueryOptions, ExtraMutationOptions } from '@zenstackhq/tanstack-query/runtime-v5';
import type { PolicyCrudKind } from '@zenstackhq/runtime'
import metadata from './__model_meta';
type DefaultError = QueryError;
import { useSuspenseModelQuery, useSuspenseInfiniteModelQuery } from '@zenstackhq/tanstack-query/runtime-v5/react';
import type { UseSuspenseQueryOptions, UseSuspenseInfiniteQueryOptions } from '@tanstack/react-query';

export function useCreateStepSequenceMatch(options?: Omit<(UseMutationOptions<(StepSequenceMatch | undefined), DefaultError, Prisma.StepSequenceMatchCreateArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.StepSequenceMatchCreateArgs, DefaultError, StepSequenceMatch, true>('StepSequenceMatch', 'POST', `${endpoint}/stepSequenceMatch/create`, metadata, options, fetch, true)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.StepSequenceMatchCreateArgs>(
            args: Prisma.SelectSubset<T, Prisma.StepSequenceMatchCreateArgs>,
            options?: Omit<(UseMutationOptions<(CheckSelect<T, StepSequenceMatch, Prisma.StepSequenceMatchGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.StepSequenceMatchCreateArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as (CheckSelect<T, StepSequenceMatch, Prisma.StepSequenceMatchGetPayload<T>> | undefined);
        },
    };
    return mutation;
}

export function useCreateManyStepSequenceMatch(options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.StepSequenceMatchCreateManyArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.StepSequenceMatchCreateManyArgs, DefaultError, Prisma.BatchPayload, false>('StepSequenceMatch', 'POST', `${endpoint}/stepSequenceMatch/createMany`, metadata, options, fetch, false)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.StepSequenceMatchCreateManyArgs>(
            args: Prisma.SelectSubset<T, Prisma.StepSequenceMatchCreateManyArgs>,
            options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.SelectSubset<T, Prisma.StepSequenceMatchCreateManyArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as Prisma.BatchPayload;
        },
    };
    return mutation;
}

export function useFindManyStepSequenceMatch<TArgs extends Prisma.StepSequenceMatchFindManyArgs, TQueryFnData = Array<Prisma.StepSequenceMatchGetPayload<TArgs> & { $optimistic?: boolean }>, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.StepSequenceMatchFindManyArgs>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('StepSequenceMatch', `${endpoint}/stepSequenceMatch/findMany`, args, options, fetch);
}

export function useInfiniteFindManyStepSequenceMatch<TArgs extends Prisma.StepSequenceMatchFindManyArgs, TQueryFnData = Array<Prisma.StepSequenceMatchGetPayload<TArgs>>, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.StepSequenceMatchFindManyArgs>, options?: Omit<UseInfiniteQueryOptions<TQueryFnData, TError, InfiniteData<TData>>, 'queryKey' | 'initialPageParam'>) {
    options = options ?? { getNextPageParam: () => null };
    const { endpoint, fetch } = getHooksContext();
    return useInfiniteModelQuery<TQueryFnData, TData, TError>('StepSequenceMatch', `${endpoint}/stepSequenceMatch/findMany`, args, options, fetch);
}

export function useSuspenseFindManyStepSequenceMatch<TArgs extends Prisma.StepSequenceMatchFindManyArgs, TQueryFnData = Array<Prisma.StepSequenceMatchGetPayload<TArgs> & { $optimistic?: boolean }>, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.StepSequenceMatchFindManyArgs>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('StepSequenceMatch', `${endpoint}/stepSequenceMatch/findMany`, args, options, fetch);
}

export function useSuspenseInfiniteFindManyStepSequenceMatch<TArgs extends Prisma.StepSequenceMatchFindManyArgs, TQueryFnData = Array<Prisma.StepSequenceMatchGetPayload<TArgs>>, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.StepSequenceMatchFindManyArgs>, options?: Omit<UseSuspenseInfiniteQueryOptions<TQueryFnData, TError, InfiniteData<TData>>, 'queryKey' | 'initialPageParam'>) {
    options = options ?? { getNextPageParam: () => null };
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseInfiniteModelQuery<TQueryFnData, TData, TError>('StepSequenceMatch', `${endpoint}/stepSequenceMatch/findMany`, args, options, fetch);
}

export function useFindUniqueStepSequenceMatch<TArgs extends Prisma.StepSequenceMatchFindUniqueArgs, TQueryFnData = Prisma.StepSequenceMatchGetPayload<TArgs> & { $optimistic?: boolean }, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.StepSequenceMatchFindUniqueArgs>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('StepSequenceMatch', `${endpoint}/stepSequenceMatch/findUnique`, args, options, fetch);
}

export function useSuspenseFindUniqueStepSequenceMatch<TArgs extends Prisma.StepSequenceMatchFindUniqueArgs, TQueryFnData = Prisma.StepSequenceMatchGetPayload<TArgs> & { $optimistic?: boolean }, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.StepSequenceMatchFindUniqueArgs>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('StepSequenceMatch', `${endpoint}/stepSequenceMatch/findUnique`, args, options, fetch);
}

export function useFindFirstStepSequenceMatch<TArgs extends Prisma.StepSequenceMatchFindFirstArgs, TQueryFnData = Prisma.StepSequenceMatchGetPayload<TArgs> & { $optimistic?: boolean }, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.StepSequenceMatchFindFirstArgs>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('StepSequenceMatch', `${endpoint}/stepSequenceMatch/findFirst`, args, options, fetch);
}

export function useSuspenseFindFirstStepSequenceMatch<TArgs extends Prisma.StepSequenceMatchFindFirstArgs, TQueryFnData = Prisma.StepSequenceMatchGetPayload<TArgs> & { $optimistic?: boolean }, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.StepSequenceMatchFindFirstArgs>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('StepSequenceMatch', `${endpoint}/stepSequenceMatch/findFirst`, args, options, fetch);
}

export function useUpdateStepSequenceMatch(options?: Omit<(UseMutationOptions<(StepSequenceMatch | undefined), DefaultError, Prisma.StepSequenceMatchUpdateArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.StepSequenceMatchUpdateArgs, DefaultError, StepSequenceMatch, true>('StepSequenceMatch', 'PUT', `${endpoint}/stepSequenceMatch/update`, metadata, options, fetch, true)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.StepSequenceMatchUpdateArgs>(
            args: Prisma.SelectSubset<T, Prisma.StepSequenceMatchUpdateArgs>,
            options?: Omit<(UseMutationOptions<(CheckSelect<T, StepSequenceMatch, Prisma.StepSequenceMatchGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.StepSequenceMatchUpdateArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as (CheckSelect<T, StepSequenceMatch, Prisma.StepSequenceMatchGetPayload<T>> | undefined);
        },
    };
    return mutation;
}

export function useUpdateManyStepSequenceMatch(options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.StepSequenceMatchUpdateManyArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.StepSequenceMatchUpdateManyArgs, DefaultError, Prisma.BatchPayload, false>('StepSequenceMatch', 'PUT', `${endpoint}/stepSequenceMatch/updateMany`, metadata, options, fetch, false)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.StepSequenceMatchUpdateManyArgs>(
            args: Prisma.SelectSubset<T, Prisma.StepSequenceMatchUpdateManyArgs>,
            options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.SelectSubset<T, Prisma.StepSequenceMatchUpdateManyArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as Prisma.BatchPayload;
        },
    };
    return mutation;
}

export function useUpsertStepSequenceMatch(options?: Omit<(UseMutationOptions<(StepSequenceMatch | undefined), DefaultError, Prisma.StepSequenceMatchUpsertArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.StepSequenceMatchUpsertArgs, DefaultError, StepSequenceMatch, true>('StepSequenceMatch', 'POST', `${endpoint}/stepSequenceMatch/upsert`, metadata, options, fetch, true)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.StepSequenceMatchUpsertArgs>(
            args: Prisma.SelectSubset<T, Prisma.StepSequenceMatchUpsertArgs>,
            options?: Omit<(UseMutationOptions<(CheckSelect<T, StepSequenceMatch, Prisma.StepSequenceMatchGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.StepSequenceMatchUpsertArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as (CheckSelect<T, StepSequenceMatch, Prisma.StepSequenceMatchGetPayload<T>> | undefined);
        },
    };
    return mutation;
}

export function useDeleteStepSequenceMatch(options?: Omit<(UseMutationOptions<(StepSequenceMatch | undefined), DefaultError, Prisma.StepSequenceMatchDeleteArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.StepSequenceMatchDeleteArgs, DefaultError, StepSequenceMatch, true>('StepSequenceMatch', 'DELETE', `${endpoint}/stepSequenceMatch/delete`, metadata, options, fetch, true)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.StepSequenceMatchDeleteArgs>(
            args: Prisma.SelectSubset<T, Prisma.StepSequenceMatchDeleteArgs>,
            options?: Omit<(UseMutationOptions<(CheckSelect<T, StepSequenceMatch, Prisma.StepSequenceMatchGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.StepSequenceMatchDeleteArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as (CheckSelect<T, StepSequenceMatch, Prisma.StepSequenceMatchGetPayload<T>> | undefined);
        },
    };
    return mutation;
}

export function useDeleteManyStepSequenceMatch(options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.StepSequenceMatchDeleteManyArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.StepSequenceMatchDeleteManyArgs, DefaultError, Prisma.BatchPayload, false>('StepSequenceMatch', 'DELETE', `${endpoint}/stepSequenceMatch/deleteMany`, metadata, options, fetch, false)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.StepSequenceMatchDeleteManyArgs>(
            args: Prisma.SelectSubset<T, Prisma.StepSequenceMatchDeleteManyArgs>,
            options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.SelectSubset<T, Prisma.StepSequenceMatchDeleteManyArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as Prisma.BatchPayload;
        },
    };
    return mutation;
}

export function useAggregateStepSequenceMatch<TArgs extends Prisma.StepSequenceMatchAggregateArgs, TQueryFnData = Prisma.GetStepSequenceMatchAggregateType<TArgs>, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.StepSequenceMatchAggregateArgs>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('StepSequenceMatch', `${endpoint}/stepSequenceMatch/aggregate`, args, options, fetch);
}

export function useSuspenseAggregateStepSequenceMatch<TArgs extends Prisma.StepSequenceMatchAggregateArgs, TQueryFnData = Prisma.GetStepSequenceMatchAggregateType<TArgs>, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.StepSequenceMatchAggregateArgs>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('StepSequenceMatch', `${endpoint}/stepSequenceMatch/aggregate`, args, options, fetch);
}

export function useGroupByStepSequenceMatch<TArgs extends Prisma.StepSequenceMatchGroupByArgs, HasSelectOrTake extends Prisma.Or<Prisma.Extends<'skip', Prisma.Keys<TArgs>>, Prisma.Extends<'take', Prisma.Keys<TArgs>>>, OrderByArg extends Prisma.True extends HasSelectOrTake ? { orderBy: Prisma.StepSequenceMatchGroupByArgs['orderBy'] } : { orderBy?: Prisma.StepSequenceMatchGroupByArgs['orderBy'] }, OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<TArgs['orderBy']>>>, ByFields extends Prisma.MaybeTupleToUnion<TArgs['by']>, ByValid extends Prisma.Has<ByFields, OrderFields>, HavingFields extends Prisma.GetHavingFields<TArgs['having']>, HavingValid extends Prisma.Has<ByFields, HavingFields>, ByEmpty extends TArgs['by'] extends never[] ? Prisma.True : Prisma.False, InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
        ? never
        : P extends string
        ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
        : [
            Error,
            'Field ',
            P,
            ` in "having" needs to be provided in "by"`,
        ]
    }[HavingFields]
    : 'take' extends Prisma.Keys<TArgs>
    ? 'orderBy' extends Prisma.Keys<TArgs>
    ? ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields]
    : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<TArgs>
    ? 'orderBy' extends Prisma.Keys<TArgs>
    ? ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields]
    : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields], TQueryFnData = {} extends InputErrors ?
    Array<PickEnumerable<Prisma.StepSequenceMatchGroupByOutputType, TArgs['by']> &
    {
        [P in ((keyof TArgs) & (keyof Prisma.StepSequenceMatchGroupByOutputType))]: P extends '_count'
        ? TArgs[P] extends boolean
        ? number
        : Prisma.GetScalarType<TArgs[P], Prisma.StepSequenceMatchGroupByOutputType[P]>
        : Prisma.GetScalarType<TArgs[P], Prisma.StepSequenceMatchGroupByOutputType[P]>
    }
    > : InputErrors, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.SubsetIntersection<TArgs, Prisma.StepSequenceMatchGroupByArgs, OrderByArg> & InputErrors>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('StepSequenceMatch', `${endpoint}/stepSequenceMatch/groupBy`, args, options, fetch);
}

export function useSuspenseGroupByStepSequenceMatch<TArgs extends Prisma.StepSequenceMatchGroupByArgs, HasSelectOrTake extends Prisma.Or<Prisma.Extends<'skip', Prisma.Keys<TArgs>>, Prisma.Extends<'take', Prisma.Keys<TArgs>>>, OrderByArg extends Prisma.True extends HasSelectOrTake ? { orderBy: Prisma.StepSequenceMatchGroupByArgs['orderBy'] } : { orderBy?: Prisma.StepSequenceMatchGroupByArgs['orderBy'] }, OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<TArgs['orderBy']>>>, ByFields extends Prisma.MaybeTupleToUnion<TArgs['by']>, ByValid extends Prisma.Has<ByFields, OrderFields>, HavingFields extends Prisma.GetHavingFields<TArgs['having']>, HavingValid extends Prisma.Has<ByFields, HavingFields>, ByEmpty extends TArgs['by'] extends never[] ? Prisma.True : Prisma.False, InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
        ? never
        : P extends string
        ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
        : [
            Error,
            'Field ',
            P,
            ` in "having" needs to be provided in "by"`,
        ]
    }[HavingFields]
    : 'take' extends Prisma.Keys<TArgs>
    ? 'orderBy' extends Prisma.Keys<TArgs>
    ? ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields]
    : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<TArgs>
    ? 'orderBy' extends Prisma.Keys<TArgs>
    ? ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields]
    : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields], TQueryFnData = {} extends InputErrors ?
    Array<PickEnumerable<Prisma.StepSequenceMatchGroupByOutputType, TArgs['by']> &
    {
        [P in ((keyof TArgs) & (keyof Prisma.StepSequenceMatchGroupByOutputType))]: P extends '_count'
        ? TArgs[P] extends boolean
        ? number
        : Prisma.GetScalarType<TArgs[P], Prisma.StepSequenceMatchGroupByOutputType[P]>
        : Prisma.GetScalarType<TArgs[P], Prisma.StepSequenceMatchGroupByOutputType[P]>
    }
    > : InputErrors, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.SubsetIntersection<TArgs, Prisma.StepSequenceMatchGroupByArgs, OrderByArg> & InputErrors>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('StepSequenceMatch', `${endpoint}/stepSequenceMatch/groupBy`, args, options, fetch);
}

export function useCountStepSequenceMatch<TArgs extends Prisma.StepSequenceMatchCountArgs, TQueryFnData = TArgs extends { select: any; } ? TArgs['select'] extends true ? number : Prisma.GetScalarType<TArgs['select'], Prisma.StepSequenceMatchCountAggregateOutputType> : number, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.StepSequenceMatchCountArgs>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('StepSequenceMatch', `${endpoint}/stepSequenceMatch/count`, args, options, fetch);
}

export function useSuspenseCountStepSequenceMatch<TArgs extends Prisma.StepSequenceMatchCountArgs, TQueryFnData = TArgs extends { select: any; } ? TArgs['select'] extends true ? number : Prisma.GetScalarType<TArgs['select'], Prisma.StepSequenceMatchCountAggregateOutputType> : number, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.StepSequenceMatchCountArgs>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('StepSequenceMatch', `${endpoint}/stepSequenceMatch/count`, args, options, fetch);
}
import type { StepSequenceMatchStatus } from '@prisma/client';

export function useCheckStepSequenceMatch<TError = DefaultError>(args: { operation: PolicyCrudKind; where?: { id?: number; projectId?: number; fingerprint?: string; stepCount?: number; status?: StepSequenceMatchStatus; scanJobId?: string; isDeleted?: boolean }; }, options?: (Omit<UseQueryOptions<boolean, TError, boolean>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<boolean, boolean, TError>('StepSequenceMatch', `${endpoint}/stepSequenceMatch/check`, args, options, fetch);
}
