/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */

import type { Prisma, TestRunCaseIteration } from "@prisma/client";
import type { UseMutationOptions, UseQueryOptions, UseInfiniteQueryOptions, InfiniteData } from '@tanstack/react-query';
import { getHooksContext } from '@zenstackhq/tanstack-query/runtime-v5/react';
import { useModelQuery, useInfiniteModelQuery, useModelMutation } from '@zenstackhq/tanstack-query/runtime-v5/react';
import type { PickEnumerable, CheckSelect, QueryError, ExtraQueryOptions, ExtraMutationOptions } from '@zenstackhq/tanstack-query/runtime-v5';
import type { PolicyCrudKind } from '@zenstackhq/runtime'
import metadata from './__model_meta';
type DefaultError = QueryError;
import { useSuspenseModelQuery, useSuspenseInfiniteModelQuery } from '@zenstackhq/tanstack-query/runtime-v5/react';
import type { UseSuspenseQueryOptions, UseSuspenseInfiniteQueryOptions } from '@tanstack/react-query';

export function useCreateTestRunCaseIteration(options?: Omit<(UseMutationOptions<(TestRunCaseIteration | undefined), DefaultError, Prisma.TestRunCaseIterationCreateArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.TestRunCaseIterationCreateArgs, DefaultError, TestRunCaseIteration, true>('TestRunCaseIteration', 'POST', `${endpoint}/testRunCaseIteration/create`, metadata, options, fetch, true)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.TestRunCaseIterationCreateArgs>(
            args: Prisma.SelectSubset<T, Prisma.TestRunCaseIterationCreateArgs>,
            options?: Omit<(UseMutationOptions<(CheckSelect<T, TestRunCaseIteration, Prisma.TestRunCaseIterationGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.TestRunCaseIterationCreateArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as (CheckSelect<T, TestRunCaseIteration, Prisma.TestRunCaseIterationGetPayload<T>> | undefined);
        },
    };
    return mutation;
}

export function useCreateManyTestRunCaseIteration(options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.TestRunCaseIterationCreateManyArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.TestRunCaseIterationCreateManyArgs, DefaultError, Prisma.BatchPayload, false>('TestRunCaseIteration', 'POST', `${endpoint}/testRunCaseIteration/createMany`, metadata, options, fetch, false)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.TestRunCaseIterationCreateManyArgs>(
            args: Prisma.SelectSubset<T, Prisma.TestRunCaseIterationCreateManyArgs>,
            options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.SelectSubset<T, Prisma.TestRunCaseIterationCreateManyArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as Prisma.BatchPayload;
        },
    };
    return mutation;
}

export function useFindManyTestRunCaseIteration<TArgs extends Prisma.TestRunCaseIterationFindManyArgs, TQueryFnData = Array<Prisma.TestRunCaseIterationGetPayload<TArgs> & { $optimistic?: boolean }>, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.TestRunCaseIterationFindManyArgs>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('TestRunCaseIteration', `${endpoint}/testRunCaseIteration/findMany`, args, options, fetch);
}

export function useInfiniteFindManyTestRunCaseIteration<TArgs extends Prisma.TestRunCaseIterationFindManyArgs, TQueryFnData = Array<Prisma.TestRunCaseIterationGetPayload<TArgs>>, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.TestRunCaseIterationFindManyArgs>, options?: Omit<UseInfiniteQueryOptions<TQueryFnData, TError, InfiniteData<TData>>, 'queryKey' | 'initialPageParam'>) {
    options = options ?? { getNextPageParam: () => null };
    const { endpoint, fetch } = getHooksContext();
    return useInfiniteModelQuery<TQueryFnData, TData, TError>('TestRunCaseIteration', `${endpoint}/testRunCaseIteration/findMany`, args, options, fetch);
}

export function useSuspenseFindManyTestRunCaseIteration<TArgs extends Prisma.TestRunCaseIterationFindManyArgs, TQueryFnData = Array<Prisma.TestRunCaseIterationGetPayload<TArgs> & { $optimistic?: boolean }>, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.TestRunCaseIterationFindManyArgs>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('TestRunCaseIteration', `${endpoint}/testRunCaseIteration/findMany`, args, options, fetch);
}

export function useSuspenseInfiniteFindManyTestRunCaseIteration<TArgs extends Prisma.TestRunCaseIterationFindManyArgs, TQueryFnData = Array<Prisma.TestRunCaseIterationGetPayload<TArgs>>, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.TestRunCaseIterationFindManyArgs>, options?: Omit<UseSuspenseInfiniteQueryOptions<TQueryFnData, TError, InfiniteData<TData>>, 'queryKey' | 'initialPageParam'>) {
    options = options ?? { getNextPageParam: () => null };
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseInfiniteModelQuery<TQueryFnData, TData, TError>('TestRunCaseIteration', `${endpoint}/testRunCaseIteration/findMany`, args, options, fetch);
}

export function useFindUniqueTestRunCaseIteration<TArgs extends Prisma.TestRunCaseIterationFindUniqueArgs, TQueryFnData = Prisma.TestRunCaseIterationGetPayload<TArgs> & { $optimistic?: boolean }, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.TestRunCaseIterationFindUniqueArgs>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('TestRunCaseIteration', `${endpoint}/testRunCaseIteration/findUnique`, args, options, fetch);
}

export function useSuspenseFindUniqueTestRunCaseIteration<TArgs extends Prisma.TestRunCaseIterationFindUniqueArgs, TQueryFnData = Prisma.TestRunCaseIterationGetPayload<TArgs> & { $optimistic?: boolean }, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.TestRunCaseIterationFindUniqueArgs>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('TestRunCaseIteration', `${endpoint}/testRunCaseIteration/findUnique`, args, options, fetch);
}

export function useFindFirstTestRunCaseIteration<TArgs extends Prisma.TestRunCaseIterationFindFirstArgs, TQueryFnData = Prisma.TestRunCaseIterationGetPayload<TArgs> & { $optimistic?: boolean }, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.TestRunCaseIterationFindFirstArgs>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('TestRunCaseIteration', `${endpoint}/testRunCaseIteration/findFirst`, args, options, fetch);
}

export function useSuspenseFindFirstTestRunCaseIteration<TArgs extends Prisma.TestRunCaseIterationFindFirstArgs, TQueryFnData = Prisma.TestRunCaseIterationGetPayload<TArgs> & { $optimistic?: boolean }, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.TestRunCaseIterationFindFirstArgs>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('TestRunCaseIteration', `${endpoint}/testRunCaseIteration/findFirst`, args, options, fetch);
}

export function useUpdateTestRunCaseIteration(options?: Omit<(UseMutationOptions<(TestRunCaseIteration | undefined), DefaultError, Prisma.TestRunCaseIterationUpdateArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.TestRunCaseIterationUpdateArgs, DefaultError, TestRunCaseIteration, true>('TestRunCaseIteration', 'PUT', `${endpoint}/testRunCaseIteration/update`, metadata, options, fetch, true)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.TestRunCaseIterationUpdateArgs>(
            args: Prisma.SelectSubset<T, Prisma.TestRunCaseIterationUpdateArgs>,
            options?: Omit<(UseMutationOptions<(CheckSelect<T, TestRunCaseIteration, Prisma.TestRunCaseIterationGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.TestRunCaseIterationUpdateArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as (CheckSelect<T, TestRunCaseIteration, Prisma.TestRunCaseIterationGetPayload<T>> | undefined);
        },
    };
    return mutation;
}

export function useUpdateManyTestRunCaseIteration(options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.TestRunCaseIterationUpdateManyArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.TestRunCaseIterationUpdateManyArgs, DefaultError, Prisma.BatchPayload, false>('TestRunCaseIteration', 'PUT', `${endpoint}/testRunCaseIteration/updateMany`, metadata, options, fetch, false)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.TestRunCaseIterationUpdateManyArgs>(
            args: Prisma.SelectSubset<T, Prisma.TestRunCaseIterationUpdateManyArgs>,
            options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.SelectSubset<T, Prisma.TestRunCaseIterationUpdateManyArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as Prisma.BatchPayload;
        },
    };
    return mutation;
}

export function useUpsertTestRunCaseIteration(options?: Omit<(UseMutationOptions<(TestRunCaseIteration | undefined), DefaultError, Prisma.TestRunCaseIterationUpsertArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.TestRunCaseIterationUpsertArgs, DefaultError, TestRunCaseIteration, true>('TestRunCaseIteration', 'POST', `${endpoint}/testRunCaseIteration/upsert`, metadata, options, fetch, true)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.TestRunCaseIterationUpsertArgs>(
            args: Prisma.SelectSubset<T, Prisma.TestRunCaseIterationUpsertArgs>,
            options?: Omit<(UseMutationOptions<(CheckSelect<T, TestRunCaseIteration, Prisma.TestRunCaseIterationGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.TestRunCaseIterationUpsertArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as (CheckSelect<T, TestRunCaseIteration, Prisma.TestRunCaseIterationGetPayload<T>> | undefined);
        },
    };
    return mutation;
}

export function useDeleteTestRunCaseIteration(options?: Omit<(UseMutationOptions<(TestRunCaseIteration | undefined), DefaultError, Prisma.TestRunCaseIterationDeleteArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.TestRunCaseIterationDeleteArgs, DefaultError, TestRunCaseIteration, true>('TestRunCaseIteration', 'DELETE', `${endpoint}/testRunCaseIteration/delete`, metadata, options, fetch, true)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.TestRunCaseIterationDeleteArgs>(
            args: Prisma.SelectSubset<T, Prisma.TestRunCaseIterationDeleteArgs>,
            options?: Omit<(UseMutationOptions<(CheckSelect<T, TestRunCaseIteration, Prisma.TestRunCaseIterationGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.TestRunCaseIterationDeleteArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as (CheckSelect<T, TestRunCaseIteration, Prisma.TestRunCaseIterationGetPayload<T>> | undefined);
        },
    };
    return mutation;
}

export function useDeleteManyTestRunCaseIteration(options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.TestRunCaseIterationDeleteManyArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.TestRunCaseIterationDeleteManyArgs, DefaultError, Prisma.BatchPayload, false>('TestRunCaseIteration', 'DELETE', `${endpoint}/testRunCaseIteration/deleteMany`, metadata, options, fetch, false)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.TestRunCaseIterationDeleteManyArgs>(
            args: Prisma.SelectSubset<T, Prisma.TestRunCaseIterationDeleteManyArgs>,
            options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.SelectSubset<T, Prisma.TestRunCaseIterationDeleteManyArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as Prisma.BatchPayload;
        },
    };
    return mutation;
}

export function useAggregateTestRunCaseIteration<TArgs extends Prisma.TestRunCaseIterationAggregateArgs, TQueryFnData = Prisma.GetTestRunCaseIterationAggregateType<TArgs>, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.TestRunCaseIterationAggregateArgs>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('TestRunCaseIteration', `${endpoint}/testRunCaseIteration/aggregate`, args, options, fetch);
}

export function useSuspenseAggregateTestRunCaseIteration<TArgs extends Prisma.TestRunCaseIterationAggregateArgs, TQueryFnData = Prisma.GetTestRunCaseIterationAggregateType<TArgs>, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.TestRunCaseIterationAggregateArgs>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('TestRunCaseIteration', `${endpoint}/testRunCaseIteration/aggregate`, args, options, fetch);
}

export function useGroupByTestRunCaseIteration<TArgs extends Prisma.TestRunCaseIterationGroupByArgs, HasSelectOrTake extends Prisma.Or<Prisma.Extends<'skip', Prisma.Keys<TArgs>>, Prisma.Extends<'take', Prisma.Keys<TArgs>>>, OrderByArg extends Prisma.True extends HasSelectOrTake ? { orderBy: Prisma.TestRunCaseIterationGroupByArgs['orderBy'] } : { orderBy?: Prisma.TestRunCaseIterationGroupByArgs['orderBy'] }, OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<TArgs['orderBy']>>>, ByFields extends Prisma.MaybeTupleToUnion<TArgs['by']>, ByValid extends Prisma.Has<ByFields, OrderFields>, HavingFields extends Prisma.GetHavingFields<TArgs['having']>, HavingValid extends Prisma.Has<ByFields, HavingFields>, ByEmpty extends TArgs['by'] extends never[] ? Prisma.True : Prisma.False, InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
        ? never
        : P extends string
        ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
        : [
            Error,
            'Field ',
            P,
            ` in "having" needs to be provided in "by"`,
        ]
    }[HavingFields]
    : 'take' extends Prisma.Keys<TArgs>
    ? 'orderBy' extends Prisma.Keys<TArgs>
    ? ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields]
    : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<TArgs>
    ? 'orderBy' extends Prisma.Keys<TArgs>
    ? ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields]
    : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields], TQueryFnData = {} extends InputErrors ?
    Array<PickEnumerable<Prisma.TestRunCaseIterationGroupByOutputType, TArgs['by']> &
    {
        [P in ((keyof TArgs) & (keyof Prisma.TestRunCaseIterationGroupByOutputType))]: P extends '_count'
        ? TArgs[P] extends boolean
        ? number
        : Prisma.GetScalarType<TArgs[P], Prisma.TestRunCaseIterationGroupByOutputType[P]>
        : Prisma.GetScalarType<TArgs[P], Prisma.TestRunCaseIterationGroupByOutputType[P]>
    }
    > : InputErrors, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.SubsetIntersection<TArgs, Prisma.TestRunCaseIterationGroupByArgs, OrderByArg> & InputErrors>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('TestRunCaseIteration', `${endpoint}/testRunCaseIteration/groupBy`, args, options, fetch);
}

export function useSuspenseGroupByTestRunCaseIteration<TArgs extends Prisma.TestRunCaseIterationGroupByArgs, HasSelectOrTake extends Prisma.Or<Prisma.Extends<'skip', Prisma.Keys<TArgs>>, Prisma.Extends<'take', Prisma.Keys<TArgs>>>, OrderByArg extends Prisma.True extends HasSelectOrTake ? { orderBy: Prisma.TestRunCaseIterationGroupByArgs['orderBy'] } : { orderBy?: Prisma.TestRunCaseIterationGroupByArgs['orderBy'] }, OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<TArgs['orderBy']>>>, ByFields extends Prisma.MaybeTupleToUnion<TArgs['by']>, ByValid extends Prisma.Has<ByFields, OrderFields>, HavingFields extends Prisma.GetHavingFields<TArgs['having']>, HavingValid extends Prisma.Has<ByFields, HavingFields>, ByEmpty extends TArgs['by'] extends never[] ? Prisma.True : Prisma.False, InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
        ? never
        : P extends string
        ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
        : [
            Error,
            'Field ',
            P,
            ` in "having" needs to be provided in "by"`,
        ]
    }[HavingFields]
    : 'take' extends Prisma.Keys<TArgs>
    ? 'orderBy' extends Prisma.Keys<TArgs>
    ? ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields]
    : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<TArgs>
    ? 'orderBy' extends Prisma.Keys<TArgs>
    ? ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields]
    : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields], TQueryFnData = {} extends InputErrors ?
    Array<PickEnumerable<Prisma.TestRunCaseIterationGroupByOutputType, TArgs['by']> &
    {
        [P in ((keyof TArgs) & (keyof Prisma.TestRunCaseIterationGroupByOutputType))]: P extends '_count'
        ? TArgs[P] extends boolean
        ? number
        : Prisma.GetScalarType<TArgs[P], Prisma.TestRunCaseIterationGroupByOutputType[P]>
        : Prisma.GetScalarType<TArgs[P], Prisma.TestRunCaseIterationGroupByOutputType[P]>
    }
    > : InputErrors, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.SubsetIntersection<TArgs, Prisma.TestRunCaseIterationGroupByArgs, OrderByArg> & InputErrors>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('TestRunCaseIteration', `${endpoint}/testRunCaseIteration/groupBy`, args, options, fetch);
}

export function useCountTestRunCaseIteration<TArgs extends Prisma.TestRunCaseIterationCountArgs, TQueryFnData = TArgs extends { select: any; } ? TArgs['select'] extends true ? number : Prisma.GetScalarType<TArgs['select'], Prisma.TestRunCaseIterationCountAggregateOutputType> : number, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.TestRunCaseIterationCountArgs>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('TestRunCaseIteration', `${endpoint}/testRunCaseIteration/count`, args, options, fetch);
}

export function useSuspenseCountTestRunCaseIteration<TArgs extends Prisma.TestRunCaseIterationCountArgs, TQueryFnData = TArgs extends { select: any; } ? TArgs['select'] extends true ? number : Prisma.GetScalarType<TArgs['select'], Prisma.TestRunCaseIterationCountAggregateOutputType> : number, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.TestRunCaseIterationCountArgs>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('TestRunCaseIteration', `${endpoint}/testRunCaseIteration/count`, args, options, fetch);
}

export function useCheckTestRunCaseIteration<TError = DefaultError>(args: { operation: PolicyCrudKind; where?: { id?: number; testRunCaseId?: number; rowIndex?: number; label?: string; ciExtended?: boolean; statusId?: number; assignedToId?: string; isCompleted?: boolean; elapsed?: number; isDeleted?: boolean; dataSetSnapshotId?: number }; }, options?: (Omit<UseQueryOptions<boolean, TError, boolean>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<boolean, boolean, TError>('TestRunCaseIteration', `${endpoint}/testRunCaseIteration/check`, args, options, fetch);
}
