/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */

import type { Prisma, TestCaseParameter } from "@prisma/client";
import type { UseMutationOptions, UseQueryOptions, UseInfiniteQueryOptions, InfiniteData } from '@tanstack/react-query';
import { getHooksContext } from '@zenstackhq/tanstack-query/runtime-v5/react';
import { useModelQuery, useInfiniteModelQuery, useModelMutation } from '@zenstackhq/tanstack-query/runtime-v5/react';
import type { PickEnumerable, CheckSelect, QueryError, ExtraQueryOptions, ExtraMutationOptions } from '@zenstackhq/tanstack-query/runtime-v5';
import type { PolicyCrudKind } from '@zenstackhq/runtime'
import metadata from './__model_meta';
type DefaultError = QueryError;
import { useSuspenseModelQuery, useSuspenseInfiniteModelQuery } from '@zenstackhq/tanstack-query/runtime-v5/react';
import type { UseSuspenseQueryOptions, UseSuspenseInfiniteQueryOptions } from '@tanstack/react-query';

export function useCreateTestCaseParameter(options?: Omit<(UseMutationOptions<(TestCaseParameter | undefined), DefaultError, Prisma.TestCaseParameterCreateArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.TestCaseParameterCreateArgs, DefaultError, TestCaseParameter, true>('TestCaseParameter', 'POST', `${endpoint}/testCaseParameter/create`, metadata, options, fetch, true)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.TestCaseParameterCreateArgs>(
            args: Prisma.SelectSubset<T, Prisma.TestCaseParameterCreateArgs>,
            options?: Omit<(UseMutationOptions<(CheckSelect<T, TestCaseParameter, Prisma.TestCaseParameterGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.TestCaseParameterCreateArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as (CheckSelect<T, TestCaseParameter, Prisma.TestCaseParameterGetPayload<T>> | undefined);
        },
    };
    return mutation;
}

export function useCreateManyTestCaseParameter(options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.TestCaseParameterCreateManyArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.TestCaseParameterCreateManyArgs, DefaultError, Prisma.BatchPayload, false>('TestCaseParameter', 'POST', `${endpoint}/testCaseParameter/createMany`, metadata, options, fetch, false)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.TestCaseParameterCreateManyArgs>(
            args: Prisma.SelectSubset<T, Prisma.TestCaseParameterCreateManyArgs>,
            options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.SelectSubset<T, Prisma.TestCaseParameterCreateManyArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as Prisma.BatchPayload;
        },
    };
    return mutation;
}

export function useFindManyTestCaseParameter<TArgs extends Prisma.TestCaseParameterFindManyArgs, TQueryFnData = Array<Prisma.TestCaseParameterGetPayload<TArgs> & { $optimistic?: boolean }>, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.TestCaseParameterFindManyArgs>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('TestCaseParameter', `${endpoint}/testCaseParameter/findMany`, args, options, fetch);
}

export function useInfiniteFindManyTestCaseParameter<TArgs extends Prisma.TestCaseParameterFindManyArgs, TQueryFnData = Array<Prisma.TestCaseParameterGetPayload<TArgs>>, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.TestCaseParameterFindManyArgs>, options?: Omit<UseInfiniteQueryOptions<TQueryFnData, TError, InfiniteData<TData>>, 'queryKey' | 'initialPageParam'>) {
    options = options ?? { getNextPageParam: () => null };
    const { endpoint, fetch } = getHooksContext();
    return useInfiniteModelQuery<TQueryFnData, TData, TError>('TestCaseParameter', `${endpoint}/testCaseParameter/findMany`, args, options, fetch);
}

export function useSuspenseFindManyTestCaseParameter<TArgs extends Prisma.TestCaseParameterFindManyArgs, TQueryFnData = Array<Prisma.TestCaseParameterGetPayload<TArgs> & { $optimistic?: boolean }>, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.TestCaseParameterFindManyArgs>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('TestCaseParameter', `${endpoint}/testCaseParameter/findMany`, args, options, fetch);
}

export function useSuspenseInfiniteFindManyTestCaseParameter<TArgs extends Prisma.TestCaseParameterFindManyArgs, TQueryFnData = Array<Prisma.TestCaseParameterGetPayload<TArgs>>, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.TestCaseParameterFindManyArgs>, options?: Omit<UseSuspenseInfiniteQueryOptions<TQueryFnData, TError, InfiniteData<TData>>, 'queryKey' | 'initialPageParam'>) {
    options = options ?? { getNextPageParam: () => null };
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseInfiniteModelQuery<TQueryFnData, TData, TError>('TestCaseParameter', `${endpoint}/testCaseParameter/findMany`, args, options, fetch);
}

export function useFindUniqueTestCaseParameter<TArgs extends Prisma.TestCaseParameterFindUniqueArgs, TQueryFnData = Prisma.TestCaseParameterGetPayload<TArgs> & { $optimistic?: boolean }, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.TestCaseParameterFindUniqueArgs>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('TestCaseParameter', `${endpoint}/testCaseParameter/findUnique`, args, options, fetch);
}

export function useSuspenseFindUniqueTestCaseParameter<TArgs extends Prisma.TestCaseParameterFindUniqueArgs, TQueryFnData = Prisma.TestCaseParameterGetPayload<TArgs> & { $optimistic?: boolean }, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.TestCaseParameterFindUniqueArgs>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('TestCaseParameter', `${endpoint}/testCaseParameter/findUnique`, args, options, fetch);
}

export function useFindFirstTestCaseParameter<TArgs extends Prisma.TestCaseParameterFindFirstArgs, TQueryFnData = Prisma.TestCaseParameterGetPayload<TArgs> & { $optimistic?: boolean }, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.TestCaseParameterFindFirstArgs>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('TestCaseParameter', `${endpoint}/testCaseParameter/findFirst`, args, options, fetch);
}

export function useSuspenseFindFirstTestCaseParameter<TArgs extends Prisma.TestCaseParameterFindFirstArgs, TQueryFnData = Prisma.TestCaseParameterGetPayload<TArgs> & { $optimistic?: boolean }, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.TestCaseParameterFindFirstArgs>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('TestCaseParameter', `${endpoint}/testCaseParameter/findFirst`, args, options, fetch);
}

export function useUpdateTestCaseParameter(options?: Omit<(UseMutationOptions<(TestCaseParameter | undefined), DefaultError, Prisma.TestCaseParameterUpdateArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.TestCaseParameterUpdateArgs, DefaultError, TestCaseParameter, true>('TestCaseParameter', 'PUT', `${endpoint}/testCaseParameter/update`, metadata, options, fetch, true)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.TestCaseParameterUpdateArgs>(
            args: Prisma.SelectSubset<T, Prisma.TestCaseParameterUpdateArgs>,
            options?: Omit<(UseMutationOptions<(CheckSelect<T, TestCaseParameter, Prisma.TestCaseParameterGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.TestCaseParameterUpdateArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as (CheckSelect<T, TestCaseParameter, Prisma.TestCaseParameterGetPayload<T>> | undefined);
        },
    };
    return mutation;
}

export function useUpdateManyTestCaseParameter(options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.TestCaseParameterUpdateManyArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.TestCaseParameterUpdateManyArgs, DefaultError, Prisma.BatchPayload, false>('TestCaseParameter', 'PUT', `${endpoint}/testCaseParameter/updateMany`, metadata, options, fetch, false)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.TestCaseParameterUpdateManyArgs>(
            args: Prisma.SelectSubset<T, Prisma.TestCaseParameterUpdateManyArgs>,
            options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.SelectSubset<T, Prisma.TestCaseParameterUpdateManyArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as Prisma.BatchPayload;
        },
    };
    return mutation;
}

export function useUpsertTestCaseParameter(options?: Omit<(UseMutationOptions<(TestCaseParameter | undefined), DefaultError, Prisma.TestCaseParameterUpsertArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.TestCaseParameterUpsertArgs, DefaultError, TestCaseParameter, true>('TestCaseParameter', 'POST', `${endpoint}/testCaseParameter/upsert`, metadata, options, fetch, true)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.TestCaseParameterUpsertArgs>(
            args: Prisma.SelectSubset<T, Prisma.TestCaseParameterUpsertArgs>,
            options?: Omit<(UseMutationOptions<(CheckSelect<T, TestCaseParameter, Prisma.TestCaseParameterGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.TestCaseParameterUpsertArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as (CheckSelect<T, TestCaseParameter, Prisma.TestCaseParameterGetPayload<T>> | undefined);
        },
    };
    return mutation;
}

export function useDeleteTestCaseParameter(options?: Omit<(UseMutationOptions<(TestCaseParameter | undefined), DefaultError, Prisma.TestCaseParameterDeleteArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.TestCaseParameterDeleteArgs, DefaultError, TestCaseParameter, true>('TestCaseParameter', 'DELETE', `${endpoint}/testCaseParameter/delete`, metadata, options, fetch, true)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.TestCaseParameterDeleteArgs>(
            args: Prisma.SelectSubset<T, Prisma.TestCaseParameterDeleteArgs>,
            options?: Omit<(UseMutationOptions<(CheckSelect<T, TestCaseParameter, Prisma.TestCaseParameterGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.TestCaseParameterDeleteArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as (CheckSelect<T, TestCaseParameter, Prisma.TestCaseParameterGetPayload<T>> | undefined);
        },
    };
    return mutation;
}

export function useDeleteManyTestCaseParameter(options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.TestCaseParameterDeleteManyArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.TestCaseParameterDeleteManyArgs, DefaultError, Prisma.BatchPayload, false>('TestCaseParameter', 'DELETE', `${endpoint}/testCaseParameter/deleteMany`, metadata, options, fetch, false)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.TestCaseParameterDeleteManyArgs>(
            args: Prisma.SelectSubset<T, Prisma.TestCaseParameterDeleteManyArgs>,
            options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.SelectSubset<T, Prisma.TestCaseParameterDeleteManyArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as Prisma.BatchPayload;
        },
    };
    return mutation;
}

export function useAggregateTestCaseParameter<TArgs extends Prisma.TestCaseParameterAggregateArgs, TQueryFnData = Prisma.GetTestCaseParameterAggregateType<TArgs>, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.TestCaseParameterAggregateArgs>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('TestCaseParameter', `${endpoint}/testCaseParameter/aggregate`, args, options, fetch);
}

export function useSuspenseAggregateTestCaseParameter<TArgs extends Prisma.TestCaseParameterAggregateArgs, TQueryFnData = Prisma.GetTestCaseParameterAggregateType<TArgs>, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.TestCaseParameterAggregateArgs>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('TestCaseParameter', `${endpoint}/testCaseParameter/aggregate`, args, options, fetch);
}

export function useGroupByTestCaseParameter<TArgs extends Prisma.TestCaseParameterGroupByArgs, HasSelectOrTake extends Prisma.Or<Prisma.Extends<'skip', Prisma.Keys<TArgs>>, Prisma.Extends<'take', Prisma.Keys<TArgs>>>, OrderByArg extends Prisma.True extends HasSelectOrTake ? { orderBy: Prisma.TestCaseParameterGroupByArgs['orderBy'] } : { orderBy?: Prisma.TestCaseParameterGroupByArgs['orderBy'] }, OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<TArgs['orderBy']>>>, ByFields extends Prisma.MaybeTupleToUnion<TArgs['by']>, ByValid extends Prisma.Has<ByFields, OrderFields>, HavingFields extends Prisma.GetHavingFields<TArgs['having']>, HavingValid extends Prisma.Has<ByFields, HavingFields>, ByEmpty extends TArgs['by'] extends never[] ? Prisma.True : Prisma.False, InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
        ? never
        : P extends string
        ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
        : [
            Error,
            'Field ',
            P,
            ` in "having" needs to be provided in "by"`,
        ]
    }[HavingFields]
    : 'take' extends Prisma.Keys<TArgs>
    ? 'orderBy' extends Prisma.Keys<TArgs>
    ? ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields]
    : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<TArgs>
    ? 'orderBy' extends Prisma.Keys<TArgs>
    ? ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields]
    : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields], TQueryFnData = {} extends InputErrors ?
    Array<PickEnumerable<Prisma.TestCaseParameterGroupByOutputType, TArgs['by']> &
    {
        [P in ((keyof TArgs) & (keyof Prisma.TestCaseParameterGroupByOutputType))]: P extends '_count'
        ? TArgs[P] extends boolean
        ? number
        : Prisma.GetScalarType<TArgs[P], Prisma.TestCaseParameterGroupByOutputType[P]>
        : Prisma.GetScalarType<TArgs[P], Prisma.TestCaseParameterGroupByOutputType[P]>
    }
    > : InputErrors, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.SubsetIntersection<TArgs, Prisma.TestCaseParameterGroupByArgs, OrderByArg> & InputErrors>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('TestCaseParameter', `${endpoint}/testCaseParameter/groupBy`, args, options, fetch);
}

export function useSuspenseGroupByTestCaseParameter<TArgs extends Prisma.TestCaseParameterGroupByArgs, HasSelectOrTake extends Prisma.Or<Prisma.Extends<'skip', Prisma.Keys<TArgs>>, Prisma.Extends<'take', Prisma.Keys<TArgs>>>, OrderByArg extends Prisma.True extends HasSelectOrTake ? { orderBy: Prisma.TestCaseParameterGroupByArgs['orderBy'] } : { orderBy?: Prisma.TestCaseParameterGroupByArgs['orderBy'] }, OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<TArgs['orderBy']>>>, ByFields extends Prisma.MaybeTupleToUnion<TArgs['by']>, ByValid extends Prisma.Has<ByFields, OrderFields>, HavingFields extends Prisma.GetHavingFields<TArgs['having']>, HavingValid extends Prisma.Has<ByFields, HavingFields>, ByEmpty extends TArgs['by'] extends never[] ? Prisma.True : Prisma.False, InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
        ? never
        : P extends string
        ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
        : [
            Error,
            'Field ',
            P,
            ` in "having" needs to be provided in "by"`,
        ]
    }[HavingFields]
    : 'take' extends Prisma.Keys<TArgs>
    ? 'orderBy' extends Prisma.Keys<TArgs>
    ? ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields]
    : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<TArgs>
    ? 'orderBy' extends Prisma.Keys<TArgs>
    ? ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields]
    : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields], TQueryFnData = {} extends InputErrors ?
    Array<PickEnumerable<Prisma.TestCaseParameterGroupByOutputType, TArgs['by']> &
    {
        [P in ((keyof TArgs) & (keyof Prisma.TestCaseParameterGroupByOutputType))]: P extends '_count'
        ? TArgs[P] extends boolean
        ? number
        : Prisma.GetScalarType<TArgs[P], Prisma.TestCaseParameterGroupByOutputType[P]>
        : Prisma.GetScalarType<TArgs[P], Prisma.TestCaseParameterGroupByOutputType[P]>
    }
    > : InputErrors, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.SubsetIntersection<TArgs, Prisma.TestCaseParameterGroupByArgs, OrderByArg> & InputErrors>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('TestCaseParameter', `${endpoint}/testCaseParameter/groupBy`, args, options, fetch);
}

export function useCountTestCaseParameter<TArgs extends Prisma.TestCaseParameterCountArgs, TQueryFnData = TArgs extends { select: any; } ? TArgs['select'] extends true ? number : Prisma.GetScalarType<TArgs['select'], Prisma.TestCaseParameterCountAggregateOutputType> : number, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.TestCaseParameterCountArgs>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('TestCaseParameter', `${endpoint}/testCaseParameter/count`, args, options, fetch);
}

export function useSuspenseCountTestCaseParameter<TArgs extends Prisma.TestCaseParameterCountArgs, TQueryFnData = TArgs extends { select: any; } ? TArgs['select'] extends true ? number : Prisma.GetScalarType<TArgs['select'], Prisma.TestCaseParameterCountAggregateOutputType> : number, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.TestCaseParameterCountArgs>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('TestCaseParameter', `${endpoint}/testCaseParameter/count`, args, options, fetch);
}
import type { ParameterType } from '@prisma/client';

export function useCheckTestCaseParameter<TError = DefaultError>(args: { operation: PolicyCrudKind; where?: { id?: number; testCaseId?: number; name?: string; description?: string; type?: ParameterType; order?: number; required?: boolean; sensitive?: boolean; lookupDataSetId?: number; isDeleted?: boolean }; }, options?: (Omit<UseQueryOptions<boolean, TError, boolean>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<boolean, boolean, TError>('TestCaseParameter', `${endpoint}/testCaseParameter/check`, args, options, fetch);
}
