/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */

import type { Prisma, WebhookDelivery } from "@prisma/client";
import type { UseMutationOptions, UseQueryOptions, UseInfiniteQueryOptions, InfiniteData } from '@tanstack/react-query';
import { getHooksContext } from '@zenstackhq/tanstack-query/runtime-v5/react';
import { useModelQuery, useInfiniteModelQuery, useModelMutation } from '@zenstackhq/tanstack-query/runtime-v5/react';
import type { PickEnumerable, CheckSelect, QueryError, ExtraQueryOptions, ExtraMutationOptions } from '@zenstackhq/tanstack-query/runtime-v5';
import type { PolicyCrudKind } from '@zenstackhq/runtime'
import metadata from './__model_meta';
type DefaultError = QueryError;
import { useSuspenseModelQuery, useSuspenseInfiniteModelQuery } from '@zenstackhq/tanstack-query/runtime-v5/react';
import type { UseSuspenseQueryOptions, UseSuspenseInfiniteQueryOptions } from '@tanstack/react-query';

export function useCreateWebhookDelivery(options?: Omit<(UseMutationOptions<(WebhookDelivery | undefined), DefaultError, Prisma.WebhookDeliveryCreateArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.WebhookDeliveryCreateArgs, DefaultError, WebhookDelivery, true>('WebhookDelivery', 'POST', `${endpoint}/webhookDelivery/create`, metadata, options, fetch, true)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.WebhookDeliveryCreateArgs>(
            args: Prisma.SelectSubset<T, Prisma.WebhookDeliveryCreateArgs>,
            options?: Omit<(UseMutationOptions<(CheckSelect<T, WebhookDelivery, Prisma.WebhookDeliveryGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.WebhookDeliveryCreateArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as (CheckSelect<T, WebhookDelivery, Prisma.WebhookDeliveryGetPayload<T>> | undefined);
        },
    };
    return mutation;
}

export function useCreateManyWebhookDelivery(options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.WebhookDeliveryCreateManyArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.WebhookDeliveryCreateManyArgs, DefaultError, Prisma.BatchPayload, false>('WebhookDelivery', 'POST', `${endpoint}/webhookDelivery/createMany`, metadata, options, fetch, false)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.WebhookDeliveryCreateManyArgs>(
            args: Prisma.SelectSubset<T, Prisma.WebhookDeliveryCreateManyArgs>,
            options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.SelectSubset<T, Prisma.WebhookDeliveryCreateManyArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as Prisma.BatchPayload;
        },
    };
    return mutation;
}

export function useFindManyWebhookDelivery<TArgs extends Prisma.WebhookDeliveryFindManyArgs, TQueryFnData = Array<Prisma.WebhookDeliveryGetPayload<TArgs> & { $optimistic?: boolean }>, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.WebhookDeliveryFindManyArgs>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('WebhookDelivery', `${endpoint}/webhookDelivery/findMany`, args, options, fetch);
}

export function useInfiniteFindManyWebhookDelivery<TArgs extends Prisma.WebhookDeliveryFindManyArgs, TQueryFnData = Array<Prisma.WebhookDeliveryGetPayload<TArgs>>, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.WebhookDeliveryFindManyArgs>, options?: Omit<UseInfiniteQueryOptions<TQueryFnData, TError, InfiniteData<TData>>, 'queryKey' | 'initialPageParam'>) {
    options = options ?? { getNextPageParam: () => null };
    const { endpoint, fetch } = getHooksContext();
    return useInfiniteModelQuery<TQueryFnData, TData, TError>('WebhookDelivery', `${endpoint}/webhookDelivery/findMany`, args, options, fetch);
}

export function useSuspenseFindManyWebhookDelivery<TArgs extends Prisma.WebhookDeliveryFindManyArgs, TQueryFnData = Array<Prisma.WebhookDeliveryGetPayload<TArgs> & { $optimistic?: boolean }>, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.WebhookDeliveryFindManyArgs>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('WebhookDelivery', `${endpoint}/webhookDelivery/findMany`, args, options, fetch);
}

export function useSuspenseInfiniteFindManyWebhookDelivery<TArgs extends Prisma.WebhookDeliveryFindManyArgs, TQueryFnData = Array<Prisma.WebhookDeliveryGetPayload<TArgs>>, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.WebhookDeliveryFindManyArgs>, options?: Omit<UseSuspenseInfiniteQueryOptions<TQueryFnData, TError, InfiniteData<TData>>, 'queryKey' | 'initialPageParam'>) {
    options = options ?? { getNextPageParam: () => null };
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseInfiniteModelQuery<TQueryFnData, TData, TError>('WebhookDelivery', `${endpoint}/webhookDelivery/findMany`, args, options, fetch);
}

export function useFindUniqueWebhookDelivery<TArgs extends Prisma.WebhookDeliveryFindUniqueArgs, TQueryFnData = Prisma.WebhookDeliveryGetPayload<TArgs> & { $optimistic?: boolean }, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.WebhookDeliveryFindUniqueArgs>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('WebhookDelivery', `${endpoint}/webhookDelivery/findUnique`, args, options, fetch);
}

export function useSuspenseFindUniqueWebhookDelivery<TArgs extends Prisma.WebhookDeliveryFindUniqueArgs, TQueryFnData = Prisma.WebhookDeliveryGetPayload<TArgs> & { $optimistic?: boolean }, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.WebhookDeliveryFindUniqueArgs>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('WebhookDelivery', `${endpoint}/webhookDelivery/findUnique`, args, options, fetch);
}

export function useFindFirstWebhookDelivery<TArgs extends Prisma.WebhookDeliveryFindFirstArgs, TQueryFnData = Prisma.WebhookDeliveryGetPayload<TArgs> & { $optimistic?: boolean }, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.WebhookDeliveryFindFirstArgs>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('WebhookDelivery', `${endpoint}/webhookDelivery/findFirst`, args, options, fetch);
}

export function useSuspenseFindFirstWebhookDelivery<TArgs extends Prisma.WebhookDeliveryFindFirstArgs, TQueryFnData = Prisma.WebhookDeliveryGetPayload<TArgs> & { $optimistic?: boolean }, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.WebhookDeliveryFindFirstArgs>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('WebhookDelivery', `${endpoint}/webhookDelivery/findFirst`, args, options, fetch);
}

export function useUpdateWebhookDelivery(options?: Omit<(UseMutationOptions<(WebhookDelivery | undefined), DefaultError, Prisma.WebhookDeliveryUpdateArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.WebhookDeliveryUpdateArgs, DefaultError, WebhookDelivery, true>('WebhookDelivery', 'PUT', `${endpoint}/webhookDelivery/update`, metadata, options, fetch, true)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.WebhookDeliveryUpdateArgs>(
            args: Prisma.SelectSubset<T, Prisma.WebhookDeliveryUpdateArgs>,
            options?: Omit<(UseMutationOptions<(CheckSelect<T, WebhookDelivery, Prisma.WebhookDeliveryGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.WebhookDeliveryUpdateArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as (CheckSelect<T, WebhookDelivery, Prisma.WebhookDeliveryGetPayload<T>> | undefined);
        },
    };
    return mutation;
}

export function useUpdateManyWebhookDelivery(options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.WebhookDeliveryUpdateManyArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.WebhookDeliveryUpdateManyArgs, DefaultError, Prisma.BatchPayload, false>('WebhookDelivery', 'PUT', `${endpoint}/webhookDelivery/updateMany`, metadata, options, fetch, false)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.WebhookDeliveryUpdateManyArgs>(
            args: Prisma.SelectSubset<T, Prisma.WebhookDeliveryUpdateManyArgs>,
            options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.SelectSubset<T, Prisma.WebhookDeliveryUpdateManyArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as Prisma.BatchPayload;
        },
    };
    return mutation;
}

export function useUpsertWebhookDelivery(options?: Omit<(UseMutationOptions<(WebhookDelivery | undefined), DefaultError, Prisma.WebhookDeliveryUpsertArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.WebhookDeliveryUpsertArgs, DefaultError, WebhookDelivery, true>('WebhookDelivery', 'POST', `${endpoint}/webhookDelivery/upsert`, metadata, options, fetch, true)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.WebhookDeliveryUpsertArgs>(
            args: Prisma.SelectSubset<T, Prisma.WebhookDeliveryUpsertArgs>,
            options?: Omit<(UseMutationOptions<(CheckSelect<T, WebhookDelivery, Prisma.WebhookDeliveryGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.WebhookDeliveryUpsertArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as (CheckSelect<T, WebhookDelivery, Prisma.WebhookDeliveryGetPayload<T>> | undefined);
        },
    };
    return mutation;
}

export function useDeleteWebhookDelivery(options?: Omit<(UseMutationOptions<(WebhookDelivery | undefined), DefaultError, Prisma.WebhookDeliveryDeleteArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.WebhookDeliveryDeleteArgs, DefaultError, WebhookDelivery, true>('WebhookDelivery', 'DELETE', `${endpoint}/webhookDelivery/delete`, metadata, options, fetch, true)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.WebhookDeliveryDeleteArgs>(
            args: Prisma.SelectSubset<T, Prisma.WebhookDeliveryDeleteArgs>,
            options?: Omit<(UseMutationOptions<(CheckSelect<T, WebhookDelivery, Prisma.WebhookDeliveryGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.WebhookDeliveryDeleteArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as (CheckSelect<T, WebhookDelivery, Prisma.WebhookDeliveryGetPayload<T>> | undefined);
        },
    };
    return mutation;
}

export function useDeleteManyWebhookDelivery(options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.WebhookDeliveryDeleteManyArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.WebhookDeliveryDeleteManyArgs, DefaultError, Prisma.BatchPayload, false>('WebhookDelivery', 'DELETE', `${endpoint}/webhookDelivery/deleteMany`, metadata, options, fetch, false)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.WebhookDeliveryDeleteManyArgs>(
            args: Prisma.SelectSubset<T, Prisma.WebhookDeliveryDeleteManyArgs>,
            options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.SelectSubset<T, Prisma.WebhookDeliveryDeleteManyArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as Prisma.BatchPayload;
        },
    };
    return mutation;
}

export function useAggregateWebhookDelivery<TArgs extends Prisma.WebhookDeliveryAggregateArgs, TQueryFnData = Prisma.GetWebhookDeliveryAggregateType<TArgs>, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.WebhookDeliveryAggregateArgs>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('WebhookDelivery', `${endpoint}/webhookDelivery/aggregate`, args, options, fetch);
}

export function useSuspenseAggregateWebhookDelivery<TArgs extends Prisma.WebhookDeliveryAggregateArgs, TQueryFnData = Prisma.GetWebhookDeliveryAggregateType<TArgs>, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.WebhookDeliveryAggregateArgs>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('WebhookDelivery', `${endpoint}/webhookDelivery/aggregate`, args, options, fetch);
}

export function useGroupByWebhookDelivery<TArgs extends Prisma.WebhookDeliveryGroupByArgs, HasSelectOrTake extends Prisma.Or<Prisma.Extends<'skip', Prisma.Keys<TArgs>>, Prisma.Extends<'take', Prisma.Keys<TArgs>>>, OrderByArg extends Prisma.True extends HasSelectOrTake ? { orderBy: Prisma.WebhookDeliveryGroupByArgs['orderBy'] } : { orderBy?: Prisma.WebhookDeliveryGroupByArgs['orderBy'] }, OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<TArgs['orderBy']>>>, ByFields extends Prisma.MaybeTupleToUnion<TArgs['by']>, ByValid extends Prisma.Has<ByFields, OrderFields>, HavingFields extends Prisma.GetHavingFields<TArgs['having']>, HavingValid extends Prisma.Has<ByFields, HavingFields>, ByEmpty extends TArgs['by'] extends never[] ? Prisma.True : Prisma.False, InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
        ? never
        : P extends string
        ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
        : [
            Error,
            'Field ',
            P,
            ` in "having" needs to be provided in "by"`,
        ]
    }[HavingFields]
    : 'take' extends Prisma.Keys<TArgs>
    ? 'orderBy' extends Prisma.Keys<TArgs>
    ? ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields]
    : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<TArgs>
    ? 'orderBy' extends Prisma.Keys<TArgs>
    ? ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields]
    : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields], TQueryFnData = {} extends InputErrors ?
    Array<PickEnumerable<Prisma.WebhookDeliveryGroupByOutputType, TArgs['by']> &
    {
        [P in ((keyof TArgs) & (keyof Prisma.WebhookDeliveryGroupByOutputType))]: P extends '_count'
        ? TArgs[P] extends boolean
        ? number
        : Prisma.GetScalarType<TArgs[P], Prisma.WebhookDeliveryGroupByOutputType[P]>
        : Prisma.GetScalarType<TArgs[P], Prisma.WebhookDeliveryGroupByOutputType[P]>
    }
    > : InputErrors, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.SubsetIntersection<TArgs, Prisma.WebhookDeliveryGroupByArgs, OrderByArg> & InputErrors>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('WebhookDelivery', `${endpoint}/webhookDelivery/groupBy`, args, options, fetch);
}

export function useSuspenseGroupByWebhookDelivery<TArgs extends Prisma.WebhookDeliveryGroupByArgs, HasSelectOrTake extends Prisma.Or<Prisma.Extends<'skip', Prisma.Keys<TArgs>>, Prisma.Extends<'take', Prisma.Keys<TArgs>>>, OrderByArg extends Prisma.True extends HasSelectOrTake ? { orderBy: Prisma.WebhookDeliveryGroupByArgs['orderBy'] } : { orderBy?: Prisma.WebhookDeliveryGroupByArgs['orderBy'] }, OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<TArgs['orderBy']>>>, ByFields extends Prisma.MaybeTupleToUnion<TArgs['by']>, ByValid extends Prisma.Has<ByFields, OrderFields>, HavingFields extends Prisma.GetHavingFields<TArgs['having']>, HavingValid extends Prisma.Has<ByFields, HavingFields>, ByEmpty extends TArgs['by'] extends never[] ? Prisma.True : Prisma.False, InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
        ? never
        : P extends string
        ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
        : [
            Error,
            'Field ',
            P,
            ` in "having" needs to be provided in "by"`,
        ]
    }[HavingFields]
    : 'take' extends Prisma.Keys<TArgs>
    ? 'orderBy' extends Prisma.Keys<TArgs>
    ? ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields]
    : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<TArgs>
    ? 'orderBy' extends Prisma.Keys<TArgs>
    ? ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields]
    : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields], TQueryFnData = {} extends InputErrors ?
    Array<PickEnumerable<Prisma.WebhookDeliveryGroupByOutputType, TArgs['by']> &
    {
        [P in ((keyof TArgs) & (keyof Prisma.WebhookDeliveryGroupByOutputType))]: P extends '_count'
        ? TArgs[P] extends boolean
        ? number
        : Prisma.GetScalarType<TArgs[P], Prisma.WebhookDeliveryGroupByOutputType[P]>
        : Prisma.GetScalarType<TArgs[P], Prisma.WebhookDeliveryGroupByOutputType[P]>
    }
    > : InputErrors, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.SubsetIntersection<TArgs, Prisma.WebhookDeliveryGroupByArgs, OrderByArg> & InputErrors>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('WebhookDelivery', `${endpoint}/webhookDelivery/groupBy`, args, options, fetch);
}

export function useCountWebhookDelivery<TArgs extends Prisma.WebhookDeliveryCountArgs, TQueryFnData = TArgs extends { select: any; } ? TArgs['select'] extends true ? number : Prisma.GetScalarType<TArgs['select'], Prisma.WebhookDeliveryCountAggregateOutputType> : number, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.WebhookDeliveryCountArgs>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('WebhookDelivery', `${endpoint}/webhookDelivery/count`, args, options, fetch);
}

export function useSuspenseCountWebhookDelivery<TArgs extends Prisma.WebhookDeliveryCountArgs, TQueryFnData = TArgs extends { select: any; } ? TArgs['select'] extends true ? number : Prisma.GetScalarType<TArgs['select'], Prisma.WebhookDeliveryCountAggregateOutputType> : number, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.WebhookDeliveryCountArgs>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('WebhookDelivery', `${endpoint}/webhookDelivery/count`, args, options, fetch);
}
import type { WebhookDirection, AdapterType } from '@prisma/client';

export function useCheckWebhookDelivery<TError = DefaultError>(args: { operation: PolicyCrudKind; where?: { id?: string; webhookConfigId?: string; direction?: WebhookDirection; adapterType?: AdapterType; eventType?: string; eventId?: string; statusCode?: number; latencyMs?: number; payloadDigest?: string; error?: string; attempt?: number; replayedFromDeliveryId?: string }; }, options?: (Omit<UseQueryOptions<boolean, TError, boolean>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<boolean, boolean, TError>('WebhookDelivery', `${endpoint}/webhookDelivery/check`, args, options, fetch);
}
