/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */

import type { Prisma, WebhookConfig } from "@prisma/client";
import type { UseMutationOptions, UseQueryOptions, UseInfiniteQueryOptions, InfiniteData } from '@tanstack/react-query';
import { getHooksContext } from '@zenstackhq/tanstack-query/runtime-v5/react';
import { useModelQuery, useInfiniteModelQuery, useModelMutation } from '@zenstackhq/tanstack-query/runtime-v5/react';
import type { PickEnumerable, CheckSelect, QueryError, ExtraQueryOptions, ExtraMutationOptions } from '@zenstackhq/tanstack-query/runtime-v5';
import type { PolicyCrudKind } from '@zenstackhq/runtime'
import metadata from './__model_meta';
type DefaultError = QueryError;
import { useSuspenseModelQuery, useSuspenseInfiniteModelQuery } from '@zenstackhq/tanstack-query/runtime-v5/react';
import type { UseSuspenseQueryOptions, UseSuspenseInfiniteQueryOptions } from '@tanstack/react-query';

export function useCreateWebhookConfig(options?: Omit<(UseMutationOptions<(WebhookConfig | undefined), DefaultError, Prisma.WebhookConfigCreateArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.WebhookConfigCreateArgs, DefaultError, WebhookConfig, true>('WebhookConfig', 'POST', `${endpoint}/webhookConfig/create`, metadata, options, fetch, true)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.WebhookConfigCreateArgs>(
            args: Prisma.SelectSubset<T, Prisma.WebhookConfigCreateArgs>,
            options?: Omit<(UseMutationOptions<(CheckSelect<T, WebhookConfig, Prisma.WebhookConfigGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.WebhookConfigCreateArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as (CheckSelect<T, WebhookConfig, Prisma.WebhookConfigGetPayload<T>> | undefined);
        },
    };
    return mutation;
}

export function useCreateManyWebhookConfig(options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.WebhookConfigCreateManyArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.WebhookConfigCreateManyArgs, DefaultError, Prisma.BatchPayload, false>('WebhookConfig', 'POST', `${endpoint}/webhookConfig/createMany`, metadata, options, fetch, false)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.WebhookConfigCreateManyArgs>(
            args: Prisma.SelectSubset<T, Prisma.WebhookConfigCreateManyArgs>,
            options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.SelectSubset<T, Prisma.WebhookConfigCreateManyArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as Prisma.BatchPayload;
        },
    };
    return mutation;
}

export function useFindManyWebhookConfig<TArgs extends Prisma.WebhookConfigFindManyArgs, TQueryFnData = Array<Prisma.WebhookConfigGetPayload<TArgs> & { $optimistic?: boolean }>, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.WebhookConfigFindManyArgs>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('WebhookConfig', `${endpoint}/webhookConfig/findMany`, args, options, fetch);
}

export function useInfiniteFindManyWebhookConfig<TArgs extends Prisma.WebhookConfigFindManyArgs, TQueryFnData = Array<Prisma.WebhookConfigGetPayload<TArgs>>, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.WebhookConfigFindManyArgs>, options?: Omit<UseInfiniteQueryOptions<TQueryFnData, TError, InfiniteData<TData>>, 'queryKey' | 'initialPageParam'>) {
    options = options ?? { getNextPageParam: () => null };
    const { endpoint, fetch } = getHooksContext();
    return useInfiniteModelQuery<TQueryFnData, TData, TError>('WebhookConfig', `${endpoint}/webhookConfig/findMany`, args, options, fetch);
}

export function useSuspenseFindManyWebhookConfig<TArgs extends Prisma.WebhookConfigFindManyArgs, TQueryFnData = Array<Prisma.WebhookConfigGetPayload<TArgs> & { $optimistic?: boolean }>, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.WebhookConfigFindManyArgs>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('WebhookConfig', `${endpoint}/webhookConfig/findMany`, args, options, fetch);
}

export function useSuspenseInfiniteFindManyWebhookConfig<TArgs extends Prisma.WebhookConfigFindManyArgs, TQueryFnData = Array<Prisma.WebhookConfigGetPayload<TArgs>>, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.WebhookConfigFindManyArgs>, options?: Omit<UseSuspenseInfiniteQueryOptions<TQueryFnData, TError, InfiniteData<TData>>, 'queryKey' | 'initialPageParam'>) {
    options = options ?? { getNextPageParam: () => null };
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseInfiniteModelQuery<TQueryFnData, TData, TError>('WebhookConfig', `${endpoint}/webhookConfig/findMany`, args, options, fetch);
}

export function useFindUniqueWebhookConfig<TArgs extends Prisma.WebhookConfigFindUniqueArgs, TQueryFnData = Prisma.WebhookConfigGetPayload<TArgs> & { $optimistic?: boolean }, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.WebhookConfigFindUniqueArgs>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('WebhookConfig', `${endpoint}/webhookConfig/findUnique`, args, options, fetch);
}

export function useSuspenseFindUniqueWebhookConfig<TArgs extends Prisma.WebhookConfigFindUniqueArgs, TQueryFnData = Prisma.WebhookConfigGetPayload<TArgs> & { $optimistic?: boolean }, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.WebhookConfigFindUniqueArgs>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('WebhookConfig', `${endpoint}/webhookConfig/findUnique`, args, options, fetch);
}

export function useFindFirstWebhookConfig<TArgs extends Prisma.WebhookConfigFindFirstArgs, TQueryFnData = Prisma.WebhookConfigGetPayload<TArgs> & { $optimistic?: boolean }, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.WebhookConfigFindFirstArgs>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('WebhookConfig', `${endpoint}/webhookConfig/findFirst`, args, options, fetch);
}

export function useSuspenseFindFirstWebhookConfig<TArgs extends Prisma.WebhookConfigFindFirstArgs, TQueryFnData = Prisma.WebhookConfigGetPayload<TArgs> & { $optimistic?: boolean }, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.WebhookConfigFindFirstArgs>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('WebhookConfig', `${endpoint}/webhookConfig/findFirst`, args, options, fetch);
}

export function useUpdateWebhookConfig(options?: Omit<(UseMutationOptions<(WebhookConfig | undefined), DefaultError, Prisma.WebhookConfigUpdateArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.WebhookConfigUpdateArgs, DefaultError, WebhookConfig, true>('WebhookConfig', 'PUT', `${endpoint}/webhookConfig/update`, metadata, options, fetch, true)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.WebhookConfigUpdateArgs>(
            args: Prisma.SelectSubset<T, Prisma.WebhookConfigUpdateArgs>,
            options?: Omit<(UseMutationOptions<(CheckSelect<T, WebhookConfig, Prisma.WebhookConfigGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.WebhookConfigUpdateArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as (CheckSelect<T, WebhookConfig, Prisma.WebhookConfigGetPayload<T>> | undefined);
        },
    };
    return mutation;
}

export function useUpdateManyWebhookConfig(options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.WebhookConfigUpdateManyArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.WebhookConfigUpdateManyArgs, DefaultError, Prisma.BatchPayload, false>('WebhookConfig', 'PUT', `${endpoint}/webhookConfig/updateMany`, metadata, options, fetch, false)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.WebhookConfigUpdateManyArgs>(
            args: Prisma.SelectSubset<T, Prisma.WebhookConfigUpdateManyArgs>,
            options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.SelectSubset<T, Prisma.WebhookConfigUpdateManyArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as Prisma.BatchPayload;
        },
    };
    return mutation;
}

export function useUpsertWebhookConfig(options?: Omit<(UseMutationOptions<(WebhookConfig | undefined), DefaultError, Prisma.WebhookConfigUpsertArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.WebhookConfigUpsertArgs, DefaultError, WebhookConfig, true>('WebhookConfig', 'POST', `${endpoint}/webhookConfig/upsert`, metadata, options, fetch, true)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.WebhookConfigUpsertArgs>(
            args: Prisma.SelectSubset<T, Prisma.WebhookConfigUpsertArgs>,
            options?: Omit<(UseMutationOptions<(CheckSelect<T, WebhookConfig, Prisma.WebhookConfigGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.WebhookConfigUpsertArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as (CheckSelect<T, WebhookConfig, Prisma.WebhookConfigGetPayload<T>> | undefined);
        },
    };
    return mutation;
}

export function useDeleteWebhookConfig(options?: Omit<(UseMutationOptions<(WebhookConfig | undefined), DefaultError, Prisma.WebhookConfigDeleteArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.WebhookConfigDeleteArgs, DefaultError, WebhookConfig, true>('WebhookConfig', 'DELETE', `${endpoint}/webhookConfig/delete`, metadata, options, fetch, true)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.WebhookConfigDeleteArgs>(
            args: Prisma.SelectSubset<T, Prisma.WebhookConfigDeleteArgs>,
            options?: Omit<(UseMutationOptions<(CheckSelect<T, WebhookConfig, Prisma.WebhookConfigGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.WebhookConfigDeleteArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as (CheckSelect<T, WebhookConfig, Prisma.WebhookConfigGetPayload<T>> | undefined);
        },
    };
    return mutation;
}

export function useDeleteManyWebhookConfig(options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.WebhookConfigDeleteManyArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.WebhookConfigDeleteManyArgs, DefaultError, Prisma.BatchPayload, false>('WebhookConfig', 'DELETE', `${endpoint}/webhookConfig/deleteMany`, metadata, options, fetch, false)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.WebhookConfigDeleteManyArgs>(
            args: Prisma.SelectSubset<T, Prisma.WebhookConfigDeleteManyArgs>,
            options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.SelectSubset<T, Prisma.WebhookConfigDeleteManyArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as Prisma.BatchPayload;
        },
    };
    return mutation;
}

export function useAggregateWebhookConfig<TArgs extends Prisma.WebhookConfigAggregateArgs, TQueryFnData = Prisma.GetWebhookConfigAggregateType<TArgs>, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.WebhookConfigAggregateArgs>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('WebhookConfig', `${endpoint}/webhookConfig/aggregate`, args, options, fetch);
}

export function useSuspenseAggregateWebhookConfig<TArgs extends Prisma.WebhookConfigAggregateArgs, TQueryFnData = Prisma.GetWebhookConfigAggregateType<TArgs>, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.WebhookConfigAggregateArgs>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('WebhookConfig', `${endpoint}/webhookConfig/aggregate`, args, options, fetch);
}

export function useGroupByWebhookConfig<TArgs extends Prisma.WebhookConfigGroupByArgs, HasSelectOrTake extends Prisma.Or<Prisma.Extends<'skip', Prisma.Keys<TArgs>>, Prisma.Extends<'take', Prisma.Keys<TArgs>>>, OrderByArg extends Prisma.True extends HasSelectOrTake ? { orderBy: Prisma.WebhookConfigGroupByArgs['orderBy'] } : { orderBy?: Prisma.WebhookConfigGroupByArgs['orderBy'] }, OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<TArgs['orderBy']>>>, ByFields extends Prisma.MaybeTupleToUnion<TArgs['by']>, ByValid extends Prisma.Has<ByFields, OrderFields>, HavingFields extends Prisma.GetHavingFields<TArgs['having']>, HavingValid extends Prisma.Has<ByFields, HavingFields>, ByEmpty extends TArgs['by'] extends never[] ? Prisma.True : Prisma.False, InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
        ? never
        : P extends string
        ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
        : [
            Error,
            'Field ',
            P,
            ` in "having" needs to be provided in "by"`,
        ]
    }[HavingFields]
    : 'take' extends Prisma.Keys<TArgs>
    ? 'orderBy' extends Prisma.Keys<TArgs>
    ? ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields]
    : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<TArgs>
    ? 'orderBy' extends Prisma.Keys<TArgs>
    ? ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields]
    : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields], TQueryFnData = {} extends InputErrors ?
    Array<PickEnumerable<Prisma.WebhookConfigGroupByOutputType, TArgs['by']> &
    {
        [P in ((keyof TArgs) & (keyof Prisma.WebhookConfigGroupByOutputType))]: P extends '_count'
        ? TArgs[P] extends boolean
        ? number
        : Prisma.GetScalarType<TArgs[P], Prisma.WebhookConfigGroupByOutputType[P]>
        : Prisma.GetScalarType<TArgs[P], Prisma.WebhookConfigGroupByOutputType[P]>
    }
    > : InputErrors, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.SubsetIntersection<TArgs, Prisma.WebhookConfigGroupByArgs, OrderByArg> & InputErrors>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('WebhookConfig', `${endpoint}/webhookConfig/groupBy`, args, options, fetch);
}

export function useSuspenseGroupByWebhookConfig<TArgs extends Prisma.WebhookConfigGroupByArgs, HasSelectOrTake extends Prisma.Or<Prisma.Extends<'skip', Prisma.Keys<TArgs>>, Prisma.Extends<'take', Prisma.Keys<TArgs>>>, OrderByArg extends Prisma.True extends HasSelectOrTake ? { orderBy: Prisma.WebhookConfigGroupByArgs['orderBy'] } : { orderBy?: Prisma.WebhookConfigGroupByArgs['orderBy'] }, OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<TArgs['orderBy']>>>, ByFields extends Prisma.MaybeTupleToUnion<TArgs['by']>, ByValid extends Prisma.Has<ByFields, OrderFields>, HavingFields extends Prisma.GetHavingFields<TArgs['having']>, HavingValid extends Prisma.Has<ByFields, HavingFields>, ByEmpty extends TArgs['by'] extends never[] ? Prisma.True : Prisma.False, InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
        ? never
        : P extends string
        ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
        : [
            Error,
            'Field ',
            P,
            ` in "having" needs to be provided in "by"`,
        ]
    }[HavingFields]
    : 'take' extends Prisma.Keys<TArgs>
    ? 'orderBy' extends Prisma.Keys<TArgs>
    ? ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields]
    : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<TArgs>
    ? 'orderBy' extends Prisma.Keys<TArgs>
    ? ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields]
    : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields], TQueryFnData = {} extends InputErrors ?
    Array<PickEnumerable<Prisma.WebhookConfigGroupByOutputType, TArgs['by']> &
    {
        [P in ((keyof TArgs) & (keyof Prisma.WebhookConfigGroupByOutputType))]: P extends '_count'
        ? TArgs[P] extends boolean
        ? number
        : Prisma.GetScalarType<TArgs[P], Prisma.WebhookConfigGroupByOutputType[P]>
        : Prisma.GetScalarType<TArgs[P], Prisma.WebhookConfigGroupByOutputType[P]>
    }
    > : InputErrors, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.SubsetIntersection<TArgs, Prisma.WebhookConfigGroupByArgs, OrderByArg> & InputErrors>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('WebhookConfig', `${endpoint}/webhookConfig/groupBy`, args, options, fetch);
}

export function useCountWebhookConfig<TArgs extends Prisma.WebhookConfigCountArgs, TQueryFnData = TArgs extends { select: any; } ? TArgs['select'] extends true ? number : Prisma.GetScalarType<TArgs['select'], Prisma.WebhookConfigCountAggregateOutputType> : number, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.WebhookConfigCountArgs>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('WebhookConfig', `${endpoint}/webhookConfig/count`, args, options, fetch);
}

export function useSuspenseCountWebhookConfig<TArgs extends Prisma.WebhookConfigCountArgs, TQueryFnData = TArgs extends { select: any; } ? TArgs['select'] extends true ? number : Prisma.GetScalarType<TArgs['select'], Prisma.WebhookConfigCountAggregateOutputType> : number, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.WebhookConfigCountArgs>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('WebhookConfig', `${endpoint}/webhookConfig/count`, args, options, fetch);
}
import type { AdapterType, WebhookDirection } from '@prisma/client';

export function useCheckWebhookConfig<TError = DefaultError>(args: { operation: PolicyCrudKind; where?: { id?: string; projectId?: number; adapterType?: AdapterType; direction?: WebhookDirection; token?: string; secret?: string; isActive?: boolean }; }, options?: (Omit<UseQueryOptions<boolean, TError, boolean>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<boolean, boolean, TError>('WebhookConfig', `${endpoint}/webhookConfig/check`, args, options, fetch);
}
