/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */

import type { Prisma, WebhookEventDedup } from "@prisma/client";
import type { UseMutationOptions, UseQueryOptions, UseInfiniteQueryOptions, InfiniteData } from '@tanstack/react-query';
import { getHooksContext } from '@zenstackhq/tanstack-query/runtime-v5/react';
import { useModelQuery, useInfiniteModelQuery, useModelMutation } from '@zenstackhq/tanstack-query/runtime-v5/react';
import type { PickEnumerable, CheckSelect, QueryError, ExtraQueryOptions, ExtraMutationOptions } from '@zenstackhq/tanstack-query/runtime-v5';
import type { PolicyCrudKind } from '@zenstackhq/runtime'
import metadata from './__model_meta';
type DefaultError = QueryError;
import { useSuspenseModelQuery, useSuspenseInfiniteModelQuery } from '@zenstackhq/tanstack-query/runtime-v5/react';
import type { UseSuspenseQueryOptions, UseSuspenseInfiniteQueryOptions } from '@tanstack/react-query';

export function useCreateWebhookEventDedup(options?: Omit<(UseMutationOptions<(WebhookEventDedup | undefined), DefaultError, Prisma.WebhookEventDedupCreateArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.WebhookEventDedupCreateArgs, DefaultError, WebhookEventDedup, true>('WebhookEventDedup', 'POST', `${endpoint}/webhookEventDedup/create`, metadata, options, fetch, true)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.WebhookEventDedupCreateArgs>(
            args: Prisma.SelectSubset<T, Prisma.WebhookEventDedupCreateArgs>,
            options?: Omit<(UseMutationOptions<(CheckSelect<T, WebhookEventDedup, Prisma.WebhookEventDedupGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.WebhookEventDedupCreateArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as (CheckSelect<T, WebhookEventDedup, Prisma.WebhookEventDedupGetPayload<T>> | undefined);
        },
    };
    return mutation;
}

export function useCreateManyWebhookEventDedup(options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.WebhookEventDedupCreateManyArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.WebhookEventDedupCreateManyArgs, DefaultError, Prisma.BatchPayload, false>('WebhookEventDedup', 'POST', `${endpoint}/webhookEventDedup/createMany`, metadata, options, fetch, false)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.WebhookEventDedupCreateManyArgs>(
            args: Prisma.SelectSubset<T, Prisma.WebhookEventDedupCreateManyArgs>,
            options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.SelectSubset<T, Prisma.WebhookEventDedupCreateManyArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as Prisma.BatchPayload;
        },
    };
    return mutation;
}

export function useFindManyWebhookEventDedup<TArgs extends Prisma.WebhookEventDedupFindManyArgs, TQueryFnData = Array<Prisma.WebhookEventDedupGetPayload<TArgs> & { $optimistic?: boolean }>, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.WebhookEventDedupFindManyArgs>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('WebhookEventDedup', `${endpoint}/webhookEventDedup/findMany`, args, options, fetch);
}

export function useInfiniteFindManyWebhookEventDedup<TArgs extends Prisma.WebhookEventDedupFindManyArgs, TQueryFnData = Array<Prisma.WebhookEventDedupGetPayload<TArgs>>, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.WebhookEventDedupFindManyArgs>, options?: Omit<UseInfiniteQueryOptions<TQueryFnData, TError, InfiniteData<TData>>, 'queryKey' | 'initialPageParam'>) {
    options = options ?? { getNextPageParam: () => null };
    const { endpoint, fetch } = getHooksContext();
    return useInfiniteModelQuery<TQueryFnData, TData, TError>('WebhookEventDedup', `${endpoint}/webhookEventDedup/findMany`, args, options, fetch);
}

export function useSuspenseFindManyWebhookEventDedup<TArgs extends Prisma.WebhookEventDedupFindManyArgs, TQueryFnData = Array<Prisma.WebhookEventDedupGetPayload<TArgs> & { $optimistic?: boolean }>, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.WebhookEventDedupFindManyArgs>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('WebhookEventDedup', `${endpoint}/webhookEventDedup/findMany`, args, options, fetch);
}

export function useSuspenseInfiniteFindManyWebhookEventDedup<TArgs extends Prisma.WebhookEventDedupFindManyArgs, TQueryFnData = Array<Prisma.WebhookEventDedupGetPayload<TArgs>>, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.WebhookEventDedupFindManyArgs>, options?: Omit<UseSuspenseInfiniteQueryOptions<TQueryFnData, TError, InfiniteData<TData>>, 'queryKey' | 'initialPageParam'>) {
    options = options ?? { getNextPageParam: () => null };
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseInfiniteModelQuery<TQueryFnData, TData, TError>('WebhookEventDedup', `${endpoint}/webhookEventDedup/findMany`, args, options, fetch);
}

export function useFindUniqueWebhookEventDedup<TArgs extends Prisma.WebhookEventDedupFindUniqueArgs, TQueryFnData = Prisma.WebhookEventDedupGetPayload<TArgs> & { $optimistic?: boolean }, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.WebhookEventDedupFindUniqueArgs>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('WebhookEventDedup', `${endpoint}/webhookEventDedup/findUnique`, args, options, fetch);
}

export function useSuspenseFindUniqueWebhookEventDedup<TArgs extends Prisma.WebhookEventDedupFindUniqueArgs, TQueryFnData = Prisma.WebhookEventDedupGetPayload<TArgs> & { $optimistic?: boolean }, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.WebhookEventDedupFindUniqueArgs>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('WebhookEventDedup', `${endpoint}/webhookEventDedup/findUnique`, args, options, fetch);
}

export function useFindFirstWebhookEventDedup<TArgs extends Prisma.WebhookEventDedupFindFirstArgs, TQueryFnData = Prisma.WebhookEventDedupGetPayload<TArgs> & { $optimistic?: boolean }, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.WebhookEventDedupFindFirstArgs>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('WebhookEventDedup', `${endpoint}/webhookEventDedup/findFirst`, args, options, fetch);
}

export function useSuspenseFindFirstWebhookEventDedup<TArgs extends Prisma.WebhookEventDedupFindFirstArgs, TQueryFnData = Prisma.WebhookEventDedupGetPayload<TArgs> & { $optimistic?: boolean }, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.WebhookEventDedupFindFirstArgs>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('WebhookEventDedup', `${endpoint}/webhookEventDedup/findFirst`, args, options, fetch);
}

export function useUpdateWebhookEventDedup(options?: Omit<(UseMutationOptions<(WebhookEventDedup | undefined), DefaultError, Prisma.WebhookEventDedupUpdateArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.WebhookEventDedupUpdateArgs, DefaultError, WebhookEventDedup, true>('WebhookEventDedup', 'PUT', `${endpoint}/webhookEventDedup/update`, metadata, options, fetch, true)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.WebhookEventDedupUpdateArgs>(
            args: Prisma.SelectSubset<T, Prisma.WebhookEventDedupUpdateArgs>,
            options?: Omit<(UseMutationOptions<(CheckSelect<T, WebhookEventDedup, Prisma.WebhookEventDedupGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.WebhookEventDedupUpdateArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as (CheckSelect<T, WebhookEventDedup, Prisma.WebhookEventDedupGetPayload<T>> | undefined);
        },
    };
    return mutation;
}

export function useUpdateManyWebhookEventDedup(options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.WebhookEventDedupUpdateManyArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.WebhookEventDedupUpdateManyArgs, DefaultError, Prisma.BatchPayload, false>('WebhookEventDedup', 'PUT', `${endpoint}/webhookEventDedup/updateMany`, metadata, options, fetch, false)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.WebhookEventDedupUpdateManyArgs>(
            args: Prisma.SelectSubset<T, Prisma.WebhookEventDedupUpdateManyArgs>,
            options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.SelectSubset<T, Prisma.WebhookEventDedupUpdateManyArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as Prisma.BatchPayload;
        },
    };
    return mutation;
}

export function useUpsertWebhookEventDedup(options?: Omit<(UseMutationOptions<(WebhookEventDedup | undefined), DefaultError, Prisma.WebhookEventDedupUpsertArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.WebhookEventDedupUpsertArgs, DefaultError, WebhookEventDedup, true>('WebhookEventDedup', 'POST', `${endpoint}/webhookEventDedup/upsert`, metadata, options, fetch, true)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.WebhookEventDedupUpsertArgs>(
            args: Prisma.SelectSubset<T, Prisma.WebhookEventDedupUpsertArgs>,
            options?: Omit<(UseMutationOptions<(CheckSelect<T, WebhookEventDedup, Prisma.WebhookEventDedupGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.WebhookEventDedupUpsertArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as (CheckSelect<T, WebhookEventDedup, Prisma.WebhookEventDedupGetPayload<T>> | undefined);
        },
    };
    return mutation;
}

export function useDeleteWebhookEventDedup(options?: Omit<(UseMutationOptions<(WebhookEventDedup | undefined), DefaultError, Prisma.WebhookEventDedupDeleteArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.WebhookEventDedupDeleteArgs, DefaultError, WebhookEventDedup, true>('WebhookEventDedup', 'DELETE', `${endpoint}/webhookEventDedup/delete`, metadata, options, fetch, true)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.WebhookEventDedupDeleteArgs>(
            args: Prisma.SelectSubset<T, Prisma.WebhookEventDedupDeleteArgs>,
            options?: Omit<(UseMutationOptions<(CheckSelect<T, WebhookEventDedup, Prisma.WebhookEventDedupGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.WebhookEventDedupDeleteArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as (CheckSelect<T, WebhookEventDedup, Prisma.WebhookEventDedupGetPayload<T>> | undefined);
        },
    };
    return mutation;
}

export function useDeleteManyWebhookEventDedup(options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.WebhookEventDedupDeleteManyArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.WebhookEventDedupDeleteManyArgs, DefaultError, Prisma.BatchPayload, false>('WebhookEventDedup', 'DELETE', `${endpoint}/webhookEventDedup/deleteMany`, metadata, options, fetch, false)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.WebhookEventDedupDeleteManyArgs>(
            args: Prisma.SelectSubset<T, Prisma.WebhookEventDedupDeleteManyArgs>,
            options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.SelectSubset<T, Prisma.WebhookEventDedupDeleteManyArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as Prisma.BatchPayload;
        },
    };
    return mutation;
}

export function useAggregateWebhookEventDedup<TArgs extends Prisma.WebhookEventDedupAggregateArgs, TQueryFnData = Prisma.GetWebhookEventDedupAggregateType<TArgs>, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.WebhookEventDedupAggregateArgs>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('WebhookEventDedup', `${endpoint}/webhookEventDedup/aggregate`, args, options, fetch);
}

export function useSuspenseAggregateWebhookEventDedup<TArgs extends Prisma.WebhookEventDedupAggregateArgs, TQueryFnData = Prisma.GetWebhookEventDedupAggregateType<TArgs>, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.WebhookEventDedupAggregateArgs>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('WebhookEventDedup', `${endpoint}/webhookEventDedup/aggregate`, args, options, fetch);
}

export function useGroupByWebhookEventDedup<TArgs extends Prisma.WebhookEventDedupGroupByArgs, HasSelectOrTake extends Prisma.Or<Prisma.Extends<'skip', Prisma.Keys<TArgs>>, Prisma.Extends<'take', Prisma.Keys<TArgs>>>, OrderByArg extends Prisma.True extends HasSelectOrTake ? { orderBy: Prisma.WebhookEventDedupGroupByArgs['orderBy'] } : { orderBy?: Prisma.WebhookEventDedupGroupByArgs['orderBy'] }, OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<TArgs['orderBy']>>>, ByFields extends Prisma.MaybeTupleToUnion<TArgs['by']>, ByValid extends Prisma.Has<ByFields, OrderFields>, HavingFields extends Prisma.GetHavingFields<TArgs['having']>, HavingValid extends Prisma.Has<ByFields, HavingFields>, ByEmpty extends TArgs['by'] extends never[] ? Prisma.True : Prisma.False, InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
        ? never
        : P extends string
        ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
        : [
            Error,
            'Field ',
            P,
            ` in "having" needs to be provided in "by"`,
        ]
    }[HavingFields]
    : 'take' extends Prisma.Keys<TArgs>
    ? 'orderBy' extends Prisma.Keys<TArgs>
    ? ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields]
    : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<TArgs>
    ? 'orderBy' extends Prisma.Keys<TArgs>
    ? ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields]
    : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields], TQueryFnData = {} extends InputErrors ?
    Array<PickEnumerable<Prisma.WebhookEventDedupGroupByOutputType, TArgs['by']> &
    {
        [P in ((keyof TArgs) & (keyof Prisma.WebhookEventDedupGroupByOutputType))]: P extends '_count'
        ? TArgs[P] extends boolean
        ? number
        : Prisma.GetScalarType<TArgs[P], Prisma.WebhookEventDedupGroupByOutputType[P]>
        : Prisma.GetScalarType<TArgs[P], Prisma.WebhookEventDedupGroupByOutputType[P]>
    }
    > : InputErrors, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.SubsetIntersection<TArgs, Prisma.WebhookEventDedupGroupByArgs, OrderByArg> & InputErrors>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('WebhookEventDedup', `${endpoint}/webhookEventDedup/groupBy`, args, options, fetch);
}

export function useSuspenseGroupByWebhookEventDedup<TArgs extends Prisma.WebhookEventDedupGroupByArgs, HasSelectOrTake extends Prisma.Or<Prisma.Extends<'skip', Prisma.Keys<TArgs>>, Prisma.Extends<'take', Prisma.Keys<TArgs>>>, OrderByArg extends Prisma.True extends HasSelectOrTake ? { orderBy: Prisma.WebhookEventDedupGroupByArgs['orderBy'] } : { orderBy?: Prisma.WebhookEventDedupGroupByArgs['orderBy'] }, OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<TArgs['orderBy']>>>, ByFields extends Prisma.MaybeTupleToUnion<TArgs['by']>, ByValid extends Prisma.Has<ByFields, OrderFields>, HavingFields extends Prisma.GetHavingFields<TArgs['having']>, HavingValid extends Prisma.Has<ByFields, HavingFields>, ByEmpty extends TArgs['by'] extends never[] ? Prisma.True : Prisma.False, InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
        ? never
        : P extends string
        ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
        : [
            Error,
            'Field ',
            P,
            ` in "having" needs to be provided in "by"`,
        ]
    }[HavingFields]
    : 'take' extends Prisma.Keys<TArgs>
    ? 'orderBy' extends Prisma.Keys<TArgs>
    ? ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields]
    : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<TArgs>
    ? 'orderBy' extends Prisma.Keys<TArgs>
    ? ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields]
    : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields], TQueryFnData = {} extends InputErrors ?
    Array<PickEnumerable<Prisma.WebhookEventDedupGroupByOutputType, TArgs['by']> &
    {
        [P in ((keyof TArgs) & (keyof Prisma.WebhookEventDedupGroupByOutputType))]: P extends '_count'
        ? TArgs[P] extends boolean
        ? number
        : Prisma.GetScalarType<TArgs[P], Prisma.WebhookEventDedupGroupByOutputType[P]>
        : Prisma.GetScalarType<TArgs[P], Prisma.WebhookEventDedupGroupByOutputType[P]>
    }
    > : InputErrors, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.SubsetIntersection<TArgs, Prisma.WebhookEventDedupGroupByArgs, OrderByArg> & InputErrors>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('WebhookEventDedup', `${endpoint}/webhookEventDedup/groupBy`, args, options, fetch);
}

export function useCountWebhookEventDedup<TArgs extends Prisma.WebhookEventDedupCountArgs, TQueryFnData = TArgs extends { select: any; } ? TArgs['select'] extends true ? number : Prisma.GetScalarType<TArgs['select'], Prisma.WebhookEventDedupCountAggregateOutputType> : number, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.WebhookEventDedupCountArgs>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('WebhookEventDedup', `${endpoint}/webhookEventDedup/count`, args, options, fetch);
}

export function useSuspenseCountWebhookEventDedup<TArgs extends Prisma.WebhookEventDedupCountArgs, TQueryFnData = TArgs extends { select: any; } ? TArgs['select'] extends true ? number : Prisma.GetScalarType<TArgs['select'], Prisma.WebhookEventDedupCountAggregateOutputType> : number, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.WebhookEventDedupCountArgs>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('WebhookEventDedup', `${endpoint}/webhookEventDedup/count`, args, options, fetch);
}

export function useCheckWebhookEventDedup<TError = DefaultError>(args: { operation: PolicyCrudKind; where?: { id?: string; webhookConfigId?: string; payloadDigest?: string }; }, options?: (Omit<UseQueryOptions<boolean, TError, boolean>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<boolean, boolean, TError>('WebhookEventDedup', `${endpoint}/webhookEventDedup/check`, args, options, fetch);
}
