import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import type {
  TestRunCasesSelect,
} from "@db/input";
import * as z from "zod/v4";
import { zenstack } from "../../api.js";
import type { EnvConfig } from "../../env.js";
import { mapHttpErrorToToolResult } from "../../errors.js";
import {
  runDetailTestCaseInclude,
  mapRunDetailTestCase,
  type RawRunDetailTestCase,
} from "./shared.js";

export interface RunsCasesUpdateDeps {
  env: EnvConfig;
}

export function registerRunsCasesUpdate(
  server: McpServer,
  deps: RunsCasesUpdateDeps,
): void {
  server.registerTool(
    "testplanit_runs_cases_update",
    {
      description:
        "Edit a test case's row WITHIN a run: assign/unassign a tester (assignedToId) or move it to a new position (order). Identify the row by testRunCaseId — the `id` on rows from testplanit_test_runs_cases_list / testplanit_test_runs_get testCases (NOT repositoryCase.id). All fields except testRunCaseId are optional — only supplied fields change. To change the case's execution status, submit a result via testplanit_test_run_results_create instead; to edit the case's CONTENT (name, steps, tags, custom fields), use testplanit_cases_update with the row's repositoryCase.id. Fails when the parent run is completed (row is frozen); `order` is additionally frozen while the run is composition-locked (execution started). Returns the updated row in the same shape as testplanit_test_runs_cases_list.",
      inputSchema: {
        testRunCaseId: z
          .number()
          .int()
          .positive()
          .describe("ID of the TestRunCase row to update."),
        // assignedToId is a String FK on TestRunCases — User PKs are strings
        // throughout TestPlanIt (Postgres uuid generated by NextAuth).
        assignedToId: z
          .string()
          .min(1)
          .nullable()
          .optional()
          .describe("User ID (string) to assign the case to; null to unassign."),
        order: z
          .number()
          .int()
          .nonnegative()
          .optional()
          .describe("New sort position within the run."),
      },
    },
    async (input) => {
      try {
        // Fetch the row head first — validates existence, exposes testRunId
        // for the run-scoped re-fetch include, and catches soft-removed rows
        // before any write.
        const head = await zenstack<{
          id: number;
          testRunId: number;
          isDeleted: boolean;
        } | null>(
          "testRunCases",
          "findUnique",
          {
            where: { id: input.testRunCaseId },
            select: {
              id: true,
              testRunId: true,
              isDeleted: true,
            } satisfies TestRunCasesSelect,
          },
          deps.env,
        );
        if (!head) {
          return {
            isError: true as const,
            content: [
              {
                type: "text" as const,
                text: `TestRunCase ${input.testRunCaseId} not found.`,
              },
            ],
          };
        }
        if (head.isDeleted) {
          return {
            isError: true as const,
            content: [
              {
                type: "text" as const,
                text: `TestRunCase ${input.testRunCaseId} was removed from the run. Re-add the case via testplanit_runs_cases_add first.`,
              },
            ],
          };
        }

        const data: Record<string, unknown> = {};
        if (input.assignedToId !== undefined) {
          data.assignedToId = input.assignedToId;
        }
        if (input.order !== undefined) {
          data.order = input.order;
        }

        if (Object.keys(data).length === 0) {
          return {
            isError: true as const,
            content: [
              {
                type: "text" as const,
                text: "No fields to update — provide at least one optional field.",
              },
            ],
          };
        }

        await zenstack(
          "testRunCases",
          "update",
          {
            where: { id: input.testRunCaseId },
            data,
            select: { id: true },
          },
          deps.env,
        );

        // Re-fetch with the same run-scoped include the list tool uses so the
        // returned row carries repositoryCase / assignedTo / status /
        // latestResult in the familiar shape.
        const raw = await zenstack<RawRunDetailTestCase | null>(
          "testRunCases",
          "findUnique",
          {
            where: { id: input.testRunCaseId },
            include: runDetailTestCaseInclude(head.testRunId),
          },
          deps.env,
        );
        if (!raw) {
          return {
            isError: true as const,
            content: [
              {
                type: "text" as const,
                text: `TestRunCase ${input.testRunCaseId} not found after update.`,
              },
            ],
          };
        }

        const row = mapRunDetailTestCase(raw);
        return {
          content: [{ type: "text", text: JSON.stringify(row) }],
          structuredContent: row as unknown as Record<string, unknown>,
        };
      } catch (err) {
        return mapHttpErrorToToolResult(err);
      }
    },
  );
}
