import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import type {
  TestRunCasesWhereInput,
} from "@db/input";
import * as z from "zod/v4";
import { zenstack } from "../../api.js";
import type { EnvConfig } from "../../env.js";
import { mapHttpErrorToToolResult } from "../../errors.js";
import {
  RUN_DETAIL_TESTCASE_INCLUDE,
  mapRunDetailTestCase,
  type RawRunDetailTestCase,
} from "./shared.js";

export interface RunsCasesListDeps {
  env: EnvConfig;
}

const DEFAULT_LIMIT = 25;
const MAX_LIMIT = 100;

export function registerRunsCasesList(
  server: McpServer,
  deps: RunsCasesListDeps,
): void {
  server.registerTool(
    "testplanit_test_runs_cases_list",
    {
      description:
        "List the test cases assigned to a specific run. Filters: isCompleted, statusId, assignedToId (user id, string). Cursor pagination ordered by `order` then `id`. NOTE: TestRunCases does not have a soft-delete field — case removal from a run is via direct deletion (cascading from the run), not isDeleted. Each row carries `latestResult` (most recent executedAt) inline. (per EXEC-03 / D7-05)",
      inputSchema: {
        runId: z.number().int().positive(),
        isCompleted: z.boolean().optional(),
        statusId: z.number().int().positive().optional(),
        // assignedToId is a String FK on TestRunCases — User PKs are strings
        // throughout TestPlanIt (Postgres uuid generated by NextAuth).
        assignedToId: z.string().min(1).optional(),
        cursor: z.number().int().positive().optional(),
        limit: z.number().int().positive().max(MAX_LIMIT).optional(),
      },
    },
    async (input) => {
      try {
        const limit = input.limit ?? DEFAULT_LIMIT;
        // R1: TestRunCases has NO isDeleted column. The
        // `TestRunCasesWhereInput` annotation makes adding one a TS2353.
        const where: TestRunCasesWhereInput = {
          testRunId: input.runId,
        };
        if (input.isCompleted !== undefined) where.isCompleted = input.isCompleted;
        if (input.statusId !== undefined) where.statusId = input.statusId;
        if (input.assignedToId) where.assignedToId = input.assignedToId;

        const body: Record<string, unknown> = {
          where,
          include: RUN_DETAIL_TESTCASE_INCLUDE,
          // BL-04 deterministic ordering. `order` is the user-facing sort
          // index; `id` breaks ties for cases inserted with the same order.
          orderBy: [{ order: "asc" }, { id: "asc" }],
          take: limit + 1,
        };
        if (input.cursor !== undefined) {
          body.cursor = { id: input.cursor };
          body.skip = 1;
        }

        const rows =
          (await zenstack<RawRunDetailTestCase[]>(
            "testRunCases",
            "findMany",
            body,
            deps.env,
          )) ?? [];
        const hasNextPage = rows.length > limit;
        const trimmed = rows.slice(0, limit);
        const items = trimmed.map(mapRunDetailTestCase);
        const nextCursor =
          hasNextPage && items.length > 0
            ? (items[items.length - 1] as { id: number }).id
            : null;

        const result = { items, hasNextPage, nextCursor };
        return {
          content: [{ type: "text", text: JSON.stringify(result) }],
          structuredContent: result as unknown as Record<string, unknown>,
        };
      } catch (err) {
        return mapHttpErrorToToolResult(err);
      }
    },
  );
}
