"use client";

import {
  Alert,
  AlertDescription,
  AlertTitle,
} from "@/components/ui/alert";
import { Button } from "@/components/ui/button";
import { formatDistanceToNow } from "date-fns";
import { MessageSquareWarning } from "lucide-react";
import { useSession } from "next-auth/react";
import { useTranslations } from "next-intl";
import { useMemo, useState } from "react";

import { useReviewFeatureEnabled } from "~/hooks/useReviewFeatureEnabled";
import { useFindFirstReviewRequest } from "~/lib/hooks";

import type { AssigneeOption } from "./AssigneeCombobox";
import { CancelRequestButton } from "./CancelRequestButton";
import {
  RequestReviewSheet,
  type ReachableGatedState,
  type ReviewableEntityType,
} from "./RequestReviewSheet";
import {
  REVIEW_STATUS_BANNER_INCLUDE,
  type ReviewStatusBannerRequest,
} from "./types";

export interface ReviewStatusBannerProps {
  entityType: ReviewableEntityType;
  entityId: number;
  projectId: number;
  /**
   * Reachable gated states for "Request review again" (CHANGES_REQUESTED /
   * REJECTED branches). Bulk-fetched at the entity-page level; if empty the
   * Request-again button still renders but the spawned Sheet will not allow
   * submission (mirrors RequestReviewButton's visibility predicate).
   */
  reachableGatedStates: ReachableGatedState[];
  /** Defaults to the entity's current state for `fromStateId` in the spawned Sheet. */
  currentStateId?: number;
}

// WR-07: BannerRequest is now an alias to the shared ReviewStatusBannerRequest
// type generated by Prisma. The ad-hoc literal is gone so a schema rename
// of any included relation surfaces here instead of crashing at runtime.
type BannerRequest = ReviewStatusBannerRequest;

/**
 * Status banner rendered directly above the entity's `WorkflowStateDisplay`
 * (per D-05). Three variant branches:
 *
 *   PENDING            → default Alert + relative-time message + Cancel CTA
 *                        (only for requester || admin per D-07)
 *   CHANGES_REQUESTED  → warning-styled Alert + decisionComment + Request-again
 *                        (warning composition per RESEARCH §"Example C" — the
 *                         project's `alertVariants` only ships `default` and
 *                         `destructive`, so warning is layered on via
 *                         className tokens rather than extending cva)
 *   REJECTED           → destructive variant + decisionComment + Request-again
 *
 * APPROVED + CANCELLED render nothing — the banner is the "do something"
 * surface; resolved-and-acted reviews drop out of the UI silently.
 *
 * Feature flag (D-12 / D-20): when disabled the banner returns null but the
 * underlying ReviewRequest rows are preserved in the database.
 *
 * `decisionComment` is rendered as plain text — NEVER `dangerouslySetInnerHTML`
 * per RESEARCH §"Security Domain".
 *
 * React Query `staleTime: 30_000` per RESEARCH §"Pitfall 4" prevents the
 * banner from flickering between renders.
 */
export function ReviewStatusBanner({
  entityType,
  entityId,
  projectId,
  reachableGatedStates,
  currentStateId,
}: ReviewStatusBannerProps) {
  const t = useTranslations();
  const { data: session } = useSession();
  const { enabled } = useReviewFeatureEnabled(projectId);
  const [requestAgainOpen, setRequestAgainOpen] = useState(false);

  const { data } = useFindFirstReviewRequest(
    {
      where: { entityType, entityId, isDeleted: false },
      orderBy: { createdAt: "desc" },
      include: REVIEW_STATUS_BANNER_INCLUDE,
    } as any,
    { staleTime: 30_000, refetchOnWindowFocus: false } as any,
  );

  const latest = data as BannerRequest | null | undefined;

  const assigneeLabel = useMemo(() => {
    if (!latest) return "";
    return (
      latest.assigneeUser?.name ?? latest.assigneeRole?.name ?? ""
    );
  }, [latest]);

  const initialValuesForRequestAgain = useMemo(() => {
    if (!latest) return undefined;
    const assignee: AssigneeOption | undefined = latest.assigneeUser
      ? {
          kind: "user",
          id: latest.assigneeUser.id,
          name: latest.assigneeUser.name ?? "",
          image: latest.assigneeUser.image ?? null,
          roleName: null,
        }
      : latest.assigneeRole
        ? {
            kind: "role",
            id: latest.assigneeRole.id,
            name: latest.assigneeRole.name,
            userCount: 0,
          }
        : undefined;

    return {
      assignee,
      targetStateId: latest.toStateId,
    };
  }, [latest]);

  if (!enabled) return null;
  if (!latest) return null;
  if (latest.status === "APPROVED" || latest.status === "CANCELLED") {
    return null;
  }

  const viewerIsRequester =
    session?.user?.id != null &&
    session.user.id === latest.requestedByUserId;
  const viewerIsAdmin =
    (session?.user as { access?: string } | undefined)?.access === "ADMIN";
  const canCancel = viewerIsRequester || viewerIsAdmin;

  if (latest.status === "PENDING") {
    const ago = formatDistanceToNow(new Date(latest.createdAt));
    return (
      <Alert data-testid="review-status-banner-pending" className="mb-2">
        <MessageSquareWarning className="h-4 w-4" />
        <AlertDescription className="flex items-center justify-between gap-2">
          <span>
            {t("reviews.banner.pendingMessage", {
              assignee: assigneeLabel,
              ago,
            })}
          </span>
          <CancelRequestButton
            reviewRequestId={latest.id}
            canCancel={canCancel}
          />
        </AlertDescription>
      </Alert>
    );
  }

  // CHANGES_REQUESTED + REJECTED share the same decision-rendered shape.
  const isRejected = latest.status === "REJECTED";

  return (
    <>
      <Alert
        data-testid={
          isRejected
            ? "review-status-banner-rejected"
            : "review-status-banner-changes-requested"
        }
        variant={isRejected ? "destructive" : "default"}
        className={
          isRejected
            ? "mb-2"
            : "mb-2 border-warning/50 bg-warning/10 text-warning [&>svg]:text-warning"
        }
      >
        <MessageSquareWarning className="h-4 w-4" />
        <AlertTitle>
          {isRejected
            ? t("reviews.banner.rejectedTitle")
            : t("reviews.banner.changesRequestedTitle")}
        </AlertTitle>
        <AlertDescription>
          {/*
            WR-09: clip oversized decisionComments at the banner so a 50KB
            paste from the Textarea (no maxLength today) doesn't blow up the
            layout. `whitespace-pre-line` preserves intentional line breaks,
            `line-clamp-6` caps the visible height to about six lines with a
            graceful ellipsis. Server-side max-length and a full
            "Show more" toggle remain as a v1.x polish item; this is the
            cheap defense for v1.
          */}
          <p
            className="mb-2 line-clamp-6 break-words whitespace-pre-line"
            data-testid="review-status-banner-decision-comment"
          >
            {latest.decisionComment ?? ""}
          </p>
          <Button
            type="button"
            variant="outline"
            size="sm"
            onClick={() => setRequestAgainOpen(true)}
            data-testid="request-review-again-button"
          >
            {t("reviews.banner.requestAgain")}
          </Button>
        </AlertDescription>
      </Alert>
      <RequestReviewSheet
        open={requestAgainOpen}
        onOpenChange={setRequestAgainOpen}
        entityType={entityType}
        entityId={entityId}
        projectId={projectId}
        currentStateId={currentStateId ?? latest.fromStateId}
        reachableGatedStates={reachableGatedStates}
        initialValues={initialValuesForRequestAgain}
      />
    </>
  );
}
